### ISSUE TITLE
Delegate responsibility for stopping and starting wazuh-db to the function make_query

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1057]
Hi,

Until now, when we are developing new tests that imply modifying wazuh dbs, we have to stop manually the `wazuh-db`, make the operation, and then start the `wazuh-db` service.

I propose to delegate this operation (stop and start `wazuh-db`) in the `make_query` function since it is the one that updates the `wazuh-db`.

This has the advantage that you don't have to worry about stopping and starting wazuh-db manually, since only the function that really needs it will do it.

On the other hand, and as a disadvantage, when several simultaneous operations are performed, the service will stop and start for each of them. Even so, I consider that the responsibility for this should be delegated to the make query function, reducing code and responsibility to the developer, avoiding unnecessary errors.

After doing this change, we have to check that the same flow is followed everywhere where `wazuh-db` is stopped and started manually.

Regards.

**Comment by BraulioV** [comment]
I've been doing some tests and I decided to follow a different approach for this. If we move the `stop` and `start` operations to the `make_query` function, we will heavily increase the time needed to run the test since each query will restart the daemon and there're some tests that run queries inside a loop.

So, I prefer to stop and start the daemons in a higher scope. The test will stop the daemons at the very beginning, mock the DB and start the daemons once again before running the test. To do so, I created a new decorator that will execute the same steps by just adding `@vd.mock_cve_db` before your mocking function.

You can see the changes in this branch: [add-mock-decorator](https://github.com/wazuh/wazuh-qa/tree/add-mock-decorator).
