### ISSUE TITLE
Investigate memory errors on tests using agent_simulator

### ISSUE THREAD

**Issue by Pac0x73706f74686f756e64** [wazuh/wazuh-qa#1085]
We've detected that some tests are causing troubles when executed in low-resourced machines (less than 4GB of RAM).
![image](https://user-images.githubusercontent.com/15269938/109024877-798bc900-76be-11eb-9544-5d1575bd3edf.png)

The cause seems to be the machine kernel killing pytest process because it is allocating too much memory:
```
Feb 24 14:44:52 centos-8 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-6.scope,task=python3,pid=8421,uid=0
Feb 24 14:44:52 centos-8 kernel: Out of memory: Killed process 8421 (python3) total-vm:4718512kB, anon-rss:1823664kB, file-rss:0kB, shmem-rss:0kB, UID:0
Feb 24 14:44:52 centos-8 kernel: oom_reaper: reaped process 8421 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

We've also experimented with some "MemoryError" exceptions running the root check tests.

We think that this may be related to the `receive_message` method on agent_simulator.

**Comment by BraulioV** [comment]
This was fixed in https://github.com/wazuh/wazuh-qa/pull/1106. The problem was located here: https://github.com/wazuh/wazuh-qa/blob/45ee2f2665991f4440f5bc6c4aa813f46602900b/deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py#L344-L347

The header of a TCP message contains the size of the message. This size is represented as an unsigned int (uint32) in binary, but the code was computing the size as a signed int. Then, if the sign bit was used, the size may change from a few bytes to gigabytes.

So, we forced to compute the size using uint32 with the `wazuh_unpack` function.
