### ISSUE TITLE
Performance test: automation in Jenkins 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1136]

**Comment by jmv74211** [comment]
We want to build a pipeline that automates the testing of a clustered environment of managers supporting a certain number of agents and events per second.

My proposed design to create the requested pipelines is as follows:

**Proposed pipeline tasks**

- **STAGE 1: INITIALIZATION**
  - Parameter processing.
  - Determine number of nodes to deploy.
- **STAGE 2: DEPLOY**
  - Deploy `n` instances for the manager cluster.
  - Deploy `n` instances for the simulated agents.
- **STAGE 3: PROVISION**
  - Provision managers: Install required deps, install wazuh ...
  - Provision agents: Install required deps, clone QA-repository ...
- **STAGE 4: CONFIGURATION**
  - Cluster configuration.
  - Additional configuration required.
- **STAGE 5: TESTING AND MONITORING**
  - Launch cluster monitor tool (To be developed).
  - Launch simulated agents and events generation.
- **STAGE 6: OBTAINING RESULTS**
  - CSV files collection.
  - Graph generation.
  - Publication of results (Jenkins artifacts). 
  - Storage in AWS-S3.
- **STAGE 7: OBTAINING RESULTS**
  - Instances destruction.
  - Environment clean up.

**Design and implementation requirements**

- A validation of the pipeline input parameters must be performed (unnecessary deployments must be avoided due to the large number of instances and costs).
- The deployment of all instances has to be performed in parallel 
- The provisioning of agent and manager has to be done in parallel
- The generation of graphs has to be done after grouping all CSVs in a separate fargate task.
- The data must be published in an orderly and structured manner in a zip file.
- Make sure that all machines have been destroyed after the pipeline has been completed.

**Comment by jmv74211** [comment]
# Estimated tasks

- [ ] Design and estimation of tasks
- [ ] Pipeline development:
    - [ ] STAGE 1: INITIALIZATION
        - [ ] Parameter processing.
        - [ ] Determine number of nodes to deploy.
    - [ ] STAGE 2: DEPLOY
        - [ ] Deploy `n` instances for the manager cluster.
        - [ ] Deploy `n` instances for the simulated agents.
    - [ ] STAGE 3: PROVISION
        - [ ] Provision managers: Install required deps, install wazuh ...
        - [ ] Provision agents: Install required deps, clone QA-repository ...
    - [ ] STAGE 4: CONFIGURATION
        - [ ] Cluster configuration.
        - [ ] Additional configuration required.
    - [ ] STAGE 5: TESTING AND MONITORING
        - [ ] Launch cluster monitor tool.
        - [ ] Launch simulated agents and events generation.
    - [ ] STAGE 6: OBTAINING RESULTS
        - [ ] CSV files collection.
        - [ ] Graph generation.
        - [ ] Publication of results (Jenkins artifacts). 
        - [ ] Storage in AWS-S3.
    - [ ] STAGE 7: OBTAINING RESULTS
        - [ ] Instances destruction.
        - [ ] Environment clean up.
- [ ] Pipeline testing and debugging.

**Comment by jmv74211** [comment]
In this first iteration, we will develop the pipeline by testing with a single manager, instead of a cluster that will be tested in later iterations.

I will try to leave the pipeline as adapted as possible for these future changes.

**Comment by jmv74211** [comment]
The objective of all this development is to obtain metrics and observe the behavior of a wazuh environment under given conditions.

In this sprint, it is being tested for a single manager. In the next sprint, it will be scaled to a wazuh-cluster.

The following PR adds everything proposed in this issue.

As a final result, we have obtained a pipeline that allows us to create an environment in which we can contemplate several scenarios:

- Simulate an `x` number of agents connected to a manager that only send keep-alives (agent mode).

- Simulate an `x` amount of EPS that are being sent continuously to the manager. These events can be of different types and assigned to different queues (EPS mode).

After the deployment of this environment, wazuh-manager resources and statistics are monitored for subsequent graphing and analysis.

At the end of the pipeline, we will obtain a .tgz file containing the following:

- **data**: Directory containing all the CSVs of the monitored data, grouped by statistics and metrics.
- **logs**: Directory containing the ossec.log of wazuh-manager
- **plots**: Directory containing all the SVG images obtained by plotting the CSV data files.

All parameters are configurable using the Jenkins UI. 

The pipeline is available at the following link https://devel.ci.wazuh.info/job/Test_cluster_performance/build?delay=0sec (not in production yet as it will be further modified in the next sprint).
