### ISSUE TITLE
Logcollector IT: Test deleted file doesn't appear in wazuh-logcollector.state

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1419]
#### Issue information
| Epic 	| target-branch 	| Wazuh version 	|
|-	|-	|-	|
| NA	| master 	| 4.2 or higher 	|

## Issue definition
We need to test that when a monitored file is deleted, it won't appear in `global` or `interval` modules of `wazuh-logcollector.state` according to https://github.com/wazuh/wazuh/pull/8797

### Operation
- [ ] Check that the deleted file does not appear in `global` section in `wazuh-logcollector.state`.
- [ ] Check that the deleted file does not appear in `interval` section in `wazuh-logcollector.state`.

### Test plan
1. Monitorice an empty file with logcollector.
2. Check that the file appears in `wazuh-logcollector.state`:

![image](https://user-images.githubusercontent.com/15269938/117268655-d098e180-ae57-11eb-9790-15b8069a1524.png)

3. Delete the monitored file.
4. Check that file does not appear in `wazuh-logcollector.state`.

**Comment by Rebits** [comment]
### Update 09/06/2021

This issue is been developed in `1419-deleted-file-logcollector-state_vr` branch. Some new checks have been added to this issue:

- Check local internal option `logcollector.state_interval` works correctly.
- Test  local internal option `logcollector.open_attempts` works correctly.

**Comment by spothound** [comment]
Closed by https://app.zenhub.com/workspace/o/wazuh/wazuh-qa/issues/1439
