### ISSUE TITLE
Fix 'test_general_settings/test_general_settings_enabled' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1556]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_general_settings/test_general_settings_enabled
| Consistent | no
| Test Execution | 1/3 executions failed
| Cases Fails | 4
| Summary | It should to do research with more details because in the logs doesn't show any details.

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_general_settings/test_general_settings_enabled` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by pereyra-m** [comment]
# 12/07

All the tests in the `test_general_settings` run successfully without any error locally (Ubuntu 20.04 and CentOS 8). The tests were run many times, even with different hardware configurations (4-2 cores, 2048-1024 Mb)

Also, in Jenkins, any error was found after four attempts (package **wazuh-manager-4.2.0-1.1493.x86_64.rpm**, branch **1516-4.2.0-full-green**):
- https://ci.wazuh.info/job/Test_integration/8137
- https://ci.wazuh.info/job/Test_integration/8138
- https://ci.wazuh.info/job/Test_integration/8139
- https://ci.wazuh.info/job/Test_integration/8140

Nevertheless, it is known that these tests are not completely reliable, so the root cause was investigated.
The `FileMonitor` component in the QA framework seems the most probable reason, because the tests are simple and just look for a specific line in the log.

Some manual tests were carried out to identify the cause of the slow file read.

**Comment by mdengra** [comment]
### 2021-07-13
Test results (full green):
  - [test_general_settings_enabled_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6809708/test_general_settings_enabled_local_r1.log)
  - [test_general_settings_enabled_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6809709/test_general_settings_enabled_local_r2.log)
  - [test_general_settings_enabled_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6809710/test_general_settings_enabled_local_r3.log)

**Comment by damarisg** [comment]
This issue is closed, after executes for a lot of times and see that works.
We couldn't reproduce the error. 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [test_general_settings_enabled_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6809708/test_general_settings_enabled_local_r1.log)| 2021-07-13| Miguel| :green_circle:
|[test_general_settings_enabled_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6809709/test_general_settings_enabled_local_r2.log) | 2021-07-13| Miguel| :green_circle:
| [test_general_settings_enabled_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6809710/test_general_settings_enabled_local_r3.log) | 2021-07-13| Miguel| :green_circle:
| [Results1_EnableSetting.log](https://github.com/wazuh/wazuh-qa/files/6810544/Results1_EnableSetting.log) | 2021-07-13| Seyla | :green_circle:
| [Results2_EnableSetting.log](https://github.com/wazuh/wazuh-qa/files/6810546/Results2_EnableSetting.log) | 2021-07-13| Seyla | :green_circle:
 | [Results3_EnableSetting.log](https://github.com/wazuh/wazuh-qa/files/6810644/Results3_EnableSetting.log) | 2021-07-13| Seyla | :green_circle:
