### ISSUE TITLE
 Fix 'test_general_settings/test_general_settings_run_on_start' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1558]
### Issue information

| Related issue | PR Created |
|--|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|https://github.com/wazuh/wazuh-qa/pull/1603|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_general_settings/test_general_settings_run_on_start
| Consistent | no
| Test Execution | 1/3 executions failed
| Cases Fails | 2
| Summary | It should to do research with more details because in the logs doesn't show any details.

In order to finish this issue the following tasks should be fulfilled:
- [x] Research of fails.
- [x] Apply Fix 
- [x] Full Green/ Full Yellow  in `test_general_settings/test_general_settings_run_on_start` for 3 times. 
- [x] Merge to `1531-full-yellow-vuln-det`

**Comment by mdengra** [comment]
### 2021-07-13
Test results :red_circle::
  - [test_general_settings_run_on_start_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6809750/test_general_settings_run_on_start_local_r1.log)
  - [test_general_settings_run_on_start_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6809751/test_general_settings_run_on_start_local_r2.log)
  - [test_general_settings_run_on_start_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6809752/test_general_settings_run_on_start_local_r3.log)

**Comment by damarisg** [comment]
This issue requires more research because when we execute it, we keep getting fails. 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_run_on_start_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6809750/test_general_settings_run_on_start_local_r1.log) | 2021-07-13| Miguel| 🔴
|[test_general_settings_run_on_start_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6809751/test_general_settings_run_on_start_local_r2.log) | 2021-07-13| Miguel| 🔴
| [test_general_settings_run_on_start_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6809752/test_general_settings_run_on_start_local_r3.log) | 2021-07-13| Miguel| 🔴
|[Results1_RunOnStart.log](https://github.com/wazuh/wazuh-qa/files/6810708/Results1_RunOnStart.log) | 2021-07-13| Seyla | 🔴
| [Results2_RunOnStart.log](https://github.com/wazuh/wazuh-qa/files/6810709/Results2_RunOnStart.log) | 2021-07-13| Seyla | 🔴
|[Results3_RunOnStart.log](https://github.com/wazuh/wazuh-qa/files/6810710/Results3_RunOnStart.log) | 2021-07-13| Seyla | 🔴

**Comment by pereyra-m** [comment]
This test was covered in this [comment](https://github.com/wazuh/wazuh-qa/issues/1556#issuecomment-878794672).
All the local tests were green:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [centos1.log](https://github.com/wazuh/wazuh-qa/files/6811729/centos.log) | 2021-07-12| Matias | :green_circle:
| [centos2.log](https://github.com/wazuh/wazuh-qa/files/6811730/centos2.1.log) | 2021-07-12| Matias | :green_circle:
 |[centos3.log](https://github.com/wazuh/wazuh-qa/files/6811732/centos3.1.log) | 2021-07-12| Matias | :green_circle:

**Comment by pereyra-m** [comment]
It was found that the file `test_general_settings/data/feeds/custom_nvd_feed.json` may not be properly formatted. 
This tests fails because the `Vulnerability scan finished` log line isn't found, the scan is aborted instead

```
ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
```

But if we replace that feed with the one located in `test_vulnerability_detector/test_scan_results/data/custom_nvd_feed.json`, the NVD vulnerabilities are inserted and the scan ends as expected.

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [test_general_settings_run_on_start_modules_off_new_nvd_1.log](https://github.com/wazuh/wazuh-qa/files/6816639/test_general_settings_run_on_start_modules_off_new_nvd_1.log) | 2021-07-14| Matias | :green_circle:
| [test_general_settings_run_on_start_modules_off_new_nvd_2.log](https://github.com/wazuh/wazuh-qa/files/6816637/test_general_settings_run_on_start_modules_off_new_nvd_2.log) | 2021-07-14| Matias | :green_circle:
 |[test_general_settings_run_on_start_modules_off_new_nvd_3.log](https://github.com/wazuh/wazuh-qa/files/6816636/test_general_settings_run_on_start_modules_off_new_nvd_3.log) | 2021-07-14| Matias | :green_circle:

This also explains why the test runs successfully together with the whole **test_general_settings** folder, the NVD vulnerabilities are inserted in a previous test.

**Comment by damarisg** [comment]
Execution Results with the changes applied on `1531-full-yellow-vuln-det` 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [ResultsRunOnStart1.log](https://github.com/wazuh/wazuh-qa/files/6832800/ResultsRunOnStart1.log)| 2021-07-16 | Seyla| 🟢
|[ResultsRunOnStart2.log](https://github.com/wazuh/wazuh-qa/files/6832801/ResultsRunOnStart2.log)| 2021-07-16 | Seyla| 🟢
| [ResultsRunOnStart3.log](https://github.com/wazuh/wazuh-qa/files/6832802/ResultsRunOnStart3.log)| 2021-07-16 | Seyla| :yellow_circle: 


| Reference | Status | 
|--|--|
| 🟢 | Pass without warnings|
| 🟡 | Pass with Warnings |

Merged to `1531-full-yellow-vuln-det`
