### ISSUE TITLE
Fix 'test_providers/test_providers_multiple_providers' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1560]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Vulnerability Detector
Support Team:  "binary beasts"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_providers/test_providers_multiple_providers
| Consistent | no
| Test Execution | 1/3 executions failed
| Cases Fails | 15
| Summary | - It should to do research with more details because in the logs doesn't show any details.
|| - Also, check it there are a problem when is executed for 3 time on Vagrant.

In order to finish this issue the following tasks should be fulfilled:
- [x] Research of fails.
- [x] Apply Fix 
- [x] Full Green/ Full Yellow  in `test_providers/test_providers_multiple_providers` for 3 times. 
- [x] Merge to `1531-full-yellow-vuln-det`

**Comment by pereyra-m** [comment]
Results for `test_providers/test_providers_multiple_providers`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[centos_providers_multiple_providers_1.log](https://github.com/wazuh/wazuh-qa/files/6812030/centos_providers_multiple_providers_1.log)| 2021-07-13| Matias | :red_circle:
| [centos_providers_multiple_providers_2.log](https://github.com/wazuh/wazuh-qa/files/6812029/centos_providers_multiple_providers_2.log)| 2021-07-13| Matias | :red_circle:
| [centos_providers_multiple_providers_3.log](https://github.com/wazuh/wazuh-qa/files/6812028/centos_providers_multiple_providers_3.log)| 2021-07-13| Matias | :red_circle:


The same package and QA branch were tested on Jenkins, and they all passed, so the issue may be local
- https://ci.wazuh.info/job/Test_integration/8141/
- https://ci.wazuh.info/job/Test_integration/8142/
- https://ci.wazuh.info/job/Test_integration/8143/
- https://ci.wazuh.info/job/Test_integration/8144/

Considering that these tests depend on the internet connection speed to generate the `Downloading feed ...` log, the timeout was increased in the local tests. It is reasonable to think that the hosts in the cloud have a faster connection. 

Here we have the results of the tests after the timeout increase `(VULN_DETECTOR_GLOBAL_TIMEOUT + 100):`

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[centos_providers_multiple_providers_timeout_1.log](https://github.com/wazuh/wazuh-qa/files/6812168/centos_providers_multiple_providers_timeout_1.log)| 2021-07-13| Matias | :green_circle:
| [centos_providers_multiple_providers_timeout_2.log](https://github.com/wazuh/wazuh-qa/files/6812167/centos_providers_multiple_providers_timeout_2.log)| 2021-07-13| Matias | :green_circle:
|[centos_providers_multiple_providers_timeout_3.log](https://github.com/wazuh/wazuh-qa/files/6812166/centos_providers_multiple_providers_timeout_3.log) | 2021-07-13| Matias | :green_circle:

This doesn't seem to be a `FileMonitor` issue, because the log the test needs appears after the test ends.

**Comment by damarisg** [comment]
Execution Results with the changes applied after merging to `1531-full-yellow-vuln-det` 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
| [ResultsMultipleProvider1.log](https://github.com/wazuh/wazuh-qa/files/6832998/ResultsMultipleProvider1.log)| 2021-07-16 | Seyla| :yellow_circle: 
|[ResultsMultipleProvider2.log](https://github.com/wazuh/wazuh-qa/files/6833010/ResultsMultipleProvider2.log)| 2021-07-16 | Seyla| :yellow_circle: 
|[ResultsMultipleProvider3.log](https://github.com/wazuh/wazuh-qa/files/6833011/ResultsMultipleProvider3.log)| 2021-07-16 | Seyla| 🟢


| Reference | Status | 
|--|--|
| 🟢 | Pass without warnings|
| 🟡 | Pass with Warnings |

**Comment by mdengra** [comment]
I reopen this issue to fix a `DeprecationWarning` that appears when running this test:
```
test_vulnerability_detector/test_providers/test_providers_multiple_providers.py:73
  /root/wazuh-qa/tests/integration/test_vulnerability_detector/test_providers/test_providers_multiple_providers.py:73: DeprecationWarning: invalid escape sequence \<.
    """
```
