### ISSUE TITLE
Fix 'test_remoted/test_active_response/test_active_response_send_ar' tests in 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1571]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_active_response/test_active_response_send_ar
| Consistent | yes
| Test Execution | 3/3 executions failed
| Cases Fails | 6
| Summary | On `test_active_response_ar_sending` when it called to `wait_status_active`. It requires investigating if it is a timeout error or if the agent is taking longer than it should.
|Error message|"Agent is not active yet: pending"

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_active_response/test_active_response_send_ar` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-23

Used Wazuh-QA branch: `1516-4.2.0-full-green`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_active_response_send_ar_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6867581/test_active_response_send_ar_local_r1.log)| 2021-07-23 | Miguel | :yellow_circle: 
|[test_active_response_send_ar_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6867583/test_active_response_send_ar_local_r2.log)| 2021-07-23 | Miguel | :red_circle: 
|[test_active_response_send_ar_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6867586/test_active_response_send_ar_local_r3.log)| 2021-07-23 | Miguel | :yellow_circle: 
|[test_active_response_send_ar_local_r4.log](https://github.com/wazuh/wazuh-qa/files/6867587/test_active_response_send_ar_local_r4.log)| 2021-07-23 | Miguel | :red_circle: 

I have run the test four times because I wanted to check if when the failure occurs it is in the same use case. In this scenario they have been different use cases:
```
r2:
FAILED test_remoted/test_active_response/test_active_response_send_ar.py::test_active_response_ar_sending[TCP_1514]
r4:
FAILED test_remoted/test_active_response/test_active_response_send_ar.py::test_active_response_ar_sending[TCP,UDP_1514]
```

**Comment by mdengra** [comment]
As far as I have been able to check, the `agent_simulator` class verifies if the agent is active making queries to the `global` database using the `wazuh-db` socket until obtaining the `active` status. To reach this state, it must previously pass through the states: `never_connected` and `pending`. This last state is where the agent is when the maximum number of checks is reached.

For the agent to go from `pending` to `active` state there must be a message exchange between the agent and the `remoted` service of the manager, so it seems that sometimes, this communication is interrupted or is too slow. 

As a solution, I have added an additional timeout to see if the cause is due to some manager services are still initializing when the communication starts. After the testing, the error has no longer happened.

**Comment by mdengra** [comment]
### 2021-07-27

Used Wazuh-QA branch: `1530-full-yellow-remoted`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_active_response_send_ar_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6885167/test_active_response_send_ar_local_r1.log)| 2021-07-27 | Miguel | :red_circle: 
|[test_active_response_send_ar_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6885169/test_active_response_send_ar_local_r2.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_active_response_send_ar_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6885174/test_active_response_send_ar_local_r3.log)| 2021-07-27 | Miguel | :yellow_circle: 

After applying the changes, the test still fails, this error is random, so after several successful validations, the error occurred again. Therefore I continue to investigate the cause of the failure.

**Comment by mdengra** [comment]
### 2021-07-28

In addition to the validation of PR: https://github.com/wazuh/wazuh-qa/pull/1662, I have performed ten rounds of the test to avoid possible false negatives since the test fails on a few occasions. The same changes applied in the PR indicated above have been used.

Used Wazuh-QA branch: `1530-full-yellow-remoted`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_active_response_send_ar_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6891259/test_active_response_send_ar_local_r1.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6891261/test_active_response_send_ar_local_r2.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6891262/test_active_response_send_ar_local_r3.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r4.log](https://github.com/wazuh/wazuh-qa/files/6891264/test_active_response_send_ar_local_r4.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r5.log](https://github.com/wazuh/wazuh-qa/files/6891265/test_active_response_send_ar_local_r5.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r6.log](https://github.com/wazuh/wazuh-qa/files/6891267/test_active_response_send_ar_local_r6.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r7.log](https://github.com/wazuh/wazuh-qa/files/6891268/test_active_response_send_ar_local_r7.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r8.log](https://github.com/wazuh/wazuh-qa/files/6891271/test_active_response_send_ar_local_r8.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r9.log](https://github.com/wazuh/wazuh-qa/files/6891273/test_active_response_send_ar_local_r9.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r10.log](https://github.com/wazuh/wazuh-qa/files/6891276/test_active_response_send_ar_local_r10.log)| 2021-07-28 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
## Update 28-07-21 

After merging #1662 the results are:

Test Executions | Date | By | Status
-- | -- | -- | --
[ResultsActiveResponseSendAr.log](https://github.com/wazuh/wazuh-qa/files/6892927/ResultsActiveResponseSendAr.log) | 2021-07-28 | Seyla| 🟡
[ResultsActiveResponseSendAr2.log](https://github.com/wazuh/wazuh-qa/files/6892928/ResultsActiveResponseSendAr2.log) | 2021-07-28 | Seyla| 🔴 
[ResultsActiveResponseSendAr3.log](https://github.com/wazuh/wazuh-qa/files/6892929/ResultsActiveResponseSendAr3.log)| 2021-07-28 | Seyla| 🟡


Does @mdengra think that it could need more time?
![imagen](https://user-images.githubusercontent.com/3978434/127320574-987802ea-0944-4c12-82df-9627d5cf07f8.png)

**Comment by mdengra** [comment]
### 2021-07-28

#### Collecting detailed information on the failure
I have run the test several times to try to reproduce the error, in six runnings it has occurred only once.
Following the indications of @DProvinciani, to collect the maximum information I have used the internal option `wazuh_db.debug=2` and the PyTest `-vvx` parameters.

Used Wazuh-QA branch: `1530-full-yellow-remoted`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Log | Date  | By  | Status | 
|--|--|--|--|--|
|[test_active_response_send_ar_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6893918/test_active_response_send_ar_local_r1.log)|[ossec_r1.log](https://github.com/wazuh/wazuh-qa/files/6893921/ossec_r1.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6893924/test_active_response_send_ar_local_r2.log)|[ossec_r2.log](https://github.com/wazuh/wazuh-qa/files/6893926/ossec_r2.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6893929/test_active_response_send_ar_local_r3.log)|[ossec_r3.log](https://github.com/wazuh/wazuh-qa/files/6893930/ossec_r3.log)| 2021-07-28 | Miguel | :red_circle:  
|[test_active_response_send_ar_local_r4.log](https://github.com/wazuh/wazuh-qa/files/6893933/test_active_response_send_ar_local_r4.log)|[ossec_r4.log](https://github.com/wazuh/wazuh-qa/files/6893934/ossec_r4.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r5.log](https://github.com/wazuh/wazuh-qa/files/6893936/test_active_response_send_ar_local_r5.log)|[ossec_r5.log](https://github.com/wazuh/wazuh-qa/files/6893937/ossec_r5.log)| 2021-07-28 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r6.log](https://github.com/wazuh/wazuh-qa/files/6893938/test_active_response_send_ar_local_r6.log)|[ossec_r6.log](https://github.com/wazuh/wazuh-qa/files/6893939/ossec_r6.log)| 2021-07-28 | Miguel | :yellow_circle:

**Comment by mdengra** [comment]
### 2021-07-29

After updating the framework with the latest changes, after ten test runs, I have not been able to replicate the error.

#### Collecting detailed information on the failure
Following the indications of @DProvinciani, to collect the maximum information I have used the internal option `wazuh_db.debug=2` and the PyTest `-vvx` parameters.

Used Wazuh-QA branch: `1530-full-yellow-remoted`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Log | Date  | By  | Status | 
|--|--|--|--|--|
|[test_active_response_send_ar_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6899274/test_active_response_send_ar_local_r1.log)|[ossec_r1.log](https://github.com/wazuh/wazuh-qa/files/6899275/ossec_r1.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6899276/test_active_response_send_ar_local_r2.log)|[ossec_r2.log](https://github.com/wazuh/wazuh-qa/files/6899278/ossec_r2.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6899280/test_active_response_send_ar_local_r3.log)|[ossec_r3.log](https://github.com/wazuh/wazuh-qa/files/6899283/ossec_r3.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r4.log](https://github.com/wazuh/wazuh-qa/files/6899285/test_active_response_send_ar_local_r4.log)|[ossec_r4.log](https://github.com/wazuh/wazuh-qa/files/6899288/ossec_r4.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r5.log](https://github.com/wazuh/wazuh-qa/files/6899293/test_active_response_send_ar_local_r5.log)|[ossec_r5.log](https://github.com/wazuh/wazuh-qa/files/6899295/ossec_r5.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r6.log](https://github.com/wazuh/wazuh-qa/files/6899296/test_active_response_send_ar_local_r6.log)|[ossec_r6.log](https://github.com/wazuh/wazuh-qa/files/6899299/ossec_r6.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r7.log](https://github.com/wazuh/wazuh-qa/files/6899303/test_active_response_send_ar_local_r7.log)|[ossec_r7.log](https://github.com/wazuh/wazuh-qa/files/6899306/ossec_r7.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r8.log](https://github.com/wazuh/wazuh-qa/files/6899307/test_active_response_send_ar_local_r8.log)|[ossec_r8.log](https://github.com/wazuh/wazuh-qa/files/6899310/ossec_r8.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r9.log](https://github.com/wazuh/wazuh-qa/files/6899312/test_active_response_send_ar_local_r9.log)|[ossec_r9.log](https://github.com/wazuh/wazuh-qa/files/6899313/ossec_r9.log)| 2021-07-29 | Miguel | :yellow_circle:  
|[test_active_response_send_ar_local_r10.log](https://github.com/wazuh/wazuh-qa/files/6899317/test_active_response_send_ar_local_r10.log)|[ossec_r10.log](https://github.com/wazuh/wazuh-qa/files/6899319/ossec_r10.log)| 2021-07-29 | Miguel | :yellow_circle:

**Comment by damarisg** [comment]
Test Results after to merge:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowActiveAr.log](https://github.com/wazuh/wazuh-qa/files/6907740/YellowActiveAr.log)| 2021-07-30| Seyla|  🟡  
|[YellowActiveAr2.log](https://github.com/wazuh/wazuh-qa/files/6907741/YellowActiveAr2.log)| 2021-07-30 | Seyla|🟡
|[YellowActiveAr3.log](https://github.com/wazuh/wazuh-qa/files/6907742/YellowActiveAr3.log)| 2021-07-30| Seyla| 🟡


It is closed by #1674

**Comment by damarisg** [comment]
This issue work random, and it affected by https://github.com/wazuh/wazuh-qa/issues/1698. After to fix this problems we can unblock this issue.

**Comment by damarisg** [comment]
This issue is closed because the test was disabled by https://github.com/wazuh/wazuh-qa/issues/1698
