### ISSUE TITLE
Fix 'test_remoted/test_agent_communication/test_request_agent_info' tests in 4.2 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1579]
### Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1530|

When it comes to starting with the test fix, there is some information that can help you:
```
Module: Remoted
Support Team: "Core" 
Channel: "devel-core"
Target: Manager   
OS: Linux
```
I add some information obtained while researched the logs that failed.

## Case:

|  Type | Description  |
|--|--|
|Test Path | test_remoted/test_agent_communication/test_request_agent_info
|Consistent | no
|Test Execution | 2/3 executions failed
|Cases Fails | 2
|Summary | On `test_request` when it called to `send_request`. It should to do research with more details because in the logs doesn't show any details.

In order to finish this issue the following tasks should be fulfilled:
- [ ] Research of fails.
- [ ] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_remoted/test_agent_communication/test_request_agent_info` for 3 times. 
- [ ] Documentation of any important change done for these tests or the used tools.

**Comment by mdengra** [comment]
### 2021-07-20

I was unable to reproduce the described error in my testing environment.
Used Wazuh-QA branch: `1516-4.2.0-full-green`
Test results with the modules `sca`, `syscollector` and `rootcheck` modules disabled in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_request_agent_info_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6848198/test_request_agent_info_local_r1.log)| 2021-07-20 | Miguel | :red_circle: 
|[test_request_agent_info_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6848199/test_request_agent_info_local_r2.log)| 2021-07-20 | Miguel | :red_circle: 
|[test_request_agent_info_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6848200/test_request_agent_info_local_r3.log)| 2021-07-20 | Miguel | :red_circle: 

The test still fails with the previously mentioned modules disabled, so in principle, we can discard that the failures are due to FileMonitor.

It is worth noting that the test fails on the same use cases during all runs:
```
FAILED test_remoted/test_agent_communication/test_request_agent_info.py::test_request[udp,tcp-disconnected]
FAILED test_remoted/test_agent_communication/test_request_agent_info.py::test_request[tcp-disconnected]
FAILED test_remoted/test_agent_communication/test_request_agent_info.py::test_request[udp-disconnected]
```

**Comment by mdengra** [comment]
### 2021-07-20

After some research, it seems that in the use cases where the errors occur the `remoted` socket is not ready when the request is sent, so no response is received and therefore the test fails. The solution for this problem may be to add a small sleep for those use cases.

I also think that the use cases can be reduced from the current 9 to 3, as these are repeating during the test:
```
parameters = [
    {'PROTOCOL': 'udp,tcp'},
    {'PROTOCOL': 'tcp'},
    {'PROTOCOL': 'udp'},
]
test_case = {
    'disconnected': ('agent getconfig disconnected',
                     'Cannot send request'),
    'get_config': ('agent getconfig client',
                   '{"client":{"config-profile":"centos8","notify_time":10,"time-reconnect":60}}'),
    'get_state': ('logcollector getstate',
                  '{"error":0,"data":{"global":{"start":"2021-02-26, 06:41:26","end":"2021-02-26 08:49:19"}}}')
}
```
In the code shown, each parameter is combined with a use case, but the first parameter already includes the other two, testing both protocols inside a for loop within the main test code. Therefore setting the parameters as:
```
parameters = [
    {'PROTOCOL': 'udp,tcp'},
]
```
The three `test_case` are combined with the two communication protocols.

**Comment by damarisg** [comment]
After merging #1624, it works successfully.
| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowResultsRequestAgentInfo.log](https://github.com/wazuh/wazuh-qa/files/6878003/YellowResultsRequestAgentInfo.log)| 2021-07-26 | Seyla| 🟢|
|[YellowResultsRequestAgentInfo2.log](https://github.com/wazuh/wazuh-qa/files/6878004/YellowResultsRequestAgentInfo2.log)| 2021-07-26 | Seyla| 🟢 |
|[YellowResultsRequestAgentInfo3.log](https://github.com/wazuh/wazuh-qa/files/6878005/YellowResultsRequestAgentInfo3.log)| 2021-07-26 | Seyla| 🟢 |
