### ISSUE TITLE
QA documentation schema investigation

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#1598]
As part of the epic [Overall improvements for integration tests documentation](https://github.com/wazuh/wazuh-qa/issues/1536) we need to design a mechanism to create, sustain and display each QA test with the following requirements:
- The documentation of the test must be self-contained on each **.py** file.
- Additional information could be contained in a README.md file, to bring a general brief and/or tags inherited by each test.
- The documentation must contain min version, max version, OS, modules, daemons, tiers, tags.
- The documentation source must be easily sustained by the developer of the tests.
- The documentation output must be locally displayed by the developer.
- The documentation output must allow the user to easily navigate it.

**Comment by MiguelazoDS** [comment]
### Description
---

As the long-term proposal to have a more completed and readable documentation about the QA testing that validates our product, this first research was done to understand the underneath requirements and the possible solutions that could be applied.

It was decided that the first iteration of this documentation improvement is aimed to find a proper way to obtain (ideally from the python test scripts) multiple metadata information that could be useful to feed a search engine with a standard format to create dynamic content by filters and fields.

As this metadata along with other information, for example, a brief description of the test module would belong to the module docstring, the approach was to consider tools that generate documentation from code.
To extract this information from every test module the options taking into account were **Doxygen** and **Sphinx**.

Both are widely used and well-known solutions, the advantage is that they set a standard to write comments that then are converted into a documentation format.
In case the syntax is not respected we easily know that we are not formatting the commentaries properly, while on a custom script we should define and create a parser that validates a made-up format to write this metadata.

Also, we can set what files and directories of a tree structure we want to include in the documentation, since to create detailed and complete documentation we also need to include document files as **markdown** or **rst** to complement what we put into the .py scripts.
The drawback we see is that these tools, as far as we read, can not easily skip a portion of the code that we don't want to include. Using a custom script would be a better approach if we don't want strictly information about the functions in the module with the disadvantage mentioned before.

The right tool can provide possibly better what is covered or not by the documentation, which would be a challenging work for a custom script.

The suggestion to use **search-ui** https://github.com/elastic/search-ui seems to be a powerful solution to develop a custom search engine capable to show what we need.
This module uses as input information a JSON format file, which is a standard easy to understand and applied in multiple cases.

One of the previously described tools, sphinx, has a builder that can return a **JSON** format after processing a document as this section of its documentation explain.

https://www.sphinx-doc.org/en/master/usage/builders/index.html

"This builder produces a directory with JSON files containing mostly HTML fragments and TOC information, for use of a web application (or custom postprocessing tool) that doesn’t use the standard HTML templates"

But again is needed to perform a test to check if this tool full fill our needs. All the python scripts along with the extra documentation files should be converted into JSON to be part of the input that **search-ui** receives.

**Comment by palaciosjeremias** [comment]
The below diagram represents how the documentation content will be spread in different test files, parsed, and joined into JSON files thru a set of scripts.
![QA documentation schema](https://user-images.githubusercontent.com/11434230/125545347-ce317c13-1935-4885-a748-d425d80ac1d1.png)

**Comment by palaciosjeremias** [comment]
The below diagram represents how the documentation content will be spread in different test files, parsed, and joined into JSON files thru a set of scripts.
![QA documentation schema](https://user-images.githubusercontent.com/11434230/125545347-ce317c13-1935-4885-a748-d425d80ac1d1.png)
