### ISSUE TITLE
Migrate documentation content to the new self-contained documentation blocks in the source code.

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#1599]
### Description

As part of the epic Overall improvements for integration tests documentation we need to add documentation blocks into the source code of the test files.
For doing this, the documentation block should follow the schema defined in wazuh/wazuh-qa#16261694.
And the description of a group of tests should be added as a README file at the tests group level as defined in wazuh/wazuh-qa#1640.
This issue aims to create example documented source codes, so, 15 modules from Vulnerability Detector tests should be covered.

**Comment by palaciosjeremias** [comment]
The following comment format was analyzed to create the self-contained documentation:
- Parse the comment without a specific format
  - Search for keywords as "Brief:", "Metadata:", etc to parse the desired fields.
    - Pro: Easy to write.
    - Cons: Easy to confuse the parser.
  - Search for tags as #Brief, #Metadata, etc to parse the desired fields.
    - Pro: Easy to write.
    - Cons: Easy to confuse the parser.
- Parse the comments with YAML format:
  - Write the comment block completely in YAML format
    - Pro: Easy to parse. Secure to write without confusing the parser.
    - Con: Difficult to write. Have to adapt each comment block. Every field in the comment, even the non-documentable (as params), must have YAML format
  - Write a regular comment block  with a #DocGen section that will contain the YAML format
    - Pro Easy to Write. Difficult to confuse the parser.
    - Con: Must define a way to not repeat information with the Brief.

**Comment by MiguelazoDS** [comment]
As an attempt to add this needed new information, some possibilities were taking into account with the best effort to not reinvent the wheel, with that in mind we looked for a standard to write docstrings that:

- Respect a well-known standard.
- To not force a developer to follow a made-up format that is not going to take a place beyond this development. 

Having said that, the approach was to consider the pep-287 standard for writing docstrings in a ReST format, but the alternative was quickly discarded as a solution for our problem since it is aimed to document code. In our case, we are trying to parse a description to create a high-level documentation without paying too much attention to the details of the code. 

And also since the standard followed so far is pep-8 which relies on pep-257 for writing docstring we thought that the best idea was not to modify that, besides it lets us create a custom description still following the rules.

**Comment by snaow** [comment]
The new schema (2.0) is in progress at issue: https://github.com/wazuh/wazuh-qa/issues/1694

Closing this issue in favor of new work on the new schema.
