### ISSUE TITLE
Develop an automatic test to detect new security flaws in the code

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1615]
Hi team,

In this PR we aim to automate the process of analyzing code for vulnerabilities in order to avoid uploading vulnerable code. This test should be run whenever Python related code is modified, such as the code in the API, Framework and Wodles folders.

## ToDo

- [x] Create a new unit test that analyzes the Python code and warns about possible bugs.
- [x] Investigate if it is possible to detect the code sections changed with respect to the same online branch and launch the tests on them.

Best regards,

Adrián Peña

**Comment by mcarmona99** [comment]
## Issue update

Having into account the investigation done in the issue: https://github.com/wazuh/wazuh/issues/7971, I will try to develop this automatic test using **`Bandit`**:



Useful Bandit parameters:

```
  -i, --confidence      report only issues of a given confidence level or
                        higher (-i for LOW, -ii for MEDIUM, -iii for HIGH)
```

Testing the framework:

`bandit -r framework/ -ii`

will show framework vulnerabilities with confidence **MEDIUM** and **HIGH**.

These are the issues we are looking for, as we will avoid issues shown by Bandit with lower confidence level. We must ignore vulnerabilities detected in tests as they are not related to the code itself.


The output of this command could be redirected to a temporal file and may be parsed. The problem is the output would be difficult to decode.

Output example for 

`bandit -r wodles/ -ii` :

<details>

<summary>output.txt</summary>

```
manuel:~/git/wazuh (master)$ bandit -r wodles/ -ii
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	running on Python 3.8.10
Run started:2021-07-23 14:55:46.659842

Test results:
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
   Severity: Low   Confidence: High
   Location: wodles/aws/tests/test_aws.py:63
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html
62	
63	        assert(metadata_version == ins.wazuh_version)
64	

--------------------------------------------------
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
   Severity: Low   Confidence: High
   Location: wodles/aws/tests/test_aws.py:85
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html
84	
85	        assert(metadata_version == ins.wazuh_version)
86	

--------------------------------------------------
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
   Severity: Low   Confidence: High
   Location: wodles/aws/tests/test_aws.py:136
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b101_assert_used.html
135	
136	        assert(data == 8)
137	
138	        # maintenance when retain_db_records is smaller than elements in DB
139	        ins.retain_db_records = 6

...

--------------------------------------------------
>> Issue: [B603:subprocess_without_shell_equals_true] subprocess call - check for execution of untrusted input.
   Severity: Low   Confidence: High
   Location: wodles/oscap/oscap.py:200
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html
199	
200	            ps_xsltproc = Popen([XSLT_BIN, TEMPLATE_OVAL, FIFO_PATH], stdin=None, stdout=PIPE, stderr=STDOUT)
201	            ps.wait()

--------------------------------------------------

Code scanned:
	Total lines of code: 3950
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 16.0
		Medium: 5.0
		High: 1.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 0.0
		Medium: 0.0
		High: 22.0
Files skipped (0):
```

</details>

I am investigating Bandit report formatters that could be useful for the output that will generate our test: https://bandit.readthedocs.io/en/latest/formatters/index.html

The format could be: **csv, custom, html, json, screen, text, xml, yaml**.

In our case, the most interesting ones may be `json` and `html`.

**Comment by mcarmona99** [comment]
## Issue update

Useful Bandit parameters:

```
  -i, --confidence      report only issues of a given confidence level or
                        higher (-i for LOW, -ii for MEDIUM, -iii for HIGH)
                        
  -r, --recursive       find and process files in subdirectories
  
  -f {csv,custom,html,json,screen,txt,xml,yaml}, --format {csv,custom,html,json,screen,txt,xml,yaml}
                        specify output format
                        
  -x EXCLUDED_PATHS, --exclude EXCLUDED_PATHS
                        comma-separated list of paths (glob patterns
                        supported) to exclude from scan (note that these are
                        in addition to the excluded paths provided in the
                        config file)
```



- Bandit can create html reports with the `-f` flag:

`bandit -r wodles/ -ii -f html
` 

Reports like the folllowing can be created, they will be useful for a future integration in our automation environment:

![image](https://user-images.githubusercontent.com/57481331/127013394-7a6853b5-c80a-48b1-b593-b5f01fd84ff2.png)



We will use `-x` to exclude tests. 

In the test that is going to be created in this issue, no `html` format will be done as we need a `json` output to assert errors.

The command that will be used in our test will be the following:

`bandit -r wodles|framework|api -ii -f json -x tests/,test/
`

That command will generate a JSON report whith the possible vulnerabilities detected by **Bandit**.

The test will pass if the detected vulnerabilities are 0. As investigated in the issue https://github.com/wazuh/wazuh/issues/7998, there are some vulnerabilities that could be ignored, as they are not real vulnerabilities.

Vulnerabilities will never be 0 because of this false positives. In order to ignore them, this test will compare all the vulnerabilities detected with a list of known vulnerabilities (false positives and vulnerabilities to fix). 

If there are new vulnerabilities, the test will fail and we will have to study whether the possible flaws are dangerous or not. In case they are false positives, we will add them to the known_flaws list (that will be a simple txt file).

When fixing a known vulnerability or flaw, we will remove its entry in the respective known_flaws list.

**Comment by mcarmona99** [comment]
## API - False positives explanations 

Total of false positives in `api/`: 2

### `wazuh-apid.py:`

Code:

```
    app.add_api('spec.yaml',
                arguments={'title': 'Wazuh API',
                           'protocol': 'https' if api_conf['https']['enabled'] else 'http',
                           'host': api_conf['host'],
                           'port': api_conf['port']
                           },
                strict_validation=True,
                validate_responses=False,
                pass_context_arg_name='request',
                options={"middlewares": [response_postprocessing, set_user_name, security_middleware, request_logging,
                                         set_secure_headers]})
```

Possible flaw: Possible hardcoded password: 'request'

This is a false positive. The pass_context_arg_name defines the neame of a request argument that will be added to the endpoints. It is not a password.

### ` configuration.py`

Code:

```
default_api_configuration = {
    "host": "0.0.0.0",
    "port": 55000,
    "use_only_authd": False,
    "drop_privileges": True,
    "experimental_features": False,
    "max_upload_size": 10485760,
    "intervals": {
        "request_timeout": 10
    },
    "https": {
        "enabled": True,
        "key": "api/configuration/ssl/server.key",
        "cert": "api/configuration/ssl/server.crt",
        "use_ca": False,
        "ca": "api/configuration/ssl/ca.crt",
        "ssl_protocol": "TLSv1.2",
        "ssl_ciphers": ""
    },
    "logs": {
        "level": "info",
        "path": "logs/api.log"
    },
    "cors": {
        "enabled": False,
        "source_route": "*",
        "expose_headers": "*",
        "allow_headers": "*",
        "allow_credentials": False,
    },
    "cache": {
        "enabled": True,
        "time": 0.750
    },
    "access": {
        "max_login_attempts": 50,
        "block_time": 300,
        "max_request_per_minute": 300
    },
    "remote_commands": {
        "localfile": {
            "enabled": True,
            "exceptions": []
        },
        "wodle_command": {
            "enabled": True,
            "exceptions": []
        }
    }
}
```

Possible flaw: Possible binding to all interfaces.

We are told that we are exposing the API from all network interfaces. This is due to the design of the API, by default, the API accepts all connections unless otherwise indicated in its configuration. This is because the API can be configured from the API itself.

Also a false positive.

**Comment by mcarmona99** [comment]
## Framework - False positives explanations


Total of false positives in `framework/`: 28

### Subprocess calls (11 flaws)

All the flaws are false positives because the subprocess module is used but we never set an external input as a parameter. In other words, all the invoked subprocesses have the parameters hardcoded. 

- framework/wazuh/core/cluster/cluster.py line 39
- framework/wazuh/core/common.py line 62
- framework/wazuh/core/configuration.py line 713
- framework/wazuh/core/utils.py line 112
- framework/scripts/wazuh-logtest.py line 421
- framework/wazuh/core/cluster/cluster.py line 39
- framework/scripts/wazuh-logtest.py line 14
- framework/wazuh/core/cluster/cluster.py line 14
- framework/wazuh/core/common.py line 7
- framework/wazuh/core/configuration.py line 9
- framework/wazuh/core/utils.py line 24

All of the flaws are due to the use of `subprocess`, but the last 5. These possible flaws was just telling to consider the possible security implications of importing subprocess.



### XML calls (2 flaws)

Issue text: Using tostring to parse untrusted XML data is known to be vulnerable to XML attacks. Replace tostring with the equivalent defusedxml package, or make sure defusedxml.defuse_stdlib() is called.

- framework/wazuh/core/configuration.py line 15

Issue text: Using ElementTree to parse untrusted XML data is known to be vulnerable to XML attacks. Replace ElementTree with the equivalent defusedxml package, or make sure defusedxml.defuse_stdlib() is called.

- framework/wazuh/core/utils.py line 25

As bandit indicates, in this case it is always convenient to use `defusedxml` because it does not reduce functionality and increases security.
These flaws can be avoided with the use of `defusedxml` (we have already used it in other situations, so we have the dep in the requirements.txt). 

- [ ] Open issue.


### Chmod setting a permissive mask (2 flaws)

Issue text: Chmod setting a permissive mask 0o770 on file (group_path).

- framework/wazuh/agent.py line 582.

Issue text: Chmod setting a permissive mask 0o750 on file (agent_backup_dir).

- framework/wazuh/core/agent.py line 611.

A MEDIUM warning is generated if a file is set to group executable and a HIGH warning is reported if a file is set world writable. In this case, both possible flaws are reported with severity MEDIUM so the file is set to group executable.

To complete...

### Use of insecure MD2, MD4, MD5, or SHA1 hash function (3 flaws)

- framework/wazuh/core/agent.py line 816
- framework/wazuh/core/agent.py line 818
- framework/wazuh/core/utils.py line 641

Create issue to investigate if it is possible to use SHA256 or a different secure cryptograpthic algorithm.
Algorithms which are not considered secure with alternatives: https://security.stackexchange.com/questions/78/what-cryptographic-algorithms-are-not-considered-secure

- [ ] Open issue.

### Possible binding to all interfaces (2 flaws)

This flaw told us that we are exposing something from all network interfaces.

- framework/wazuh/core/cluster/cluster.py line 64

The flaw is a false positive here as the IP 0.0.0.0 is just an IP included in a variable that work as a filter to indicate invalid elements:

```
reservated_ips = {'localhost', 'NODE_IP', '0.0.0.0', '127.0.1.1'}
...
invalid_elements = list(reservated_ips & set(config['nodes']))
```


- framework/wazuh/core/cluster/utils.py line 48-57

The flaw is also a false positive as Bandit is reporting this:

```
cluster_default_configuration = {
        'disabled': False,
        'node_type': 'master',
        'name': 'wazuh',
        'node_name': 'node01',
        'key': '',
        'port': 1516,
        'bind_addr': '0.0.0.0',
        'nodes': ['NODE_IP'],
        'hidden': 'no'
    }
```
    
as a possible binding from all interfaces. This is not a real flaw as this is part of the design of the cluster.

### Probable insecure usage of temp file/directory (2 flaws)

- framework/wazuh/core/configuration.py line 676
- framework/wazuh/core/utils.py line 1755

This is a hardcoded temporary directory. We could investigate if we could generate a temporary one in a safer way (the tmpfile library can create it by its own): https://docs.openstack.org/bandit/1.4.0/plugins/hardcoded_tmp_directory.html

[ ] Open issue.

### Possible SQL injection vector through string-based query construction (5 flaws)

- framework/wazuh/core/rootcheck.py line 98
- framework/wazuh/core/rootcheck.py line 104
- framework/wazuh/syscheck.py line 93
- framework/wazuh/syscheck.py line 95
- framework/wazuh/syscheck.py line 97

They are false positives because no SQL injection can be done as the variables inserted in the SQL sentences come from the controller and they are controlled at the spec level.

### Pseudo-random generadtors (1 flaw)

Issue text: Standard pseudo-random generators are not suitable for security/cryptographic purposes

- framework/wazuh/core/cluster/cluster.py line 306

This random number is used to set the name of the compressed data for the integrity synchronization process in cluster. This is a false positive as the temporary file is created using the node name, so we can guaranteee that the files will never be overwritten.

**Comment by mcarmona99** [comment]
## Wazuh modules - False positives explanations 


Total of possible flaws in wodles/: 10 + 1 to fix

### To fix (1 flaw)

The flaw:

Standard pseudo-random generators are not suitable for security/cryptographic purposes.

- wodles/oscap/oscap.py line 164

Has already been studied in #7998 and an issue was opened to fix it. The issue opened is https://github.com/wazuh/wazuh/issues/8347.

### Use of insecure MD2, MD4, MD5, or SHA1 hash function (3 flaws)

- wodles/azure/azure-logs.py line 246
- wodles/azure/azure-logs.py line 384
- wodles/azure/azure-logs.py line 530

This is not a problem since the data handled are not critical and are only used internally by the wodle, so there is no decoding possibility. Despite this, we could open an issue to investigate and use secure hash functions, similar to the same possible flaws found in framework.

- [ ] Open issue

### Subprocess calls (5 flaws)

The issue https://github.com/wazuh/wazuh/issues/8347 was opened to investigate and avoid these subprocess calls.

- wodles/oscap/oscap.py line 17
- wodles/oscap/oscap.py line 36
- wodles/oscap/oscap.py line 140
- wodles/oscap/oscap.py line 170
- wodles/oscap/oscap.py line 200

Diferent to the subprocess calls found in framework, now we can see that we make subprocess calls with command line arguments. Example:

`profiles = extract_profiles_from_file(arg_file)`

arg_file is created from argv and the function extract_profiles_from_file uses subprocess.



### Use of eval: insecure function (2 flaws)

Issue text: Use of possibly insecure function - consider using safer ast.literal_eval.

- wodles/oscap/oscap.py line 111
- wodles/oscap/oscap.py line 113

This was also reported in #8347 as we should consider using a safer function instead of eval.

**Comment by mcarmona99** [comment]
## Issue update - Summary

To sum up, I have created 11 new issues reporting the possible vulnerabilities found in the `wazuh` repository in its actual `master` branch. The parameters used in the test have been the default ones.

These issues have been grouped in an epic one: https://github.com/wazuh/wazuh/issues/10125
