### ISSUE TITLE
SearchUI investigation for QA documentation

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#1627]
As part of the Epic [1600](https://github.com/wazuh/wazuh-qa/issues/1600), we expect to use **SearchUI** as the main tool to index, filter and display the documentation content of Wazuh QA.
The input for **SearchUI** will be created in the Epic [1536](https://github.com/wazuh/wazuh-qa/issues/1536).
In this issue, we should dump all the information obtained aimed to understand the requirements of implementing SearchUI as a final and working solution.

**Comment by MiguelazoDS** [comment]
### Analysis
---

As part of the analysis of a search engine capable of indexing related data, we were studying the `search-ui` framework, and we found the following information and also some doubts that should be addressed before starting this development.

#### Main repository
---

The GitHub repository of the framework.

https://github.com/elastic/search-ui

#### Introduction
---

As it is described in the documentation it is important to understand the components that are involved in this project.

The first, and probably the more visible functionality, is the `search API` component, which is in charge to index the data we feed into it, and provide a response according to the fields and parameters we set in our query. \
There're two recommended alternatives to achieve that. The first one `Elastic App Search` managed service (non-free), and the `ElasticSearch` self-hosted option that we can install in our own server for free. \
Since we are familiar with `elasticsearch` it is probably the option we are going to use, although any search API should work with more or less effort. If we take this last approach we need to evaluate the alternatives.

The examples that uses `elastic app search` work out of the box without any extra configuration. The information that feeds the `Search API` is fetched from a website. \
For this purpose, `search-ui` uses a `site-connector`. This option does not seem to fit in our needs since the data is not locally stored. Although, more information about it can be read from the official documentation.

https://github.com/elastic/search-ui/tree/master/packages/search-ui-site-search-connector


#### Create a new project
---

To create a project the same way as it is in this demo

https://search-ui-stable.netlify.app/?size=n_20_n

We use the tool [create-react-app](https://create-react-app.dev/) to create an environment as follows.

`
npx create-react-app app_name
`

For that is needed to have the npx package installed, which one is a module that comes with the `npm` package manager.\
That will create a typical directory structure where we can start to develop our project.

![7](https://user-images.githubusercontent.com/13010397/126846026-d3f23b15-27ad-488a-849c-9d980c82ec71.png)

From there we can launch a react app demo using the `npm` or `yarn` package manager. \
As some warnings suggest is not desirable to mix between those two package managers in the same project.

To execute a project we use:

`npm start` or `yarn start`

A http-server will be launched with address **localhost:3000** (the port may change if it is in use), the tool will prompt a different option.

This is just a minimal example of a web application using `react`.

#### Get a project working
---

Within the project workspace, there's a package.json file that lists the dependencies of the project. We need to download that dependencies to execute our application. The dependencies are going to be installed locally in a folder called `node_modules`.

We can use, for this purpose, `yarn` and `npm` as described before.

`yarn install` or `npm install`

The `ElasticSearch` example, which is the one that uses the local installation, has the data to be indexed in a JSON file, that should be sent to `elasticsearch` in order to create the indexes.

https://github.com/elastic/search-ui/tree/master/examples/elasticsearch

As the documentation says the implementation could be done using any JS library or without them (using pure JS). But we think that using `React` will be more convenient if this framework is created on top of it. Although a Vue.js implementation is shared in the description that may be interesting to take a look at.

To send the data to `elasticsearch` we need to make use of the `bulk API` since it let us create indexes for multiple documents in a single call. \
The format of the JSON file is something like this.

```
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_id" : "2" } }
{ "create" : { "_index" : "test", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
```
Here we can specify the action in the JSON body. The document is equivalent to a table row in a relational database.

For more details visit:

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

Once we have `elasticsearch` ready to go we can launch de project.

`ELASTICSEARCH_HOST=http://localhost:9200 npm start`

This project already has a proxy configuration as it is recommended when querying `elasticsearch` through a browser.

Also this example is made to run on `netlify`. Deeper research about this tool should be desirable to see if this is a must-have or optional configuration.

#### Configuring ElasticStack
---

In order to implement a project that makes use of data locally generated we need to configure `elasticsearch` and feed it with the information, we want to be indexed.

- `Install elasticsearch` (the method depends on the OS you have)

    `yay -S elasticsearch`

- Start service

    For systemd execute:

    `systemctl start elasticsearch.service`

- Use http://localhost:9200 in the browser to validate `elasticsearch` is working as expected, or use the `curl` command from the command line.

    Example: `curl -GET http://localhost:9200`

    
    ![8](https://user-images.githubusercontent.com/13010397/126846048-207521fb-e6a4-42ee-aa52-376afc8bd548.png)

To add the data into `elasticsearch` we use `PUT` or `POST` in `curl` command as follows.

`curl -XPOST -H "Content-Type: application/json" localhost:9200/index/type/_bulk --data-binary @data.json`

The use of `PUT` or `POST` depends on what we have as data input. When you know the index id `PUT` should be used as we want to upload the resource as it is, and `POST` when you want ES to specify it for you, since we want to modify the current state of the server.

If we need to delete the index we use `DELETE`

`curl -XDELETE localhost:9200/index_name/`

To check the index we just created using:

`curl -XGET 'localhost:9200/_cat/indices?v'`

![1](https://user-images.githubusercontent.com/13010397/126846066-db342e4f-6ab2-47f9-9a57-9cd8045b2151.png)

A more detailed information about the cluster is done with:

`curl -GET 'localhost:9200/_cluster/health?pretty=true'`

![9](https://user-images.githubusercontent.com/13010397/126846074-13c8ba02-1a18-4e5a-9e40-d539538a5386.png)

As far as we know the `yellow` state of the health check is related to the lacking of shards replicas due to having a single node. \
We can fix this by adding another node to the cluster.

We need to evaluate how bad is this state for our purpose. According to the documentation, there's a risk of losing data, that's why `elasticsearch` warns about it.

There are some considerations to take into account when updating the information.

Probably the best alternative is using the `query API` since it let us update the information using matches.

More information is detailed below.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html

There's also an `IndexAPI` that can be used to add documents to an existing document but also update if it already exists.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html

A concept that we should take in mind is that documents have versions.

#### Alternatives
---

As the JSON format, we need to have for input to `elasticsearch` it would be important to consider a `elasticsearch client` to format the file and make queries.

Besides Python there're libraries for multiple languages, the reference is in the following link.

https://www.elastic.co/guide/en/elasticsearch/client/index.html

#### TODO
---

Receive feedback from the frontend team about the following concerns:

- The overall idea is to understand if this is doable or not.
- What certificates do we need to generate as part of this project for security purposes.
- If so, recommendations about technologies that we should use and should not use.
- What else we need to consider that may delay the development later.
- The best approach to have incremental development working
- Actions to do to have a reasonable performance when using `elasticsearch`

**Comment by MiguelazoDS** [comment]
As a continuation of the previous analysis, some requirements of the implementation were raised as a consequence of the sync with frontend team:
- For now, we can consider removing the **index** and recreate it when new information is ready to be indexed.
- In order to keep a version control management of the documentation, we should take into account the idea to create multiple **indexes**.
- Make use of **index** **templates** which help to define **index** **patterns** and **mapping**.
- With a series of simple manual tests, the format of the **JSON** file generated by the **DocGenerator** scripts could be sent to **Elasticsearch** without modifications. Every **JSON** will be a new document preceded by the **index** information in a header object as the **bulk API** requires.
- An overview of the example code let us know that the workflow of the project is basically to create a state of the information in the webpage from the information received from **Elasticsearch** and then from the current state build a request that will be sent to **Elasticsearch** in order to generate new states.
