### ISSUE TITLE
 Full Yellow in 'test_general_settings' tests of Vulnerability Detector 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1636]
# Description 

Once time that every test was fixed, we need to check if it on the 'test_general_settings' group works, or needs a fix. 
It should work successfully.

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Issue information

| Related issue |
|--|
| Closes https://github.com/wazuh/wazuh-qa/issues/1531|

## Development
In order to finish this issue the following tasks should be fulfilled:
- [x] Research of fails.
- [x] Apply Fix 
- [ ] Full Green/ Full Yellow  in `test_general_settings` for 3 times.

**Comment by mdengra** [comment]
### 2021-07-23

#### Test group: `test_general_settings`

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6868336/test_general_settings_local_r1.log)| 2021-07-23 | Miguel | :yellow_circle: 
|[test_general_settings_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6868337/test_general_settings_local_r2.log)| 2021-07-23 | Miguel | :red_circle: 
|[test_general_settings_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6868338/test_general_settings_local_r3.log)| 2021-07-23 | Miguel | :yellow_circle: 

It seems that going from test: `test_general_settings_enabled` to test: `test_general_settings_ignore_time` produces the following error:
```
        # Check if alert does not appear during ignore time
        for _ in range(1, jumps):
            check_time_travel(time_travel=True, interval=timedelta(seconds=seconds_to_travel))
            with pytest.raises(TimeoutError):
                wazuh_log_monitor.start(timeout=get_configuration['metadata']['timeout'],
                                        callback=custom_callback_vulnerability)
>               raise AttributeError('Alert appeared before ignore_time was finished')
E               AttributeError: Alert appeared before ignore_time was finished

test_vulnerability_detector/test_general_settings/test_general_settings_ignore_time.py:88: AttributeError
.
.
.
FAILED test_vulnerability_detector/test_general_settings/test_general_settings_ignore_time.py::test_ignore_time[get_configuration0]
```

Due to the nature of the error, it may be due to finding messages from the previous test in the current one. I am still investigating.

**Comment by damarisg** [comment]
After to applied merge #1650, it works succesfully.

Test Results:

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[YellowGeneralSetting.log](https://github.com/wazuh/wazuh-qa/files/6880239/YellowGeneralSetting.log)| 2021-07-26 | Seyla| :yellow_circle: |
|[YellowGeneralSetting2.log](https://github.com/wazuh/wazuh-qa/files/6880240/YellowGeneralSetting2.log)| 2021-07-26 | Seyla| :yellow_circle: |
|[YellowGeneralSetting3.log](https://github.com/wazuh/wazuh-qa/files/6880241/YellowGeneralSetting3.log)| 2021-07-26 | Seyla| :yellow_circle: |

**Comment by mdengra** [comment]
### 2021-07-27

#### Test group: `test_general_settings`

Used Wazuh-QA branch: `1531-full-yellow-vuln-det`
Test results with the default settings in the `ossec.conf`: 

| Test Executions | Date  | By  | Status | 
|--|--|--|--|
|[test_general_settings_local_r1.log](https://github.com/wazuh/wazuh-qa/files/6884025/test_general_settings_local_r1.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_general_settings_local_r2.log](https://github.com/wazuh/wazuh-qa/files/6884033/test_general_settings_local_r2.log)| 2021-07-27 | Miguel | :yellow_circle: 
|[test_general_settings_local_r3.log](https://github.com/wazuh/wazuh-qa/files/6884034/test_general_settings_local_r3.log)| 2021-07-27 | Miguel | :yellow_circle:
