### ISSUE TITLE
Modify the QA framework to the save the logs after every test

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-qa#1690]
### Description

When a test fails, sometimes it is difficult to find out the reason because the QA framework doesn't save the `ossec.log` and `archives.log` files. These logs are truncated for every test and that information isn't available when it fails.

It would be really helpful during the debugging process to have them, so it isn't necessary to recover them manually.

**Comment by Rebits** [comment]
In order to store system files, is necessary to use `pytest-html`. Currently, there is a hook https://github.com/wazuh/wazuh-qa/blob/ef1723d37835705eeceeb1a7f2abc0c1ef4ceec1/tests/integration/conftest.py#L276 that stores in a report ossec.log, `ossec.conf` and test arguments when a test fails. 
In order to create a report is necessary to run pytest as following:

```
python3 -m pytest ... --html=report_name.html
```

This will generate an HTML file and an assets folder with specified files.
Maybe it should be desirable to add more information to this report and even make it customizable using pytest arguments if it is possible.

**Comment by pereyra-m** [comment]
Hi @Rebits !

You are right, thank you.
It would be interesting that this option also stores the logs for the passed tests and the `archives.log` file (if exists).

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/issues/1690
