### ISSUE TITLE
Incorrect disk usage calculation in performance tools

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#1718]
## Description

It seems that the disk usage calculation is wrong in the `wazuh_testing/tools/performance/binary.py` script. If we observe any disk graphics created by said tool, the following behavior appears: 

![imagen](https://user-images.githubusercontent.com/23361101/129702548-97f521d7-8c54-473e-833c-00a9e63240d4.png)

Apart from the fact that disk growth follows a logarithmic trend that is strange, we can see that it far exceeds 100% of use, which should not be possible. This is done to calculate the percentage of disk I/O:
https://github.com/wazuh/wazuh-qa/blob/ef1723d37835705eeceeb1a7f2abc0c1ef4ceec1/deps/wazuh_testing/wazuh_testing/tools/performance/binary.py#L137-L146
1. Add the total number of `read_bytes` and `write_bytes` (both cumulative, according to the [psutil doc](https://psutil.readthedocs.io/en/latest/#psutil.Process.io_counters)) of the current process (#L139). 
2. Add the total number of `read_bytes` and `write_bytes` of the entire disk (here the [psutil doc](https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters) makes no mention of it being cumulative) 
3. Divide the result obtained in `1.` by that obtained in `2.` 

The number of read + writes of the process should never exceed the read + writes of the disk as a whole. That is the reason why it is strange that disk usage exceeds 100%. 

On the other hand, if we see, for example, the number of reading operations of the following graph (a test that lasted one day and in which the content of all agent-groups was updated every 30 seconds), we see that the number of KBs read remains static all the time, it never reads anything new, which also does not make sense and seems to indicate that something it is not working well: 
![imagen](https://user-images.githubusercontent.com/23361101/129704309-08e4b894-904d-436c-ba02-a62431d8205d.png)

It would be necessary to review what the expected behavior is and if it coincides with the current one.

**Comment by mcarmona99** [comment]
## Issue update

`wazuh_metrics.py` imports the `Monitor` class and `logger` function from `binary.py`, used to monitor the apid and clusterd stats.

This Monitor class has the code that is not working properly. This code is in the function `get_process_info`.

To replicate this in local, I have built a docker environment and installed the `wazuh-qa` dependencies.
After installing the wazuh_testing package, I have used the wazuh-metrics binary to monitor the wazuh-clusterd process, which is the one showing this wrong behaviour:

`root@wazuh-master:/wazuh-qa/deps/wazuh_testing# wazuh-metrics -p wazuh-clusterd -d
`

This binary logs the events in the file `/tmp/process_metrics/wazuh-metrics.log` and saves the data in `/tmp/wazuh-clusterd.csv`.

```
...
wazuh-clusterd,,08:56:31,3802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wazuh-clusterd,,08:56:32,3802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wazuh-clusterd,,08:56:33,3802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wazuh-clusterd,,08:56:34,3802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wazuh-clusterd,,08:56:35,3802,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...
```


No information is being written in the csv as the following error appears and is not catched:

`psutil.AccessDenied: psutil.AccessDenied (pid=3802)
`

This error appears because of the docker environment.

I have used the binary in local with a python3 instance different to the one running the wazuh-clusterd process. 

First problem I found is the following:

```
>>> psutil.disk_io_counters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 2168, in disk_io_counters
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1125, in disk_io_counters
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1098, in read_procfs
ValueError: not sure how to interpret line '   7       0 loop0 54 0 2164 12 0 0 0 0 0 20 12 0 0 0 0 0 0\n'
```


This only happens in the local test I am doing. The solution was changing the `psutil` version to `5.7`. This doesn't have to be done in wazuh-qa as this is just a local test.

This is the information monitored in a second:

`{'Daemon': 'w', 'Version': None, 'Timestamp': '11:30:31', 'PID': 6686, 'CPU(%)': 0.0, 'VMS(KB)': 0.0, 'RSS(KB)': 0.0, 'USS(KB)': 0.0, 'PSS(KB)': 0.0, 'SWAP(KB)': 0.0, 'FD': 0.0, 'Read_Ops': 1258, 'Write_Ops': 2276, 'Disk_Read(KB)': 792.0, 'Disk_Written(KB)': 60.0, 'Disk(%)': 0.004386290176416643, 'Disk_Read_Speed(KB/s)': 0.0, 'Disk_Write_Speed(KB/s)': 0.0}`


The daemon is whatever as the pid has been hardcoded in order to do this test.

Disk i/o counter:

`sdiskio(read_count=149545, write_count=522352, read_bytes=5350811136, write_bytes=15689745408, read_time=32572, write_time=4010078, read_merged_count=43573, write_merged_count=1049030, busy_time=767268)`

`read + write = 21040556544 Bytes
`

We can see if the disk i/o information we are taking is the correct one using `iostat`:

```
root@wazuh-master:/# iostat -d
Linux 5.11.0-27-generic (wazuh-master) 	08/24/21 	_x86_64_	(16 CPU)

Device             tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd
nvme0n1          26.13       158.67       632.13         0.00    3864905   15397825          0
```

`read + write = 19725035520 Bytes
`

It seems that the amount of total read + write bytes is the same with both tools, so it seems that we are doing a correct use of `psutil.disk_io_counter`.

The problem may be in the part of the code where we are taking the io write and read bytes of the single process:

```
proc.io_counters()
pio(read_count=1783, write_count=42644, read_bytes=811008, write_bytes=1273856, read_chars=961676, write_chars=1387690)
```


I have been investigating and the `iotop` tool could give us a solution since it shows the disk i/o usage per process (percentage). We should investigate if this tool has a Python library.

**Comment by mcarmona99** [comment]
## Issue update

I have solved the problem mentioned in the last comment.

I have created a new thread to be run with the `wazuh-metrics` script. This new thread will run the `iotop` command:

`sudo iotop -p {self.pid} -b -o -k -qqq > {self.output_iotop_file}
`

This will redirect an iotop output in batch mode, only i/o info, kilobytes units and quietly. See the iotop manual in [this comment](https://github.com/wazuh/wazuh-qa/issues/1718#issuecomment-906376217). 

`thread_iotop` -> thread running iotop
`thread_monitor` -> thread running the known `_monitor_process` function

The monitor function will read from the output_iotop_file and will save the new disk i/o information in the info dictionary.

The new disk i/o information is the following:

info['**new_disk_read**'] -> the disk read per second
info['**new_disk_write**'] -> the disk write per second
info['**new_swapin_percentage**'] -> the percentage of time the thread spent while swapping in
info['**new_io_percentage**'] -> the percentage of time the thread spent waiting on I/O

I have tested this with a local script. This script is the one mentioned [here](https://github.com/wazuh/wazuh-qa/issues/1718#issuecomment-907144970). 

These are the new plots generated:

- Disk read:

![image](https://user-images.githubusercontent.com/57481331/131458088-6d10092d-a875-4fa3-8d41-0d59eac0501f.png)

- Disk write:

![image](https://user-images.githubusercontent.com/57481331/131458176-6e804419-d976-4c8f-aac4-3c442d5ef886.png)

- Disk IO %:

![image](https://user-images.githubusercontent.com/57481331/131458270-257cbed1-c9d5-41ce-bd91-58124e08fff1.png)

- Swapping %:

![image](https://user-images.githubusercontent.com/57481331/131458366-0308f4dd-7a67-4394-a2ce-0b2cdd6ed8cd.png)

I am testing this in our testing environment to see real cases.

**Comment by mcarmona99** [comment]
## Issue update
After resuming this issue, we conclude saying that we can calculate the percentage of disk i/o usage with tools that iotop.

Despite this, we have decided to remove this process measure as it is not a good metric. In truth, this metric measures the process read and written bytes in comparison with the system disk bandwith. This is not descriptive as the results will depend on the machine used. 

For example, a process could have a 10% i/o usage in a machine with 100 MB/s of disk bandwidth and the same process will have a 100% if the machine disk has a 10 MB/s bandwidth. This shows that the metric is not descriptive, as I said.
