### ISSUE TITLE
 Bring Authd the capability to avoid re-registering agents that already has valid keys - Integration tests

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-qa#1756]
## Description

This is a tracking purposes issue to reflect the work done on the integration tests for the epic https://github.com/wazuh/wazuh/issues/9549. Below are explained all the tests that will be updated and the new ones that will be developed as well.

As per the analysis made by @palaciosjeremias, @pereyra-m, and @MiguelazoDS, the work should include:

### Authd tests
Extend the yaml files with new test cases to cover the K option:
- _test_authd.py_ -> Extend enroll_messages.yaml with **K:**
- _test_authd_local.py_ -> Extend _local_enroll_messages.yaml_ with **key_hash** (in the JSON payload)
- _test_authd_name_ip.py_ -> Extend _name_ip_pass_tests.yaml_ with **K:** and try to integrate with  _test_authd.py_.
- _test_authd_worker.py_ -> Extend _worker_messages.yaml_ with **K:**. This is a two points test, the test cases has what needs to be sent to main-server and what we must response to it.

### Agentd tests
Deprecate the old tests because they are based on simulators and implement the following tests:
**test_agentd_enrollment_params.py.**
    Must: 
      - Consume a yaml file _wazuh_enrollment_test.yaml_
      - Open port 1515 to listen to the agent's requests.
      - Configure the agent with the yaml configuration 
       - Clean keys if necessary.
       - Start the agent and wait for the key request to arrive (It may take a few seconds (configurable) if they are tests with a key)
       - Compare the request received with the expected one from the .yaml.

**test_agent_auth_enrollment.py**
    Must: 
      - Consume a yaml wazuh_enrollment_test.yaml
      - Open port 1515 to listen for Agent-Auth requests
      - Use the Agent-auth-parser with the yaml configuration to build the correct agent-auth command
      - Clean keys if necessary.
      - Run agent-auth and wait for the key request
      - Compare the received request with the expected one from the .yaml.

**Implement the complete battery of tests in wazuh_enrollment_test.yaml**
    Must: 
      - Cover all key and combination request scenarios.
      - Build on contemplated authd scenarios
        - With specific name.
        -  With group.
        - With specific IP
        - With key / without key

**Comment by MiguelazoDS** [comment]
Taking a look inside the test_authd directory, which contains the tests to cover the enrollment feature on the manager side, we pay special attention to the scripts.

https://github.com/wazuh/wazuh-qa/blob/4.2/tests/integration/test_authd/test_authd.py

https://github.com/wazuh/wazuh-qa/blob/4.2/tests/integration/test_authd/test_authd_name_ip_pass.py

Which use, respectively, the following data files that represent the messages sent from the agent to the manager and the response that the last one gives.

https://github.com/wazuh/wazuh-qa/blob/4.2/tests/integration/test_authd/data/enroll_messages.yaml

https://github.com/wazuh/wazuh-qa/blob/4.2/tests/integration/test_authd/data/name_ip_pass_tests.yaml

The new test cases that we need to implement are related to the fact that is possible now that the manager may receive a message that includes a new option with its hash key. 
That option should be included in the previous YAML files where the messages are configured. 
The question is if we need to cover a complete case where the message is something like this.

`<OSSEC PASS: secret OSSEC A:'ubuntu18' G:'default' IP:'192.168.33.50' K:'e98aa41f34ab9028e41dc12d226557df36244eb0'`

Since now the test cases are split and there is no integration with all the options available. To achieve that we would need to reformat the scripts and their YAML data files.

Having said that and regardless of the combinations we can do, and if we are going to create tests that include all the options or at least include the key option in both tests (we should) there's an extra step if we consider the following cases.

- Check empty key, agent not-duplicated: This may refer to the first time the agent is registered in the manager.
- Check empty key, agent duplicated: In this case, the agent was already registered but the key in the client.keys file was deleted.
- Check not-empty key, agent not-duplicated: This is the case that the agent is removed using the manage_agents tool. 
- Check not-empty key, mismatch agent duplicated: The agent was registered but the key was changed. Similar to the case before, since the keys are not going to match.
- Check not-empty key, match agent duplicated: Here we are trying to re-register an already registered agent. In this case, the manager should reject the registration claiming that the manager already has the hash key.

The inconvenience here is that as the hash key is internally generated by the manager, we can not create a message from outside sending the same key to force a rejection due to the key already registered.

Another concern is that the response that the manager sends to the agent if it finds an already registered key doesn't reflect that on the client-side. 
The message related to "key already exists on manager" in the manager logs, in the agent is just "duplicated agent name" - "unable to add agent"

![4](https://user-images.githubusercontent.com/13010397/130517730-26899c0a-5ac6-4c50-8546-4d6a2c12231a.png)

So the "output" configured in the YAML file is not representative of what is already happening during the registration process.

This is because the response that comes from run_dispatcher in the manager, is generated inside the auth_validate_data function, but this one does not take into account the log messages that auth_replace_agent generates.

**Comment by palaciosjeremias** [comment]
From a first analysis, we have identified the following required tasks to implement IT for the new key hash logic.
### Autd tests
Extend the yaml files with new test cases to cover the K option:
- _test_authd.py_ -> Extend enroll_messages.yaml with **K:**
- _test_authd_local.py_ -> Extend _local_enroll_messages.yaml_ with **key_hash** (in the JSON payload)
- _test_authd_name_ip.py_ -> Extend _name_ip_pass_tests.yaml_ with **K:** and try to integrate with  _test_authd.py_.
- _test_authd_worker.py_ -> Extend _worker_messages.yaml_ with **K:**. This is a two points test, the test cases has what needs to be sent to main-server and what we must response to it.

### Agentd tests
Deprecate the old tests because they are based on simulators and implement the following tests:
**test_agentd_enrollment_params.py.**
    Must: 
      - Consume a yaml file _wazuh_enrollment_test.yaml_
      - Open port 1515 to listen to the agent's requests.
      - Configure the agent with the yaml configuration 
       - Clean keys if necessary.
       - Start the agent and wait for the key request to arrive (It may take a few seconds (configurable) if they are tests with a key)
       - Compare the request received with the expected one from the .yaml.

**test_agent_auth_enrollment.py**
    Must: 
      - Consume a yaml wazuh_enrollment_test.yaml
      - Open port 1515 to listen for Agent-Auth requests
      - Use the Agent-auth-parser with the yaml configuration to build the correct agent-auth command
      - Clean keys if necessary.
      - Run agent-auth and wait for the key request
      - Compare the received request with the expected one from the .yaml.

**Implement the complete battery of tests in wazuh_enrollment_test.yaml**
    Must: 
      - Cover all key and combination request scenarios.
      - Build on contemplated authd scenarios
        - With specific name.
        -  With group.
        - With specific IP
        - With key / without key

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1874
