### ISSUE TITLE
Agentd tests - Failed locally but works on Jenkins to 4.2.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1905]
# Description
Working in [Analysis: Integration tests for 4.2.2-rc1](https://github.com/wazuh/wazuh-qa/issues/1880) was detected that agentd did not work locally on Windows, but It [works](https://ci.wazuh.info/view/Tests/job/Test_integration/11399/) on Jenkins. For that reason, we need to research what is the difference or problems when this test is executed locally and fix it. 

You could find the local Results on `Agentd` section of [Analysis: Integration tests for 4.2.2-rc1](https://github.com/wazuh/wazuh-qa/issues/1880).

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 4.2 | https://github.com/wazuh/wazuh-qa/commit/c6981d83a644cd9fe9b2644680ae26e4bd5ea217 |v4.2.2-rc1 |https://github.com/wazuh/wazuh/commit/411389188f449c3e7a2d97ff059c25035d32f38a |

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-manager-4.2.2-1.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.2 | 40215| v4.2.2-rc1 | wazuh-agent-4.2.2-1.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-agent-4.2.2-1.msi|

### local_internal_options.conf

> agent.debug=2
execd.debug=2
monitord.rotate_log=0

</table>

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  jacqinthebox/windowsserver2016 | Windows | 2 | 1024 |

## Tasks
- [x] Research Failures.
- [x] Fix the Test Cases.
- [x] Verify that each execution works successfully on `4.2.2`. (Full Green - Attach evidence.)

**Comment by danisan90** [comment]
### Agentd updates
Tests were executed in box `gusztavvargadr/windows-10`
| Name  |State | Date| Note| Result
|--|--|--|--|--|
|Agentd| 🔴 |2021/09/17||[ResultsAgentd1](https://github.com/wazuh/wazuh-qa/files/7195605/ResultsAgentd1.zip)
|test_agentd/test_agentd_reconnection|🔴 |2021/09/17|` Error when executing stop in daemon None.`|[ResultsAgentd2](https://github.com/wazuh/wazuh-qa/files/7195660/ResultsAgentd2.zip)
---------------------------------------------------------------------------------------------------------------------------------------------------------------
2021/09/20
Tests will be executed in `jacqinthebox/windowsserver2016` and `gusztavvargadr/windows-10` with debugging steps in order to find the test problem in windows.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1925
