### ISSUE TITLE
GCloud tests - Research of failures on 4.2.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1906]
# Description 

Working in [Analysis: Integration tests for 4.2.2-rc1](https://github.com/wazuh/wazuh-qa/issues/1880) was detected that GCloud did not work on 4.2.2 but works on 4.2.1. 

This issue is to research the root cause about failures on 4.2.2, we need to understand if it is a new problem of the product or if it of our tests.

You could find the local Results on `GCloud` section of [Analysis: Integration tests for 4.2.2-rc1](https://github.com/wazuh/wazuh-qa/issues/1880). 
Below, you can see all execution of Jenkins that also, failed.

| Results | Status|
|--|--|
| [ResultsGcloud](https://ci.wazuh.info/view/Tests/job/Test_integration/11431) | 🔴 
| [ResultsGcloud](https://ci.wazuh.info/view/Tests/job/Test_integration/11445/)| 🔴 
| [ResultsGcloud](https://ci.wazuh.info/view/Tests/job/Test_integration/11478/) | 🔴 

## Package Details

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 4.2 | https://github.com/wazuh/wazuh-qa/commit/c6981d83a644cd9fe9b2644680ae26e4bd5ea217 |v4.2.2-rc1 |https://github.com/wazuh/wazuh/commit/411389188f449c3e7a2d97ff059c25035d32f38a |

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-manager-4.2.2-1.x86_64.rpm |

### local_internal_options.conf

> analysisd.debug=2
wazuh_modules.debug=2
monitord.rotate_log=0

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

## Tasks
- [x] Research Failures.
- [x] Fix the Test Cases.
- [x] Verify that each execution works successfully on `4.2.2`. (Full Green - Attach evidence.)

**Comment by Deblintrake09** [comment]
### Test Results

| Files Tested | Results | Status| Date | By | Note
|--|--|--|--|--|--|
| test_configuration folder | [ResltsTestConfigurationFolder.zip](https://github.com/wazuh/wazuh-qa/files/7205029/ResltsTestConfigurationFolder.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 | The folder was tested and all files pass  |
| test_functionality/test_rules.py | [ResltsTestRules-Unchanged.zip](https://github.com/wazuh/wazuh-qa/files/7205028/ResltsTestRules-Unchanged.zip) | :red_circle: 2021/09/21 | @Deblintrake09 | Fails with an error that credentials file was not found. Line 131 of **/wazuh_testing/gcloud.py** is adding the wazuh installation folder at the start of the file location. This is not new on the file, there is a change from what's coming from the application |
| test_functionality/test_rules.py | [rules_fail_changed.zip](https://github.com/wazuh/wazuh-qa/files/7205047/rules_fail_changed.zip)  | :red_circle: 2021/09/21 | @Deblintrake09 | Results after change to gcloud.py - No more credentials error, but throws gcloud API exception |
| **/test_functionality/** folder | [ResultsTestFunctionalityFolder.zip](https://github.com/wazuh/wazuh-qa/files/7205051/ResultsTestFunctionalityFolder.zip) | :red_circle: 2021/09/21 | @Deblintrake09 | Results after change to gcloud.py - test_rules.py fails. test_logging.py and test_max_messages.py throw API Errors. |

### Steps taken
The fix to remove the credentials file not found from the logs in Issue 1880 and the ResultsTestRules-Unchanged, was changing line 131 from /deps/wazuh_testing/gcloud.py:

```
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "{}".format(credentials)
   ## os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "{}/{}".format(WAZUH_PATH, credentials) ## Original Line
```
This change was tried since the it's adding the WAZUH_PATH at the start of the credentials file path, and causing that error. After the change there's a new gcloud API error.

**Comment by Deblintrake09** [comment]
### Update 2021/09/23 

- After a call with @Rebits, he noted an import missing from `/var/ossec/wodles/gcloud/tools.py`. in the package used.
- The import missing is an import of the `os` package
- After adding the import, `test_rules.py` passed. After running `test_functionality` folder, only test_max_files  fails.
- @Rebits  ran test with this package [wazuh-manager-4.2.2-0.40215.20210921.x86_64.rpm](https://packages-dev.wazuh.com/staging/yum/wazuh-manager-4.2.2-0.40215.20210921.x86_64.rpm) and all tests passed. 
- Set up VM using pakace. 4.2.2-0.40215.20210921
- Waiting for test results

| Files Tested | Results | Status| Date | By | Note
|--|--|--|--|--|--|
| test_rules.py | [ResultsTestRules.zip](https://github.com/wazuh/wazuh-qa/files/7218413/ResultsTestRules.zip) | :green_circle: | 2021/09/23 | @Deblintrake09 |
| /test_functionality/ folder | [ResultsTestFunctionality.zip](https://github.com/wazuh/wazuh-qa/files/7218415/ResultsTestFunctionality.zip) | :red_circle: | 2021/09/23 | @Deblintrake09 | - test_max_messages failed

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/2065
