### ISSUE TITLE
Determine the start and end point of phases in a Wazuh's cluster environment

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1937]
In order to perform cluster-oriented performance tests, it is necessary to be able to determine when each of its two phases starts and ends. Each phase will have certain evaluation criteria, so we need to create an intelligent algorithm to determine the start and end of each phase.

We can consider that the `setup phase` is the phase where most of the work is done. It is the phase in which the different agents connect to each manager and start synchronizing. As for the `stable phase`, in this phase a smaller part of the work is done, maintaining the integrity of the cluster, in this phase, since there are not many changes, there should not be times above the average.

Here we can see an example of the two phases for the `integrity check` task:
![setup_stable](https://user-images.githubusercontent.com/15522808/135050182-4d18262b-f290-4a48-94e0-2cf2336f451a.png)

Testing data:
- [50000A25W.zip](https://github.com/wazuh/wazuh-qa/files/7242289/50000A25W.zip)

**Comment by Selutario** [comment]
# Update

As explained in the original post and in this https://github.com/wazuh/wazuh-qa/issues/1846#issuecomment-915036765, the test should differentiate between two stages within the environment. This is because, while a large number of agents are registered at the same time and their `agent-groups` files are created, the `clusterd` process has a much higher load than usual.

During this high load period that can be considered the setup phase, tasks such as `Agent-info sync` and `Integrity check` are greatly slowed down by the resource consumption of the `Integrity sync` task. Thanks to this differentiation, we can determine what should be the maximum times allowed for those three tasks when the cluster is heavily loaded (many files to synchronize) and when it is "free" (no files to synchronize).

## Setup phase

These are the conclusions we took about the beginning and end of the setup phase in https://github.com/wazuh/wazuh-qa/issues/1846#issuecomment-915036765:

> The **setup phase** begins with the start of the test and ends when the following conditions are met:
> - The number of connected agents matches what is expected.
> - The number of agent-groups files (`/var/ossec/queue/agent-groups`) matches the number of connected agents and it is identical in all nodes of the cluster.

However, we should take one more condition into account, at least in order to determine the thresholds in https://github.com/wazuh/wazuh-qa/issues/1913. The setup phase should not start from the beginning of the test, but from the beginning of the file synchronization. That is, since the first `[Integrity sync]` appears. Before that, the environment can be ready but even more idle than the stable phase, since it is waiting for the agents to connect. That means no large number of files or `Agent-info` to sync.
![image](https://user-images.githubusercontent.com/23361101/135090245-c1dbc20c-9e13-42a2-96e6-68d6fd1aa98b.png)


```
2021/09/24 11:51:38 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Integrity check] Starting.
2021/09/24 11:51:38 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Integrity check] Finished in 0.007s. Sync not required.
2021/09/24 11:51:42 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Agent-info sync] Starting.
2021/09/24 11:51:42 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Agent-info sync] Finished in 0.001307s (0 chunks sent).
2021/09/24 11:51:47 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Integrity check] Starting.
2021/09/24 11:51:47 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Integrity check] Finished in 0.007s. Sync not required.
2021/09/24 11:51:52 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Agent-info sync] Starting.
2021/09/24 11:51:52 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B57_manager_25] [Agent-info sync] Finished in 0.001573s (0 chunks sent).
```

As we can see, these times are much lower than what would be expected in a real environment, therefore, we have to discard them so as not to adulterate the mean, median, etc. calculated for the setup phase.

IN PROGRESS

## Stable phase

IN PROGRESS
