### ISSUE TITLE
Testing and validation of the complete check-files system testing flow

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2245]
After having developed all the necessary components to test the system check-files, we need to perform the necessary tests to ensure that the test is reliable and secure.

To do this, we have to test for all possible cases, taking into account that the test fails when it should fail (there is some change in the system check-files caused by some action of wazuh) and that it passes when it does not.

Also, we have to test this test in the reported failure cases.

**Comment by fedepacher** [comment]
Testing check-files script over Ubuntu 20.04

## Paths that change due to installing Wazuh component

- Installing a manager/agent:
  - `/`
  - `/etc`
  - `/etc/group-`
  - `/etc/group`
  - `/etc/gshadow-`
  - `/etc/gshadow`
  - `/etc/passwd-`
  - `/etc/passwd`
  - `/etc/shadow`
  - `/etc/shadow-`
  - `/etc/mtab`
  - `/etc/init.d`
  - `/var/log`
  - `/var/lib/`
  - `/var/cache/yum`
  - `/var/cache/apt`
  - `/usr/lib`
  - `/usr/share/bash-completion/completions`
  - `/usr/share/lintian/overrides`
  - `/usr/local/lib/python3.9/dist-packages/apt`
  - `/usr/local/lib/python3.9/dist-packages/apt/progress`
