### ISSUE TITLE
Create test for server address configuration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2254]
|QA Branch|Component|
|:--:|:--:|
||Agent|

## Description

After the research done in #2225, we need to create a test for the [server configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#server) in the agent, especially the address. We need to verify we can use IPv4 and IPv6 addresses.

These tests will add support for the https://github.com/wazuh/wazuh/issues/4243 development.

**Comment by MizugorouZ** [comment]
### 2021/11/25 Update on progress
The first task consisted of researching the messages that are generated in `ossec.log` in different scenarios: invalid server address, could not resolve hostname, unable to connect and connected to the server.

After that, we started to develop the test with fixed addresses, in order to monitor those messages. The next step is to add configuration files to test all cases automatically.

**Comment by Rebits** [comment]
Merged https://github.com/wazuh/wazuh-qa/pull/2435
