### ISSUE TITLE
Fail Test execution when building docker image from Windows 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2272]
## Description 

To install QA-CTL I followed the steps in the [guide](https://github.com/wazuh/wazuh-qa/wiki/QACTL-tool-installation-guide), and I had no problems.
At the moment of executing, I followed this [guide](https://github.com/wazuh/wazuh-qa/wiki/QACTL-tool-use-guide), and executed:

> qa-ctl -r test_general_settings_enabled --qa-branch=2173-qa-ctl-v2-release

While the test is running, this error interrupts the execution. (attach image)

![DockerRunReturn1](https://user-images.githubusercontent.com/3978434/143297692-c45d273f-aa04-4cd9-a3d3-57b9f7907134.png)

On **docker image**, we can see than the image was created.

![imagen](https://user-images.githubusercontent.com/3978434/143299233-a6ca2fb4-b677-4b21-b44d-2d906c34810d.png)

## Note

My machine has the following characteristics:
- **Windows Edition**: Windows 10 Home
- **Windows version**: 20H2
- **OS Build**: 19042.1348

**Comment by jmv74211** [comment]
Investigating the failure produced when running the `docker run` on Windows, it appears that the error is as follows:

```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

Looking into this, it seems that the cause of the error is that docker cannot execute its entry-point script because it has a `CRLF` format. In principle, by default, all files in the `wazuh-qa` repository are in `LF` format (except those that need `CRLF`).

Investigating in the @damarisg environment, it seems that git was automatically transforming all `LF` formats to `CRLF` causing the error.

After changing this setting, it is now working correctly.
