### ISSUE TITLE
IT FIM: Refactor 'test_registry' according to new standard (4)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2353]
It is necessary to have a new standard in the tests, this will help to improve their modularization, along with the execution times.

This issue aims to refactor:

- test_registry/test_registry_file_limit/test_registry_limit_values.py
- test_registry/test_registry_file_limit/test_registry_limit_capacity_alerts.py
- test_registry/test_registry_file_limit/test_registry_limit_full.py
- test_registry/test_registry_report_changes/test_registry_diff_size_limit_values.py
- test_registry/test_registry_report_changes/test_registry_all_limits_disabled.py
- test_registry/test_registry_report_changes/test_registry_file_size_values.py
- test_registry/test_registry_report_changes/test_registry_disk_quota_values.py

**Comment by Deblintrake09** [comment]
## Update Work done on Issue During Sprint 4 **27/12/2021 - 07/01/2022**

- Research on tests
- Initial refactor of All tests (Remove hard-coded variables, callbacks and error messages. clean up tests and formatting)
- Test failed on local instances (Possibly linked to Issue [#2421](https://github.com/wazuh/wazuh-qa/issues/2421). On Jenkins they are not run since they are scheduled tests.
- Research on fixing `test_registry_report_changes` tests. A Full rewrite is suggested, dividing each tests in different stages.
