### ISSUE TITLE
Vulnerability detector test module refactor: `test_providers_multiple_providers`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2455]
It is asked to refactor the test module named `test_providers_multiple_providers.py`. 

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [x] Make a study of the objectives of the test, and what is being tested.
- [x] Refactor the test. Clean and modularizable code.
- [x] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [x] Review test documentation, and modify if necessary.
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Test in 5-10 rounds of execution that the test always shows the same result.

## Checks

- [x] The code complies with the standard PEP-8 format.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is processed by `qa-docs` tool without errors.

> Note: It would also be advisable to change the test module name, as it is a bit confusing.

**Comment by fedepacher** [comment]
Created template in order to refactor test_providers_multiple_providers

## Test objective

Download or read feeds from different providers and check that feeds are indexed in the database correctly. It will test Redhat and Debian providers because both providers need two different sources of vulnerabilities. One OVAL file for each supported Debian/Redhat version, and one a JSON feed with global information of the affected packages for each distribution. 

### Test initial/final status
- DB: tables of cve.db empty
- Working manager
- Log truncated

### Test running status
- Working manager configured with vulnerability detector enabled
- Provider enabled
- DB accessible to query feeds indexed
- Log information

### To be checked
- Number of feed in the database before insertion and after feed insertion 
- Messages in the ossec.log file

**Comment by fedepacher** [comment]
Refactor the test test_providers_multiple_providers.py in the branch `2455-test-providers-multiple-providers`.
The test was launched in 5 instances of qa-ctl Centos 8 local machines and passed successfully.
![Screenshot from 2022-01-23 21-41-21](https://user-images.githubusercontent.com/28990973/150711710-8dc1c484-bc4f-4bfd-a271-f4475077d1b9.png)

**Comment by fedepacher** [comment]
Refactor the test_providers_multiple_providers.py using the new structure of wazuh-qa repository in the branch `2455-test-multiple-sources`.
The test was launched individually and passed. 

![Screenshot from 2022-01-25 15-01-38](https://user-images.githubusercontent.com/28990973/151044964-f682f188-5bdb-4cc3-9a16-93cc96c1ac4a.png)

The test was launched in 5 instances of qa-ctl Centos 8 local machines and passed successfully.

![Screenshot from 2022-01-25 16-19-13](https://user-images.githubusercontent.com/28990973/151045294-7ec3fb7f-74d7-4be0-8bf2-cdfb8ba0540e.png)

**Comment by fedepacher** [comment]
New refactor following the new structure configuration structure int the branch `2455-refactor-test-providers-multiple-providers`:
```
data/
 ├── configuration_template
 ├            └── providers_multiple_providers.yaml
 └── test_cases
               └── test_multiple_providers.yaml

```

**Comment by fedepacher** [comment]
Refactor the test to check that the local feeds are indexed in the database. It checks in the corresponding table of the database if a specific mocked vulnerability exists.
