### ISSUE TITLE
[Staging/Develop] Possible file descriptor leak(big increase) manager vuln-detector

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-qa#258]
# Vulnerability detector

| Version | Revision | Branch
| --- | --- | --- |
| 3.11.0 | 31109 | [3.11](https://github.com/wazuh/wazuh/tree/3.11) |

Hello team,

We noticed an increase on the file descriptors used by Wazuh-db at the current 3.11 development branch, our tests have the following configuration and stress scripts:
[Vuln-detector stress script (Windows)](https://github.com/wazuh/wazuh-qa/files/3831699/vuln.txt)
[Syscollector stress script (Windows)](https://github.com/wazuh/wazuh-qa/files/3831705/syscollector.txt)
[Windows agent configuration](https://github.com/wazuh/wazuh-qa/files/3831713/ossec.conf.txt)
[Linux manager configuration](https://github.com/wazuh/wazuh-qa/files/3831728/ossec.conf.txt)

And below we show the obtained charts:
### Manager CPU
![image](https://user-images.githubusercontent.com/10661307/68594346-a00cfd00-0497-11ea-8ef3-94c4c10b2901.png)
### Manager FD 
![image](https://user-images.githubusercontent.com/10661307/68594372-ad29ec00-0497-11ea-90d8-244b32ed01d4.png)
### Manager RSS
![image](https://user-images.githubusercontent.com/10661307/68594397-bca93500-0497-11ea-98e9-45f1ec13ef97.png)

### Win agent CPU
![image](https://user-images.githubusercontent.com/10661307/68594457-dc405d80-0497-11ea-91f5-a894f23ceb75.png)
### Win agent FD
![image](https://user-images.githubusercontent.com/10661307/68594466-e8c4b600-0497-11ea-8484-f365b89eb31a.png)
### Win agent RSS
![image](https://user-images.githubusercontent.com/10661307/68594496-f7ab6880-0497-11ea-8527-3b5bb10a3953.png)

Regards.

**Comment by crolopez** [comment]
Hi @okynos,

When `wazuh-db` starts, it opens the existing databases in `/var/ossec/queue/db/<ID>.db`

https://github.com/wazuh/wazuh/blob/0ce2d0fc00800ca85e41c2cf95e86a162339e4f0/src/wazuh_db/main.c#L426

This process takes a descriptor for each database and its metadata files. After this, the necessary databases are closed until less than the number defined by `wazuh_db.open_db_limit` remains open.

https://github.com/wazuh/wazuh/blob/0ce2d0fc00800ca85e41c2cf95e86a162339e4f0/src/wazuh_db/main.c#L379

In summary, it is normal to keep 3 file descriptors for each database created, plus another ~10-20 internal descriptors that wazuh-db keeps permanently open.

So, if you have the default value of `wazuh_db.open_db_limit` configured, 64, and your `/var/ossec/queue/db` folder has more than this number of database, the graphics are normal.

The explanation for having so many databases with only 2 agents connected is due to the script that was being used to stress Vulnerability Detector, in combination with the fact that the databases of the re-registered agents are not deleted.
