### ISSUE TITLE
Stress Test: Footprint comparision test

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2704]
| Related issue |
|---|
| https://github.com/wazuh/wazuh-qa/issues/2694 |

### Description

As part of the test stress analyzer, is required to develop a footprint comparison test.
The aim of this new test is to ensure footprint is not increasing during the development time.

### Design
In order to allow version comparison, we are going to use the `report_generator` tool, a JSON file that describes the environment during the specified time. The test will accept two reports as arguments, a current build report and a representative report of the previous version. If the developed version resources are greater than the previous version in a meaningful way, the test should fail.

**Comment by mauromalara** [comment]
Working branch: [2704-test-compare-footprint](https://github.com/wazuh/wazuh-qa/tree/2704-test-compare-footprint)

**Comment by mauromalara** [comment]
## 06/04/2022

### Description
The test will be **"On Hold"** until the content of the reports is defined. That's because this test depends on the input files to compare the values inside them and give a result.

### For now...
The test receives 2 file paths as parameters where the reports are stored, then it reads the data inside those files and validates that it has a valid JSON format. Finally, the test validates the metadata inside the files to verify that the environments were the same in both stress tests.

#### How to use
**Parameters**

`--first_report`: Is the report that comes from the older version.
`--second_report`: Is the report that comes from the newer version.

**Execution example:**

`python3 -m pytest -s tests/performance/test_footprint/test_footprint_between_versions.py --first_report <PATH_TO_REPORT>  --second_report <PATH_TO_REPORT>`

### Expected

1. **The test must be flexible**: It means that the test should be able to compare 2 versions of Wazuh under different conditions (all daemons running, some of them running, with N quantity of agents, running in different OS, etc.).
