### ISSUE TITLE
Gcloud IT: `test_max_messages` error 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2880]
### Description

During https://github.com/wazuh/wazuh-qa/issues/2879 nightly, `test_max_messages` Gcloud IT test fails.
Is required further research to determine the cause of the error.

### Error output
```
test_gcloud/test_functionality/test_max_messages.py:183: in test_max_messages
    assert int(number_pulled) >= publish_messages
E   AssertionError: assert 0 >= 100
E    +  where 0 = int('0')
```

**Build**: https://ci.wazuh.info/job/Test_integration/26273/
**Report**:  [report.html](https://github.com/wazuh/wazuh-qa/files/8677359/manager_html_report_Test_integration_B26273_20220512005724.1.zip)

**Comment by Deblintrake09** [comment]
# Research 2022/05/23

- Set up local Enviroment and launched Test instances :green_circle: x5
- Launched Jenkins instances

## Tests Results
| Test Path | Os/Type | Jenkins | Local | Date | By |
|--|--|--|--|--|--|
|  test/integration/test_gcloud/ CentOS - Manager | [:large_blue_circle:](https://ci.wazuh.info/job/Test_integration/26733/) [:large_blue_circle:](https://ci.wazuh.info/job/Test_integration/26732/) [:large_blue_circle:](https://ci.wazuh.info/job/Test_integration/26729/)  | [:green_circle:]() [:green_circle:]() [:green_circle:]() [:green_circle:]() [:green_circle:]() | 2022/05/23  | @Deblintrake09 |

**Comment by damarisg** [comment]
|Version | Revision | 
|--|--|
| 4.5.0 | 0.40500.20220520 | 

| Test Path | Os/Type | Jenkins| Date | By | 
|--|--|--|--|--|
| test_gcloud/ | Manager | [:green_circle:](https://ci.wazuh.info/job/Test_integration/26846/)  [:green_circle:](https://ci.wazuh.info/job/Test_integration/26856/) [:green_circle:](https://ci.wazuh.info/job/Test_integration/26851/) | 2022/05/24|  Seyla

This issue was closed because we couldn't reproduce it.
