### ISSUE TITLE
Fix Analysisd IT: test_syscollector_events failure on wait_for_analysisd_startup

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3058]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | |
|--|--|--|--|--|
| 2022-07-01| [2efe60e](https://github.com/wazuh/wazuh/commit/2efe60ec9dc95475f1fe93a206771546d0bf35f4) | Merge pull request https://github.com/wazuh/wazuh/pull/13264 from wazuh/10555-fix-ignore-restrict-directories | [#28308](https://ci.wazuh.info/job/Test_integration/28308) |  |

## Case 

| Module | Case | Tier| Wazuh Type |
|--|--|--|--|
test_analysisd/test_syscollector/test_syscollector_events.py | [Test syscollector events-Test syscollector events] | 0 | Manager

### Description

```
21:14:13  _ ERROR at setup of test_syscollector_events[Test syscollector events-Test syscollector events] _
21:14:13  test_analysisd/conftest.py:46: in wait_for_analysisd_startup
21:14:13      log_monitor.start(timeout=30, callback=callback_analysisd_startup)
21:14:13  /usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:203: in start
21:14:13      error_message=error_message).result()
21:14:13  /usr/local/lib/python3.6/site-packages/wazuh_testing-4.3.0-py3.6.egg/wazuh_testing/tools/monitoring.py:469: in start
21:14:13      raise TimeoutError(error_message)
21:14:13  E   TimeoutError
```
## Tasks
- [x] Run tests in Jenkins
- [x] Run tests in local enviroment
- [x] Fix failures

**Note:** 
- Reported by Nightly [2022-07-01](https://github.com/wazuh/wazuh-qa/issues/3057)
- Nico A. checked that it only happens on Wazuh PR because there aren't the local_internals_options added (Jenkins and Local it works)

**Comment by CamiRomero** [comment]
## Run test in Jenkins

we can see that the error always occurs.

| Tester             | Test path | Jenkins  | OS |Notes                |
|--------------------|-----------|---------|--------|----------------------|     
| @CamiRomero   |  test_analysisd/test_syscollector/test_syscollector_events.py    | [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29185/) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29344/) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29037/) | CentOS-8    |   |  |

**Comment by CamiRomero** [comment]
## Run tests in local environment

The same error occurs in the local environment. After investigation, we can note that is needed add a local internal option.

| Tester             | Test path | Local  | OS |Notes                |
|--------------------|-----------|---------|--------|----------------------|     
| @CamiRomero   |  test_analysisd/test_syscollector/test_syscollector_events.py    | [:red_circle: ](https://github.com/wazuh/wazuh-qa/files/9123805/R1.zip) | CentOS-8    |   |

**Comment by CamiRomero** [comment]
## Fix failures

The fix is in branch `3858-fix-analysisd`

| Tester             | Test path | Jenkins | Local  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|-----|--------|----------------------|
| @CamiRomero  (Developer)  |  test_analysisd/test_syscollector/test_syscollector_events.py         | [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29357/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29358/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29359/)  | [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/9123873/R1-3058.tar.gz) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/9123874/R2-3058.tar.gz) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/9123875/R3-3058.tar.gz)|   CentOS-8      |   [3310a6](https://github.com/wazuh/wazuh-qa/pull/3109/commits/3310a6a94a6ecefba697163bd3b7c6f4002cc254 )      | Nothing to highlight |
