### ISSUE TITLE
Fix GCloud IT: test_max_messages error not received expected messages

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3063]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | |
|--|--|--|--|--|
| 2022-07-03| [2efe60e](https://github.com/wazuh/wazuh/commit/b4c9ab6680d318b1ae20d73b72d6d5450bf8f7be) | Fix remoted not updating total bytes sent by UDP (#13979)| [#28540](https://ci.wazuh.info/job/Test_integration/28540/) |  |

## Case 

| Module |  Tier| Wazuh Type | OS 
|--|--|--|--|
test_gcloud/test_functionality/test_max_messages.py | 0 | Manager| CentOS

### Description

```
23:56:04  FAILED test_gcloud/test_functionality/test_max_messages.py::test_max_messages[get_configuration0-publish_messages0]
23:56:04  FAILED test_gcloud/test_functionality/test_max_messages.py::test_max_messages[get_configuration0-publish_messages1]
23:56:04  FAILED test_gcloud/test_functionality/test_max_messages.py::test_max_messages[get_configuration0-publish_messages2]
```

## Tasks
- [x] Run tests in Jenkins
- [x] Fix failures

**Comment by CamiRomero** [comment]
## Run test in Jenkins

The test fails every time
## Testing performed
| Tester             | Test path | Jenkins  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|--------|----------------------|
| @CamiRomero   | test_gcloud/test_functionality/test_max_messages.py          | [:red_circle:](https://ci.wazuh.info/job/Test_integration/28986/) [:red_circle:](https://ci.wazuh.info/job/Test_integration/28996/)  [:red_circle:](https://ci.wazuh.info/job/Test_integration/28997/) | Centos8 | [394f627](https://github.com/wazuh/wazuh/commit/394f627b3915f64dfc1a5b7ba55f61076159d2d2)  |  |

**Comment by CamiRomero** [comment]
## Fix failures

The failure is due to a change in the regex when wanting to run the test in Wazuh 4.3.x.

## Run test in Jenkins

The test fails every time
## Testing performed
| Tester             | Test path | Jenkins  | OS | Commit | Notes                |
|--------------------|-----------|---------|--------|--------|----------------------|
| @CamiRomero   | test_gcloud/          | [:green_circle:](https://ci.wazuh.info/job/Test_integration/29001/) [:green_circle:](https://github.com/wazuh/wazuh/commit/394f627b3915f64dfc1a5b7ba55f61076159d2d2)  [:green_circle:](https://ci.wazuh.info/job/Test_integration/29008/) | Centos8 | [394f627](https://ci.wazuh.info/job/Test_integration/29015/)  |  |
