### ISSUE TITLE
E2E tests: Fix AWS infrastructure monitoring test failures

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3211]
## Description

After the debugging and testing achieved in https://github.com/wazuh/wazuh-qa/issues/3166, we could see that `test_aws_infrastructure_monitoring` was failing, so we must find the reason for the failure and a solution for it.

### Executions

- https://github.com/wazuh/wazuh-qa/issues/3166#issuecomment-1228250975

**Comment by juliamagan** [comment]
For the test to work properly we need to create an exclusive trail for the test, but it has a charge.

This issue will remain locked until a decision is made.

**Comment by juliamagan** [comment]
After configuring a trail for S3 data events and modifying the test to use this trail to generate events. No alerts are generated because the event we can generate is `PutObject`. The only events for which alerts are generated can be found at [ruleset/lists/amazon/aws-eventnames](https://github.com/wazuh/wazuh/blob/master/ruleset/lists/amazon/aws-eventnames).

So we need to create a trail that checks the Management events, the drawback is that it has a higher price than the Data events.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
