### ISSUE TITLE
QA Planning: Deprecated force option in auth

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3225]
## Description

This problem aims to investigate [No log when using the deprecated force option in auth](https://github.com/wazuh/wazuh/issues/14137) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Research results

## Research applied change
The change in this PR aims to modify the message shown when the `force_time` and `force_insert` options are enabled. Since this options are deprecated the following messages are expected:

```
2022/08/17 14:10:37 wazuh-authd: WARNING: The <force_insert> tag is deprecated since version 4.3.0.
2022/08/17 14:10:37 wazuh-authd: WARNING: The <force_time> tag is deprecated since version 4.3.0.
```

## Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.

Currently there are no automated testing done for this.

- [ ] Test `force_insert` enabled
   - [ ] Test valid values
   - [ ] Test invalid values
- [ ] Test `force_insert` enabled, no `force_time` value
- [ ] Test `force_insert` enabled, with `force_time` value
   - [ ] Test valid `force_time` values
   - [ ] Test invalid `force_time` values
