### ISSUE TITLE
QA Planning: Filter option in <localfile> to exclude regex matches of log lines 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3227]
## Description

This problem aims to investigate [Filter option in <localfile> to exclude regex matches of log lines](https://github.com/wazuh/wazuh/issues/5628) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by jotacarma90** [comment]
## PR update
Hi team, we have made some recent changes in the [PR](https://github.com/wazuh/wazuh/pull/14782) that introduces the changes in logcollector. I will summarize all the information that may be helpful for testing:

- We have added the possibility to choose the type of regular expression to use. We must configure it with the `type` attribute. The options are osregex, osmatch, pcre2. The default is pcre2.

- We have also implemented a list of expressions to give the possibility to configure multiple ignores or multiple restrict in each localfile. The behavior will be OR for ignore, and AND for restrict.

Some notes and examples I have added in the documentation [PR](https://github.com/wazuh/wazuh-documentation/pull/5571/files):

```
  For formats that group multiple lines, the entire group will be counted as a single log to check if it should be ignored.

  The ignore label is checked before the restrict label, so if you set identical expressions for both settings, no log will be processed.

  On Windows, the ``eventchannel`` format already provides a way to ignore logs through queries, so this setting ``does not apply`` to this format.
```

```
  <localfile>
      <log_format>audit</log_format>
      <location>/var/log/audit/audit.log</location>
      <ignore type="osregex">type=\.+_CHANGE</ignore>
      <ignore type="osregex">type=CONFIG_\.+</ignore>
  </localfile>
  
    <localfile>
      <log_format>syslog</log_format>
      <location>/custom/file/path</location>
      <restrict type="osregex">username_\.+</restrict>
      <restrict type="osregex">Jun\.+</restrict>
  </localfile>
```

The debug messages that will appear when a log is ignored are:

- ignore: 
`(1976): Ignoring the log line '<line string>' due to ignore config: '<configured pattern>''`
- restrict: 
`(1976): Ignoring the log line '<line string>' due to restrict config: '<configured pattern>'`
