### ISSUE TITLE
QA Planning: Malformed merged.mg file 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3240]
## Description

This problem aims to investigate the new changes applied to [Malformed merged.mg file](https://github.com/wazuh/wazuh/issues/14375) and [Remoted: Ensure merged.mg is not malformed](https://github.com/wazuh/wazuh/issues/14771) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by QU3B1M** [comment]
# Task results

<details><summary>Research the applied change.</summary>

This change applies an improvement that is proposed after the testing of the fix for malformed `merged.mg` file. Now when a `merged.mg` file is malformed, it should raise an error and trigger the deletion and recreation of the file (`merged.mg`). Testing this improvement does not seems easy, as now the `merged.md` file is not getting malformed.
</details>

<details><summary>Research if we have a test for this case.</summary>

We don't have any automated tests for this case, the only place in the framework where the `merged.md` file is mentioned is in `deps/wazuh_testing/wazuh_testing/tools/agent_simulator.py::line-92`
</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.</summary>

</details>
