### ISSUE TITLE
QA planning: Vulnerability Detector refactor 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3384]
## Description

This problem aims to investigate [Vulnerability Detector refactor](https://github.com/wazuh/wazuh/issues/14153 ) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Check some videos about this change.
- [x] Define the new test cases. 
- [x] Check cases created by Belén.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by mauromalara** [comment]
## Update 03/10/2022

### Research the applied change

This refactor is focused on improving:
1. **Reliability**: In the past, Wazuh has had to experience segmentation faults because the information that is ingested from different providers has format inconsistency, missing fields, duplicates, and more shortcomings.
2. **Efficiency**: The development team has to release a new version each time a feed changes/updates. Also, the Vulnerability Detector module downloads the feed each time the scan is executed, although the feeds are not updated or no packages are installed/updated/etc.
3. **Availability**: Related to the previous point, these changes will take place after the release process (which takes days to complete), so the user should wait until this change is available to protect their resources against any vulnerabilities.
4. **Usability**: The user has no way to easily access the Vulnerability Detector reports of all its agents and many configuration options require an unnecessary amount of time and effort to fully understand.

That's why the team proposed the following refactoring:

- Sanitize third-party vulnerabilities information and deliver it through the Wazuh Content model
- Reduce the Vulnerability Detector time-to-value by
- Fetching Wazuh Content deltas if possible
- Provide OOTB Wazuh Content baseline at installation time
- Improve UX by reducing Vulnerability Detector configuration options.
- Simplify vulnerability scan by removing current complexity handling from code to Wazuh Content generation step.
- Enhance the vulnerability scanner to avoid unnecessary scans by changing to an event-driven approach.
- Push Vulnerability detector results to Wazuh Indexer

### Define the new test cases

After analyzing the test cases proposed by @BelenValdivia in [this issue](https://github.com/wazuh/wazuh-qa/issues/3233#issuecomment-1249686571) and watching the meeting videos about this refactor, I propose the following test cases:

**Integration tests cases**
- Scan an unsupported OS
- Disable Syscollector before running Wazuh for the very first time
- Ingest a bad Syscollector output (e.g.: `null` fields)
- Schedule a scan and run a scan manually

**E2E test cases**:
- Check that the vulnerability is indexed when installing a vulnerable package
