### ISSUE TITLE
Add SCA Policy for HP-UX B.11.31

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3387]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|               4.4.0         |              https://github.com/wazuh/wazuh/issues/10696          |           https://github.com/wazuh/wazuh/pull/15157         |

## Description

Create Security Assessment Policies for HP-UX B.11.31.

The only document found is this, and it is from 2009 and for version 11i: https://www.cisecurity.org/wp-content/uploads/2017/04/CIS_HP-UX_11i_Benchmark_v1.5.0.pdf

There will be two different policies for the same OS, one will use the bastille tool from HP, the other one will use standard UNIX commands

## Proposed checks

- [x] Request an HP-UX 11.31 system and use the Bastille approach to test the bastille file.
- [x] Disable by deleting the bastille configuration file the bastille tool and verify the Command based policy is executed. 

...

## Configuration and considerations

- [x] HP-UX system must be requested as we did here https://github.com/wazuh/wazuh-packages/issues/997

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [92cf3fe](https://github.com/wazuh/wazuh/pull/15157/commits/92cf3fe0e27a3d82e9ac624094ac5b497d11b1df) |


### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| HPUX | # B.11.31 | CICD Requested  | - |


### Tested packages

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| HPUX |  Requested in https://github.com/wazuh/wazuh-packages/issues/1881 |


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @72nomada

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:


<details>

<summary> Use of the character U+2013 (–) instead of - in check rules :red_circle:</summary>

The checks 21001 in `cis_hpux_11i` and `cis_hpux_11_bastille` use the character `–` instead of `-` in the first rule:
```
    - 'c:swlist –l bundle SecureShell -> r:HP-UX Secure Shell'
```

This probably will produce an error in shell parameters gathering, making this rule consistently fail.


</details>


<details>

<summary>  Use of incorrect characters in checks  :red_circle:</summary>

Multiple checks contain not expected characters (like U+2013 – ), in remediation and descriptions. This could produce failure in the remediation process if the user copy-pastes these commands. 

For instance, consider check 21029 of the `cis_hpux_11i`

```
- id: 21029

title: "Use more random TCP sequence numbers."

description: "Generate initial TCP sequence numbers that comply with RFC1948. Note: In HP-UX 11i v1 and later, an algorithm largely compliant with RFC1948 is already used. However, setting the isn passphrase closes the small remaining gap, and adds entropy to the seed."

rationale: "Makes remote off-net session hijacking attacks more difficult."

remediation: "Perform the following to use more random TCP sequence numbers upon system startup: 1. Create/open the file /sbin/rc2.d/S999tcpisn 2. Add the following line: ndd –set /dev/tcp tcp_isn_passphrase=<random string> replacing <random string> with a string of random characters. 3. Save the file. 4. Set root as the owner and bin as the group owner of the file. 5. Restrict write access to the file. 6. Set the execution bit for the file."
```

We can see that `ndd –set /dev/tcp tcp_isn_passphrase=<random string> replacing <random string>` use `–` instead of `-`


</details>


<details>

<summary> Policies are correctly formatted :red_circle:</summary>


<blockquote>


<details>

<summary> Bad rules indentation </summary>

Rules block should be indented one level. Currently, rules are not indented correctly in any of the new policies files `cis_hpux_11i_bastille` and `cis_hpux_11i`.
Example:

- Current
```
rules:

- 'f:/var/opt/sec_mgmt/bastille/log/Assessment/assessment-log.config -> r:AccountSecurity.user_rc_files="N"'
```

- Expected

rules:
	- 'f:/var/opt/sec_mgmt/bastille/log/Assessment/assessment-log.config -> r:AccountSecurity.user_rc_files="N"'
```


</details>


<details>

<summary> Inconsistent use of " and '' </summary>

Rules should be defined using the character `"` as surrounding character instead of `'`. The `'` should surround checks rules only in the case of using `"` in the rule syntax.
This is the style used in the newest policies like `cis_ubuntu_22`. 
Both `cis_hpux_11i_bastille` and `cis_hpux_11i` contains this format error.

Example:

- Current
```
    rules:
    - 'f:/etc/ftpd'
    - 'c: sh -c "ls -la /etc/ftpd | grep  -e ^-.*root.*sys | grep -v total" -> r:ftpd' 
    - 'c: sh -c "ls -la /etc/ftpd/ftpaccess | grep  -e ^-.*root.*sys | grep -v total" -> r:ftpaccess' 
```

- Expected
```
    rules:
      - "f:/etc/ftpd"
      - 'c: sh -c "ls -la /etc/ftpd | grep  -e ^-.*root.*sys | grep -v total" -> r:ftpd'
      - 'c: sh -c "ls -la /etc/ftpd/ftpaccess | grep  -e ^-.*root.*sys | grep -v total" -> r:ftpaccess'
```



</blockquote>









</details>

**Comment by Rebits** [comment]
### Updated - 17/10/2022
- [Static policies testing](https://github.com/wazuh/wazuh-qa/issues/3387#issuecomment-1280452805)

**Comment by Rebits** [comment]
@72nomada and @DFolchA detected that `4.4` does not compile HPUX properly.
 Manual testing is marked as blocked for https://github.com/wazuh/wazuh/issues/15182

**Comment by Rebits** [comment]
## Update - 20/10/2022
- Request new HP-UX host
- Research HP-UX CIS Policy
- [Manual testing of checks 1.1.2-1.3.1](https://github.com/wazuh/wazuh-qa/issues/3387#issuecomment-1280452805)

**Comment by Rebits** [comment]
Generated packages for https://github.com/wazuh/wazuh/pull/15157 does not compile correctly. After agent installation, the agent does not contain any daemon in the wazuh binaries directory:
```
# ls /var/ossec/bin
wazuh-control
# /var/ossec/bin/wazuh-control restart
/var/ossec/bin/wazuh-control[4]: /var/ossec/bin/wazuh-execd:  not found.
wazuh-execd: Configuration error. Exiting
# 
```
@DFolchA has been noticed.
For now, only static testing is going to be performed.

**Comment by Rebits** [comment]
### Update - 21/10/2022
- Meeting with @72nomada about 
  - HP-UX and HP-UX use same policy id red_circle
  - HP-UX and HP-UX checks use the same ids red_circle 
- Work in checks 1.3.1 - 1.4.3
- Manual installation HP-UX agent and checks command

**Comment by Rebits** [comment]
## Testing after requested changes :large_blue_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15157/commits/b1124fdedaa565ad02983e9586e3b3bfb43fbb9d

***

### Results

**Comment by Rebits** [comment]
## Update - 02/11/2022
- [Second manual testing](https://github.com/wazuh/wazuh-qa/issues/3387#issuecomment-1300286344)

**Comment by 72nomada** [comment]
Updates applied.

**Comment by Rebits** [comment]
## Testing after requested changes :large_blue_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15157/commits/be6b6e5b895d86cc35643e376a79586589f9cbf9

***

### Results 


<details>

<summary> 1.1.2 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :red_circle: Missing `Secure Shell installation instructions at http://h20293.www2.hp.com/portal/swdepot/displayInstallInfo.do?productNumb (non-bastille and bastille) er=T1471AA` reference
- **Rules**: :red_circle:

Wrong audit. It is required to check (non-bastille and bastille):

-   Set the Banner token to /etc/issue. If it is absent, add and set it. Current rule`f:/opt/ssh/etc/sshd_config -> r:^\s*Banner /\.+` is not restrictive enough
-   Set root as the owner of sshd_config and ssh_config.
-   Set sys as the group owner of sshd_config and ssh_config.
-   Restrict write access to sshd_config and ssh_config to the file owner


Expected Failed - :green_circle:

</details>


<details>

<summary> 1.1.3 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



Expected Pass - :green_circle:

</details>


<details>

<summary> 1.2.1 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Wrong audit rule:
```
- 'not c:sh -c "ls -la /var/spool/cron/crontabs | grep -v -e ^-rw-r--r--.*root.*sys | grep -v -e ^d | grep -v total" -> r:^\w'
```

This rule does not fit with CIS audit specifications.
It is required to check permissions and ownership of the `initetd.conf` file


Expected False - :red_circle:

</details>

<details>



<summary> 1.2.2 :yellow_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle:

Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service

Expected Failed - :green_circle:

</details>


<details>

<summary> 1.2.3 :yellow_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle:

Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service


Expected Failed - :green_circle:

</details>

<details>

<summary> 1.2.4 :yellow_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle:


Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service


Expected Failed - :green_circle:

</details>

<details>

<summary> 1.2.6 :yellow_circle:  </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle:

Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service


Expected Failed - :green_circle:

</details>



<details>

<summary> 1.2.7 :yellow_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle::


Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service


Expected Failed - :yellow_circle:

</details>


<details>

<summary> 1.2.8 :yellow_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :yellow_circle:


Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service

Expected Failed - :green_circle:

</details>

<details>

<summary> 1.2.10 :yellow_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Confusing Rule/Remediation. Remediation suggests enabling but rule is based on disabling the service


Expected - :green_circle:

</details>


<hr>

**Comment by 72nomada** [comment]
1.1.2 - Solved
1.2.1 - Solved
1.3.5 - Solved
1.3.10 - Solved
1.3.11 - Solved
1.3.13 - Solved
1.6.1 - SCA Limitation, can't be changed
1.6.2 - Solved
1.6.8 - Solved
1.6.9 - Solved
1.6.11 - Solved

**Comment by Rebits** [comment]
### Update - 03/11/2022
- [Third manual testing](https://github.com/wazuh/wazuh-qa/issues/3387#issuecomment-1301874539)

**Comment by Rebits** [comment]
## Testing after requested changes :large_blue_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15157/commits/7d32e90da2e68965ee4612162a4a6d49ed23868c

***

### Results

**Comment by Rebits** [comment]
## Testing after requested changes :red_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15157/commits/7d32e90da2e68965ee4612162a4a6d49ed23868c

***

### Results

<details>

<summary> 1.1.2 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>


<details>

<summary> 1.2.1 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



</details>

<details>

<summary> 1.3.5 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:




</details>


<details>

<summary> 1.3.10 :red_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Use of `UM_NFSIOD` instead of `NUM_NFSIOD`



</details>



<details>

<summary> 1.3.11 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



</details>



<details>

<summary> 1.3.13 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:




</details>


<details>

<summary> 1.6.1 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:




</details>


<details>

<summary> 1.6.2 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



</details>




<details>

<summary> 1.6.8 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



</details>



<details>

<summary> 1.6.9  :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



</details>


<details>

<summary> 1.6.11 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:




</details>



<details>

<summary> 1.8.3 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:



</details>



<details>

<summary> 1.8.4 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>


<details>

<summary> 1.8.5 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>


<details>

<summary> 1.8.3 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

</details>


<details>

<summary> 1.9.3 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>

**Comment by Rebits** [comment]
### Update - 04/11/2022
- [Fourth manual testing review](https://github.com/wazuh/wazuh-qa/issues/3387#issuecomment-1303679290)

**Comment by Rebits** [comment]
### Update - 07/11/2022
- End to end testing
  -  Package creation

**Comment by Rebits** [comment]
## Testing after requested changes :red_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15157/commits/7d32e90da2e68965ee4612162a4a6d49ed23868c

***

### Results

<details>


<summary> No title for check 30049 :red_circle:  </summary
```
  - id: 30049
    description: "'+' entries in various passwd and group files served as markers for systems to insert data from NIS maps at a certain point in a system configuration file. HP-UX does not use these markers, but they may exist in files that have been imported from other platforms. They should be deleted if they exist."
    rationale: "Legacy '+' entries are no longer required on HP-UX systems, and may provide an avenue for attackers to gain privileged access on the system."
    remediation: "Perform the following to remove any legacy '+' entries in passwd and group files: 1. Display legacy '+' entries: grep '^+:' /etc/passwd /etc/group 2. Remove any entries found from the passwd and group files."
    compliance:
      - cis: ["1.8.5"]
      - cis_level: ["1"]
    condition: all
    rules:
      - 'f:/var/opt/sec_mgmt/bastille/log/Assessment/assessment-log.config -> r:MiscellaneousDaemons.nis_client="Y"'
```

```
2022/11/08 02:54:00 sca: ERROR: Skipping check with id: 30049: Check name is invalid.

```
</details>

**Comment by Rebits** [comment]
Requested changes apply in https://github.com/wazuh/wazuh/pull/15157/commits/bb56b286a4cc490ad28e7e70fd3f254f5582eac5

**Comment by Rebits** [comment]
## Testing after requested changes :large_blue_circle:  

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/commit/bb56b286a4cc490ad28e7e70fd3f254f5582eac5
***

### Results


<details>


<summary> Not title for check 30049 :green_circle: </summary

Title added
```
    title: "Verify no legacy '+' entries exist in passwd and group files."
```

</details>

<details>


<summary> Use Bastille to report security configuration state check command fails for time overtaken :green_circle: </summary
After a meeting with @72nomada, we have decided to avoid generating the report in SCA. Now, bastille policy will depend of a previously generated report:
```
  rules:
    - "c:swlist HPUX*OE* -> r:HPUX11i"
    - "d:/opt/sec_mgmt/bastille/"
    - "f:/var/opt/sec_mgmt/bastille/log/Assessment/assessment-log.config"
```

</details>

<details>


<summary>  HP-UX requirements title is not descriptive enough :green_circle: </summary

Description changed to:
```
  title: "Check HPUX version, bastille is installed and a bastille report is present."
```


</details>

<details>


<summary> Inconsistencies between bastille and non-bastille results :green_circle: </summary

- **1.3.4**: Fixed
- **1.4.1**, **1.6.8**, **1.6.4**, **1.3.1**: These discrepancies are produced for inconsistencies between the bastille and CIS document, and should not be researched for the development.
- **1.3.2**: SCA limitations do not allow improving this logic. An explicit declaration of NISPLUS_SERVER and NISPLUS_CLIENT is required.
- **1.9.1**: Fixed rule
- **1.3.13** and **1.3.9**: SCA limitations do not allow improving this logic

</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

|| |
|-|-|
| 🟢 | Solved |

All the proposed fixes and changes have been implemented in this current development, so development is approved taking into account the reported and fixed things:

- Bastille rules are incorrect. Values should be the same as the referenced CIS file. 🟢
- Some non-bastille rules are incomplete. 🟢
- Style errors in description/remediation/rationale sections. 🟢
- Use of the character U+2013 (–) instead of - in 21001 check. 🟢
- Policies are not correctly formatted. 🟢
- HP-UX and HP-UX use the same policy id. 🟢
- HP-UX and HP-UX checks use the same ids. 🟢
- Checks 1.1.2-1.2.10/1.3.8-1.3.14 remediation field does not correspond to the defined rule, making the policy difficult to understand. 🟢
- Bastille rules are incorrect. Values should be the same as the referenced CIS file. 🟢
- Some non-bastille rules are incomplete. 🟢
- Errors in 1.1.2 and 1.1.3 remediation and description fields. 🟢
- No title for check 30049. 🟢
- Use Bastille to report security configuration state check command fails for time overtaken. 🟢
- HP-UX requirements title is not descriptive enough 🟢
- Inconsistencies between bastille and non-bastille results. 🟢

---

### Observations

There are some checks in which the remediation fields and the rules themselves are inconsistent, indicating a different remediation than the rule commands themselves. For example:

**Check**: Activate service.
**Remediation**: Activate service.
**Rule**: Check that the service is deactivated.

This is so, because the check itself recommends that the service is only activated if it is really necessary, but nevertheless it must be given as failed in the case of being enabled, assuming that the user is aware of the use of such service. In addition, there are other checks in the policy itself that would conflict, because they expect a set of services to be disabled in order to give `PASSED` checks.

By this is meant, that the logical and user-safe implementation has been carried out, but that the check itself is inconsistent.
