### ISSUE TITLE
Update 0580-win-security_rules.xml rules

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3394]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|              4.4.0          |          https://github.com/wazuh/wazuh/pull/13579              |           https://github.com/wazuh/wazuh/pull/13579         |

## Description

Fixes some bugs present in Windows group modification audit rules:

The field used to identify group SID is wrong in rules: 60154, 60155, 60156, 60157, 60158, 60159 and 60160
Change consist on modifying field name win.eventdata.subjectUserSid for win.eventdata.targetSid. subjectUserSid is the SID of enacting the change, and targetSid is the SID of the changed group.

There are other changes related to regexes and Sids. Some of the sids were wrong or not canonical.

## Proposed checks

- [x] Runt the testing command 'runtest.py' and verify all checks pass.

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  [3847522](https://github.com/wazuh/wazuh/pull/13579/commits/3847522d98b07c75d865a0da59ab61b018477f3e)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|    |         |  |          |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|          |   

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  (@72nomada)


### Conclusion

**Comment by fabamatic** [comment]
Comments on the detected issues:

- Rule 60154:
By dropping the final $ the regex ^\p*S-1-5-32-544 would cover both formats {S-1-5-32-544} and S-1-5-32-544.
I guess we can change the regex it to be consistent trough the file.
 

-  Rule 60165:
Will fix, change if_sid  ids for 60141, 60142 and 60150  

- Rule 60166:
Will fix, ad  if_sid  ids for 60141, 60142 and 60150  for global groups besides the existing universal ones

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/13579/commits/3f1e1378fa704f5eee82a38a20ee1bcace5b4b47

***

### Results


<details>
<summary>Rule 60154 :green_circle:  </summary>
<br>


- Before:

```xml
<field name="win.eventdata.targetSid">^\p*S-1-5-32-544</field>
```

- After:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32-544}$|^S-1-5-32-544$</field>
```

It now follows the same format as the other rules and accepts the specific expected values.

</details>

<details>
<summary>Rule 60165 :green_circle:  </summary>
<br>


- Before:

```xml
<if_sid>60144,60145</if_sid>
```

- After:

```xml
<if_sid>60141,60142</if_sid>
```

It now expects global group events.



</details>

<details>
<summary>Rule 60166 :green_circle:  </summary>
<br>


- Before:

```xml
<if_sid>60149,60150,60151,60152</if_sid>
```

- After:

```xml
<if_sid>60149,60150,60151,60152,60141,60142</if_sid>
```

It now expects global and universal group events.

</details>

<details>
<summary>Rule 60167 :green_circle:  </summary>
<br>


- Before:

```xml
<if_sid>60149,60150,60151,60152</if_sid>
```

- After:

```xml
<if_sid>60149,60150,60151,60152,60141,60142</if_sid>
```

It now expects global and universal group events.


</details>

<details>
<summary>Rule 60170 :green_circle:  </summary>
<br>


- Before:

```xml
 <field name="win.eventdata.targetSid">^%{S-1-5-32\S+-545}$|^S-1-5-32\S+-545$</field>
```

- After:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32-545}$|^S-1-5-32-545$</field>
```

`\S+` has been deleted


</details>

<details>
<summary>Rule 60171 :green_circle:  </summary>
<br>


- Before:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32\S+-546}$|^S-1-5-32\S+-546$</field>
```

- After:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32-546}$|^S-1-5-32-546$</field>
```

`\S+` has been deleted

</details>

<details>
<summary>Rule 60172 :green_circle:  </summary>
<br>


- Before:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32\S+-547}$|^S-1-5-32\S+-547$</field>
```

- After:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32-547}$|^S-1-5-32-547$</field>
```

`\S+` has been deleted

</details>

<details>
<summary>Rule 60188 :green_circle:  </summary>
<br>


- Before:

```xml
<if_sid>60144,60145</if_sid>
```

- After:

```xml
<if_sid>60141,60142</if_sid>
```

It now expects global group events.

</details>

<details>
<summary>Rule 60193 :yellow_circle:  </summary>
<br>


- Before:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32\S+-574}$|^S-1-5-32\S+-574$</field>
```

- After:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32\S*-574}$|^S-1-5-32\S*-574$</field>
```

It now expects 0 or more characters between `32` and `-574`.


</details>

### Conclusion :yellow_circle:

Rule changes have been implemented, but an explanation is still lacking for:

- Rule 60193: Why has it been decided that it can accept characters in the middle?

- Number of expected rules depending on whether the group is universal or not: Rules for universal events have 4 `if_sid`, but local and global ones have only 2.

**Comment by fabamatic** [comment]
Regarding rule 60193, as the documentation is not clear on whether the target sid should be S-1-5-32-574 or S-1-5-32-\<domain\>-574 I went with accepting both possibilities. Further look on other documentation seems to point that the correct sid is S-1-5-32-574 . Will remove the \S*

**Comment by fabamatic** [comment]
Regarding the number of if_sids in rules, it's beyond the scope of this pull request as it's legacy data from the rules and assumed to be correct. Will open an issue to research if this is true

**Comment by juliamagan** [comment]
## Testing after requested changes

- Tester: @juliamagan 
- PR commit: https://github.com/wazuh/wazuh/pull/13579/commits/fc8fefd9b28b488df3723acabe5354e7648030c8

***

### Results


<details>
<summary>Rule 60193 :green_circle:  </summary>
<br>


- Before:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32\S*-574}$|^S-1-5-32\S*-574$</field>
```

- After:

```xml
<field name="win.eventdata.targetSid">^%{S-1-5-32-574}$|^S-1-5-32-574$</field>
```

It will now accept `S-1-5-32-574`, with nothing between 32 and 574.

</details>


### Conclusion :green_circle:

Everything seems to be in order.

The following issue has been opened for the `if_sid` number: 
- https://github.com/wazuh/wazuh/issues/15169

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved 
| 🔵 | Proposed to be fixed in future versions or developments | 

After talking with the development team, the testing has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/3394#issuecomment-1274746341):

**(1) Rule 60154: The SID does not follow the same format as the rest and may accept more characters after the SID (cc @wazuh/threat-intel).** 🟢

The development team has fixed it. See https://github.com/wazuh/wazuh-qa/issues/3394#issuecomment-1277204468.

**(2) Rules 60165 and 60188: It's a global group, but the if_sid are for local groups (cc @wazuh/threat-intel.** 🟢

The development team has fixed it. See https://github.com/wazuh/wazuh-qa/issues/3394#issuecomment-1277204468.

**(3) Rules 60166 and 60167: It's an universal group, but it could be global (cc @wazuh/threat-intel.** 🟢

The development team has fixed it. See https://github.com/wazuh/wazuh-qa/issues/3394#issuecomment-1277204468.

**(4) Rules 60170, 60171 and 60172: There should be no \S+ in the middle of the SID (cc @wazuh/threat-intel.** 🟢

The development team has fixed it. See https://github.com/wazuh/wazuh-qa/issues/3394#issuecomment-1277204468.

**(5) Rule 60193: According to this documentation and this, there should be no \S+ in between, but according to this documentation there should be (cc @wazuh/threat-intel.** 🟢

The development team has fixed it. See https://github.com/wazuh/wazuh-qa/issues/3394#issuecomment-1277204468.

**(6) When they are rules for local groups, two if_sid are taken into account, but for universal ones, four (cc @wazuh/threat-intel.** 🔵

It will be investigated and fixed for future versions. Reported in [wazuh#15169](https://github.com/wazuh/wazuh/issues/15169).
