### ISSUE TITLE
QA Planning:Wazuh service unit cannot be enabled in openSUSE

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3401]
## Description

This problem aims to investigate [Wazuh service unit cannot be enabled in openSUSE](https://github.com/wazuh/wazuh/issues/14924) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
## Research changes

The change applied is related to enabling wazuh as a service in openSUSE systems. the command would fail and wazuh would not automatically restart after rebooting the endpoint. The fix replaces the command used so that it will work on open Suse systems.

## Current testing

Currently there is no specific test that checks that the system is enabled properly.

## Testing

The testing proposed for this fix, is manual testing where the agent/manager is installed and the service is enabled, and after rebooting, the service is automatically restarted. The manual testing will be handled on Issue #3399 

No IT testing is proposed, since this testing requires that the endpoint is rebooted.
