### ISSUE TITLE
Unstable FIM tests for Solaris agent

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3405]
| Version | Commit | Report
| --- | --- | --- |
| 4.5.0 | 9ce0d83 |  [solaris_report.zip](https://github.com/wazuh/wazuh-qa/files/9698681/agent_solaris_html_report_Test_integration_B32353_20221001023820.zip)

### Description
Solaris agent FIM tests seem unstable. The test case `test_realtime_unsupported[get_configuration0]`. It is required to check these tests and ensure they are stable

**Comment by fedepacher** [comment]
# Update 2022/11/03

The Wazuh agent works as is expected in manual testing in a Solaris 11 OS, ignoring the `realetime` tag and using the `schedule` mode instead. 
On the other hand, the test has been launched several times and it could not reproduce the failure.

**Comment by fedepacher** [comment]
# Update 2022/11/07

I have noticed that every time the test fails is because it has performed a DateTime change before letting Wazuh achieve the following log:

```
DEBUG: Finished calculating FIM integrity.
```

This means, that the test creates/modifies/deletes a file, makes a DateTime change, and checks for the FIM integrity result but, as FIM has not finished calculating the integrity it fails.
This problem may be done by the use of DateTime change. To avoid the use of the time travel function, I propose the addition of the following tag to the `ossec.conf` file i the `syscheck` module:

```
<frequency>3</frequency>
```

This tag will set the scan frequency to 3 seconds instead of using the default value of 43200 seconds (12 hours).
