### ISSUE TITLE
Repeated offenders not working/implemented in windows

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#3424]
| Target version | Related issue | 
|--------------------|--------------------|
|           4.4        |        https://github.com/wazuh/wazuh/issues/8400                |  

## Description

This issue aims to implement, the lack of the ability to repeat offenders in active response for windows. The same functionality of repeated offenders in Linux for Windows.

### Case 1: If there is a recurrence before the timeout expires.

- [x] The first log is for the configured timeout of the `active-response`
- [x] The second log (first recurrence) where the waiting time would become 1 minute.
- [x] The third log (second recurrence) where the waiting time would become 2 minutes.
- [x] The fourth log (third recurrence) where the timeout would become 3 minutes.
- [x] The fifth log (fourth recurrence) where the waiting time would become 5 seconds.

### Case 2: Timeout negative value.

- [x] Takes a default value.

### Case 3: Timeout valid where a repeated_offenders negative value.

- [x] Takes a default value.

### Case 4: Repeat_offenders exceeds the established recurrence limit.

- [x] The first log is for the configured timeout of the `active-response`.
- [x] The second log (first recurrence) where the waiting time would become 1 minute.
- [x] The third log (second recurrence) where the waiting time would become 2 minutes.
- [x] The fourth log (third recurrence) where the timeout would become 3 minutes.
- [x] The fifth log (fourth recurrence) where the waiting time would become 4 minutes.
- [x] The sixth log (fifth recurrence) where the waiting time would become 5 minutes.
- [x] The seventh log is for the configured timeout of the `active-response`.

### Case 5: Repeat_offenders values are set more than once.

- [x] Takes the second values

### Manager-side configuration test

```
<active-response>
  <disabled>no</disabled>
  <command>netsh</command>
  <location>defined-agent</location>
  <agent_id>002</agent_id>
  <rules_id>60122</rules_id>
  <timeout>5</timeout>
</active-response>
```

### local_internal_option configuration 

- windows.debug=1

#### Windows agent-side configuration test

```
<active-response>
  <disabled>no</disabled>
  <repeated_offenders>1,2,3</repeated_offenders>
</active-response>
```

#### Manager-side configuration test

```
<timeout>-5</timeout>
```

#### Windows agent-side configuration test

```
<active-response>
  <disabled>no</disabled>
  <repeated_offenders>1,2,3</repeated_offenders>
</active-response>
```

#### Windows agent-side configuration test
```
<active-response>
  <disabled>no</disabled>
  <repeated_offenders>-1,2,3</repeated_offenders>
</active-response>
```

#### Windows agent-side configuration test
```
<active-response>
  <disabled>no</disabled>
  <repeated_offenders>1,2,3,4,5,6,7</repeated_offenders>
</active-response>
```

#### Windows agent-side configuration test
```
<active-response>
  <disabled>no</disabled>
  <repeated_offenders>1,2,3</repeated_offenders>
  <repeated_offenders>4,5</repeated_offenders>
</active-response>
```

**Comment by fedepacher** [comment]
## Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @fedepacher  |  (https://github.com/wazuh/wazuh-qa/pull/3371) | 
	

### Testing environment


| OS | OS version | Deployment | Instance |
|-- |-- |-- |-- | 
| Ubuntu |  22.04 LTS |  EC2 | Manager |
| Windows |  Server 2019 |  EC2 | Agent |


### Status

- [x] In progress
- [x] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jmv74211 


### Conclusion 

Some of the required checks were not got the expected result. For this reason, it will be created an issue to register the bugs

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 


The testing has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/3424#issuecomment-1279061886) and discussed with the related development team:

**(1) active-response timeout does not reset the state after an expired timeout. repeated_offenders timeout remains till the manager restarts (cc @wazuh/binary-beasts).** 🔵

It will be fixed for future versions. Reported in [wazuh#15171](https://github.com/wazuh/wazuh/issues/15171).

**(2) active-response and repeated_offenders timeout allows negative values without warning or error message. Negative values have not effects(cc @wazuh/binary-beasts).** 🔵

It will be fixed for future versions. Reported in [wazuh#15171](https://github.com/wazuh/wazuh/issues/15171).

**(3) Duplicated repeated_offenders tag takes as valid value the first tag instead the second one (cc @wazuh/binary-beasts).** 🔵

It will be fixed for future versions. Reported in [wazuh#15171](https://github.com/wazuh/wazuh/issues/15171).
