### ISSUE TITLE
AIX package and capabilities testing

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-qa#3502]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 3.1.0                     | https://github.com/wazuh/wazuh/issues/15228                       |                    |

## Description
Hello team,

We built this Wazuh manager for AIX in local mode, meaning doesn't have remoted or Wazuh-DB/API. The manager will still generate alerts. 

The deployment should run smoothly and we are going to cover the next uses cases to make sure they are working on the OS:
- Monitor system/application logs, using rules (signatures) to detect threats.
- Scan files/directories to monitor their integrity. For example configuration files or system binaries.
- Detect malware behavior (more specifically rootkits), by looking for hidden files, hidden processes, or hidden ports.
- Trigger automatic responses when a threat is detected.

Link to package: https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/3.1/wazuh-local-3.1.0-1.aix6.1.ppc.rpm

## Proposed checks

- [x] Install Wazuh manager and check that is running as expected and generate alerts
- [x] Monitor system/application logs, using rules (signatures) to detect threats.
- [x] Scan files/directories to monitor their integrity. For example configuration files or system binaries.
- [x] Detect malware behavior (more specifically rootkits), by looking for hidden files, hidden processes, or hidden ports.
- [x] Trigger automatic responses when a threat is detected.

Regards,

Miguel Casares

**Comment by Rebits** [comment]
## Tester review


| Tester | 
|--------|
| @Rebits  |


### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| AIX              | 6.1 TL9         | SiteOX        | - |



### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:


<details>

<summary> Install Wazuh manager and check that is running as expected and generate alerts :large_blue_circle: </summary>

</details>


<details>

<summary> Monitor system/application logs, using rules (signatures) to detect threats :large_blue_circle: </summary>

</details>


<details>

<summary> Scan files/directories to monitor their integrity. For example configuration files or system binaries :large_blue_circle: </summary>

</details>


<details>

<summary> Detect malware behavior (more specifically rootkits), by looking for hidden files, hidden processes, or hidden ports :large_blue_circle: </summary>

</details>


<details>

<summary> Trigger automatic responses when a threat is detected :large_blue_circle:</summary>

</details>

**Comment by Rebits** [comment]
### Updates - 25/10/2022
New packages were generated by @wazuh/cicd team for AIX 5.3 and 6.1
- AIX 5.3: https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/3.1/wazuh-local-3.1.0-1.aix5.3.ppc.rpm
- AIX 6.1: https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/3.1/wazuh-local-3.1.0-1.aix6.1.ppc.rpm

**Comment by Rebits** [comment]
## Testing after requested changes
-   Tester:  @Rebits 
-   Package: https://github.com/wazuh/wazuh-qa/issues/3502#issuecomment-1290814890





## Testing results :large_blue_circle:

<details>

<summary>  Install Wazuh manager and check that is running as expected and generate alerts :green_circle: </summary>


<blockquote> 

AIX local packages installation seems to work as expected:

- **Installation**:
```
# rpm -ivh wazuh-local-3.1.0-1.aix6.1.ppc.rpm
wazuh-local                 ##################################################
```

- **Manager startup**:
```
bash-4.4# /var/ossec/bin/ossec-control restart
ossec-monitord not running...
ossec-logcollector not running...
ossec-syscheckd not running...
ossec-analysisd not running...
ossec-maild not running...
ossec-execd not running...
wazuh-modulesd not running...
Wazuh v3.1.0 Stopped
Starting Wazuh v3.1.0 (maintained by Wazuh Inc.)...
Started wazuh-modulesd...
Started ossec-execd...
2022/10/25 06:18:59 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-analysisd...
Started ossec-syscheckd...
Started ossec-logcollector...
Started ossec-monitord...
Completed.
bash-4.4#
```


- **Logging**: Very verbose logging (`ossec.log`), expected for the 3.1 version.  
```
...
2022/10/25 16:40:05 ossec-monitord: INFO: Started (pid: 15597570).
2022/10/25 11:40:09 ossec-syscheckd: INFO: Started (pid: 15663140).
2022/10/25 11:40:09 rootcheck: INFO: Started (pid: 15663140).

...
2022/10/25 11:40:11 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2022/10/25 11:40:11 ossec-logcollector: INFO: Monitoring full output of command(360): nestat -tu | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -n -k 4 | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
2022/10/25 11:40:11 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2022/10/25 11:40:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2022/10/25 11:40:11 ossec-logcollector: INFO: Started (pid: 16908296).
```

No errors or warnings found:  

```
bash-4.4# cat /var/ossec/logs/ossec.log  | grep -i error\|warning
bash-4.4# 
```

- **Alerts**: Expected startup alert is generated
```
** Alert 1666716015.0: mail  - ossec,pci_dss_10.6.1,gpg13_10.1,
2022 Oct 25 16:40:15 soaxp181->ossec-monitord
Rule: 502 (level 3) -> 'Ossec server started.'
ossec: Ossec started.
```

</blockquote>
</details>

**Comment by Rebits** [comment]
## Testing results - Logcollector :large_blue_circle: 


<details>


<summary> Multiple files matching monitoring: <code>/tmp/example/*</code> :large_blue_circle: </summary>


</details>



<details>


<summary> Multiple files matching monitoring: <code> /tmp/example/test? </code>  :large_blue_circle:  </summary>


</details>



<details>


<summary> Strftime format: <code>/tmp/example/file.log-%Y-%m-%d</code>  :large_blue_circle:  </summary>


</details>



<details>


<summary> New files are monitored after restart  :large_blue_circle: </summary>


</details>



<details>


<summary> Log Format: <code> json </code>  :large_blue_circle:  </summary>


</details>


<details>


<summary> Log Format: <code> multi-line </code>  :large_blue_circle:  </summary>


</details>


<details>

<summary> Enrich JSON events with <code> label </code> option   :large_blue_circle: 
 </summary>




</details>


<details>

<summary> Command monitoring <code>df </code>  :large_blue_circle:  </summary>




</details>


<details>

<summary> Full command monitoring <code>df </code>  :large_blue_circle:  </summary>




</details>


<details>

<summary> Command monitoring using an alias   :large_blue_circle:  </summary>




</details>


<details>

<summary> Command monitoring using an alias  :large_blue_circle:   </summary>




</details>

**Comment by Rebits** [comment]
## Testing results - CSyslog

<details>

<summary> Basic syslog configuration :large_blue_circle:</summary>

</details>


<details>

<summary> Level filter :large_blue_circle: </summary>

</details>


<details>

<summary> Group filter :large_blue_circle: </summary>

</details>


<details>

<summary> Location filter :large_blue_circle: </summary>

</details>


<details>

<summary> Rule_id filter :large_blue_circle: </summary>

</details>


<details>

<summary> Format <code>json</code> :large_blue_circle: </summary>

</details>


<details>

<summary> Format <code>cef</code> :large_blue_circle:</summary>

</details>


<details>

<summary> Format <code>splunk</code> :large_blue_circle:</summary>

</details>

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Requested improvements   
- **Comments**: For this first iteration of testing, more emphasis has been put on testing the modules most used by the customer. Everything seems to work correctly, taking into account some behaviors that have to be investigated to see if in version `3.1` they were as expected. As a summary:
  - (1). Uninstall and reinstall of the `wazuh-manager` package does not seem to work correctly, because certain files and directories are not deleted.
  - (2). Logcollector does not handle correctly monitored file deletion. According to the documentation, it should try to open a monitored file `logcollector.open_attempts` times. However, that is not the case, trying to access to deleted files permanently. 
  - (3). Minor errors in AIX installation documentation.

This will be discussed with the development team, and the PR will be approved or not on this basis.

**Comment by Rebits** [comment]
## Testing results - Integration :yellow_circle: 

<details>

<summary> Basic Slack integration :yellow_circle:  </summary>

Slack integration does not work correctly. Integration logs suggest that the hook or payload is invalid, although that is not the case. The same integration has been tested in a 4.3.9 centos manager package, working as expected.
```
Slack integration failed to run. Either invalid hook url or payload
```

<blockquote>

<details> 

<summary> <code> ossec.conf </code> </summary>

```
<integration>
  <name>slack</name>
  <hook_url>HOOK_URL</hook_url>
  <alert_format>json</alert_format>
</integration>
```

</details>

<details> 

<summary> <code> integations.log </code> </summary>

```
Thu Oct 27 04:36:34 CDT 2022 /var/ossec/integrations/slack /tmp/slack-1666863394--27532.alert  HOOK    
Thu Oct 27 04:36:34 CDT 2022 /var/ossec/integrations/slack Slack integration failed to run. Either invalid hook url or payload.
```

</details>


</blockquote>



</details>

**Comment by jmv74211** [comment]
## QA review update

As a summary of everything tested, we have the following points:

**(1). Uninstall and reinstall of the wazuh-manager package does not seem to work correctly, because certain files and directories are not deleted.**

This is known and also occurs in current versions and reported in [wazuh-packages#607](https://github.com/wazuh/wazuh-packages/issues/607). In the [documentation](https://github.com/wazuh/wazuh-packages/issues/607) itself, it is recommended that to do a complete uninstall, you manually delete `/var/ossec` afterwards.

**(2). Logcollector does not handle correctly monitored file deletion. According to the documentation, it should try to open a monitored file logcollector.open_attempts times. However, that is not the case, trying to access to deleted files permanently.**

According to the development team, it is possible that for this version this was known, and that this behavior was changed in the `force reload` added in version `3.7.1` at [wazuh#2022](https://github.com/wazuh/wazuh/pull/2022).

The development team tells us that it is tested in `4.4` and that it works correctly.

**(3). Minor errors in AIX installation documentation.**

This has been reported in [wazuh-documentation#5710](https://github.com/wazuh/wazuh-documentation/issues/5710)

**(4). Integratord for slack does not work.**

To test integratord, integration with slack has been used. The result was that it did not work correctly, but it seems to be caused by the slack script itself, rather than the module. This script was refactored in `3.2.2` [wazuh#443](https://github.com/wazuh/wazuh/pull/443).

If requested, more tests could be done with the integrator module.
