### ISSUE TITLE
Windows agent MSI installer disables Restart Manager and closes GUI

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#3512]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4 | https://github.com/wazuh/wazuh-packages/issues/1485| https://github.com/wazuh/wazuh/pull/15207 |

## Description

The Wazuh agent Windows MSI installer creator now disables the Restart Manager and manually closes the GUI, as it gave some problems to upgrade when it was open.

## Proposed checks

For every Windows supported (xp, 2012R2, 2016, 2019, 10, 2022, 11):
- [x] Agent installation
- [x] Agent upgrade from version 4.2.x and 4.3.x with open GUI
- [x] Agent upgrade from version 4.2.x and 4.3.x without an open GUI

## Expected results

The upgrade must finish without errors and the installation can't force a reboot no matter what options are chosen in the FilesInUse Dialog

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |
|  Windows Server |    2016     | EC2 |    ami-0ce166ca1b447f229 |

### Tested packages

| `wazuh-agent` | 
|-----------------|
|   | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@alberpilot)

**Comment by Rebits** [comment]
### Update - 08/11/2022
- PR_Wazuh fails for https://github.com/wazuh/wazuh/pull/15207 development. Talked with @verdx about how to fix the error and relaunch the checks.

**Comment by alberpilot** [comment]
Checks green

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:


<details>


<summary> Error code 2349 replication </summary>


According to the [issue](https://github.com/wazuh/wazuh-packages/issues/1485#issuecomment-1285825052), these steps must be reproduced:
- Install a Windows agent  v4.2.6
- Maintaining the GUI open, upgrade to v4.3.0
- In the File in Use menu, select Close the application and attempt to restart them`.


A pop-up with the error 2349 should appear. However, it was impossible to reproduce this behavior in AWS instances. Instead of the pop-up, the installation gets stuck forever:
![3512-Windows2019Stuck-BugReplication](https://user-images.githubusercontent.com/11089305/201082823-0807860a-f3aa-4c5a-9c47-295da9bcf75b.png)

In the vagrant box specified in the issue, the error has been replicated correctly:

![3512-Windows2019-Error2](https://user-images.githubusercontent.com/11089305/201082902-91c975c8-9f97-49c2-92cb-50b851b80145.png)


</details>
