### ISSUE TITLE
Enhancement - Apply the new structure to the Syscollector IT 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3541]
## Description

After the last restructure of VD, we propose that this new structure will be applied to the Syscollector suite of our IT. 

### Current behavior

The old structure with all tests running.

### Expected behavior

The new structure with all tests running.

# Development stage

- [x] In research
- [x] In development
    - [x] Linux
- [x] In testing phase
    - [x] Linux
- [ ] In Review

**Comment by mauromalara** [comment]
There is an [existing test](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_analysisd/test_syscollector) related with Syscollector that verifies the integration of Analysisd with it. So perhaps a more precise name should be given to this module, for instance: `test_syscollector_integration.py`

**Comment by BelenValdivia** [comment]
The test will follow this structure:

```
integration/
└ test_analisysd/
      └ test_syscollector_integration/
	 │
	 ├ data/
         │   └ rules/
	 │   │ │
	 │   │ └ syscollector_rules.xml
         │   │
	 │   └ test_cases/
	 │       │
         │       └ cases_syscollector_integration.yaml
         │ 
         └ test_syscollector_integration.py
```

Also, we need to refactor the test cases yaml to follow the correct structure adding `configuration_parameters`  and `metadata`. Consequently, the test must be modified to support that structure

**Comment by BelenValdivia** [comment]
11/8
- Refactored some fixtures
- New structure done
- Solved problems to read metadata and reload daemon

**Comment by QU3B1M** [comment]
## Update 24/05/2023
This issue and its PR are resumed.

- Some modifications were needed in order to adapt the tests to last `wazuh` patches b9f270e53b0ce565b9238ffe9a015faa4a1f16c8 
- Cases executed locally resulting on success: [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11559381/report.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11559382/report1.zip)[:green_circle: ](https://github.com/wazuh/wazuh-qa/files/11559383/report2.zip)

**Comment by QU3B1M** [comment]
## Apply requested changes
The requested changes were applied in the commit 008183e5deff23cbd48756d2c63e1a91cb4c9dbc
