### ISSUE TITLE
QA Planning: wazuh-db, wazuh-remoted and wazuh-analysisd show an excessive use of descriptors in 4.4.0

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3617]
## Description

This aims to investigate [wazuh-db and wazuh-analysisd show an excessive use of descriptors in 4.4.0](https://github.com/wazuh/wazuh/issues/15426) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
## Task results

- Research the applied change.
The change was done on the functions that update the state files, every time the state file was updated a new socket descriptor would be opened but not closed, and that caused a memory leak.

- Research if we have a test for this case.
Currently, we have no tests developed for this, but this is something difficult to test, since the socket descriptor is created in the background but not accessible on our end. This error was found on the Stress test suite.

It has been determined that no test cases will be created by QA, testing on this development will be done using the Stress test suite and verify the behavior is now fixed.
