### ISSUE TITLE
Functional testing of AIX `wazuh-manager` local mode

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3678]
| Wazuh automation Issue |
| --- |
| https://github.com/wazuh/wazuh-automation/issues/1027 | 

Based on all the information described in this issue [wazuh-qa#3676](https://github.com/wazuh/wazuh-qa/issues/3676), we are asked to perform the proposed functional tests for the log data collection and file integrity monitoring module using the development version of the `wazuh-manager` local mode on AIX.

For each of the proposed architectures and test cases, the following must be done:

- Perform configuration
- Generate actions in the system to generate the events.
- Verify that the alerts are generated and stored.
- Verify that the alerts have been sent correctly through remote syslog.

## Architectures

- POWER 7.
- POWER 8.
- POWER 9.
- POWER 10.

## Tests cases
<details>

<summary> Logcollector </summary>

-   Different location values:
    -   Common path: `/home/vagrant/test.log`
    -   Wildcard group: `/home/vagrant/file.log-%Y-%m-%d`
    -   Wildcard generic: `/home/vagrant/*.log`
-   Command monitoring:
    -   Command with arguments: `ls -la /tmp`
    -   Command without arguments: `df`
    -   Command monitoring using the `<alias>` option: **Command: `df`** / **Alias: `File system disk space`**
    -   Different `frequency` values: `5`, `10`, `60`
-   Collect events generated since wazuh-logcollector was stopped disabling the `<only-future-events>` option
-   Different `<log_format>` values
    -   `syslog`
    -   `json`
        -   Use the `<label>` option to add custom data in JSON events. **Key**: `testing` / **Value**: `LabelsUsage`
    -   `multi-line`: Read a Python Traceback output as one single log. **Multiline Regex value**: ^Traceback / **Multiline replace value**: `wspace`
-   Change default local internal options
    -   Change the `logcollector.vcheck_files` option to `5`
    -   Change the `logcollector.max_lines` option to `100000`
    -   Change the `logcollector.loop_timeout` option to `1`
    -   Change the `logcollector.remote_commands` option to `0` and `1`. No changes are expected

</details>

<details>

<summary> Syscheck </summary>

- Basic directory monitoring
- Report Changes
- Check all
- Ignore
- Nodiff
- Frequency
- Scan time
- Scan day
- Alert new files
- Scan on start

</details>

<details>

<summary> Syslog Output </summary>

- Configure the manager to send alerts through Syslog

</details>

**Comment by Rebits** [comment]
### Testing results

<details>

<summary> AIX Manager installation :yellow_circle: </summary>


1.  Clone the development branch in an external host

```
git clone https://github.com/wazuh/wazuh.git -b 15502-build-restricted-AIX-manager
```

2. Remove the `.git/.github/.gitignore`


> **Note**
> This step is required by space limitations of the deployed instances

3. Compress the wazuh directory into `wazuh.tar.gz`

```
tar -czvf wazuh.tar.gz wazuh/
```

4. Send through SCP the `wazuh.tar.gz` file
```
scp -i CRED wazuh.tar.gz user@ip:/var
```
5. Untar file
```
gunzip -c /tmp/wazuh.tar.gz
```
6. Install dependencies using [generate_wazuh_packages](https://github.com/wazuh/wazuh-packages/blob/3.1.0-AIX-packages/aix/generate_wazuh_packages.sh)

7. Install the manager using `./install.sh`
```

1- What kind of installation do you want (manager, agent, hybrid or help)? 
manager

  - Manager (server) installation chosen.

  1.2- Do you want to compile and install the Remote and Auth modules? (y/n) [y]: 
n

   - The Remote and Auth modules will not be compiled.

  1.3- Do you want to compile and install the cluster? (y/n) [y]: 
n

   - Cluster will not be compiled.

2- Setting up the installation environment.

 - Choose where to install Wazuh [/var/ossec]: 


    - Installation will be made at  /var/ossec .

3- Configuring Wazuh.

  3.1- Do you want e-mail notification? (y/n) [n]: 


   --- Email notification disabled.

  3.2- Do you want to run the integrity check daemon? (y/n) [y]: 


   - Running syscheck (integrity check daemon).

  3.3- Do you want to run the rootkit detection engine? (y/n) [y]: 


   - Running rootcheck (rootkit detection).

  3.4- Do you want to run policy monitoring checks? (OpenSCAP) (y/n) [y]: 


   - Running OpenSCAP (policy monitoring checks).

  3.5- Active response allows you to execute a specific
       command based on the events received.
       By default, no active responses are defined.

   - Default white list for the active response:
      - 127.0.0.1
      - 9.9.9.9

   - Do you want to add more IPs to the white list? (y/n)? [n]: 


  3.6- Do you want to start Wazuh after the installation? (y/n) [y]: 


   - Wazuh will start at the end of installation.

  3.7- Setting the configuration to analyze the following logs:

    -- /var/ossec/logs/active-responses.log

 - If you want to monitor any other file, just change
   the ossec.conf and add a new localfile entry.
   Any questions about the configuration can be answered
   by visiting us online at https://documentation.wazuh.com/.


   --- Press ENTER to continue ---

```

**Installation script produces errors** in the `inst-functions.sh` script due to the environment root directory does not exist:

```
install: File root was not found.
gmake: *** [Makefile:73: install] Error 2
```


https://github.com/wazuh/wazuh/blob/7c4628174edc7d61c35e8fff9b740986866f5002/src/init/inst-functions.sh#L653


This error does not produce any misconfiguration in the manager and belong to future phases. However it is recommended to include options into the makefile to avoid this step

No further implications in the environment


</details>


<details>

<summary> Update using sources :red_circle: </summary>

Upgrading by sources fails, making reference to the `local` target removed in the development

```
 Wazuh v3.1.0 (Rev. 3491) Installation Script - http://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: AIX wa-1016-second-try 1 (Linux 0.0)
  - User: root
  - Host: wa-1016-second-try


  -- Press ENTER to continue or Ctrl-C to abort. --


 - You already have Wazuh installed. Do you want to update it? (y/n): 
y


  1.2- Do you want to compile and install the Remote and Auth modules? (y/n) [y]: 
n

   - The Remote and Auth modules will not be compiled.

  1.3- Do you want to compile and install the cluster? (y/n) [y]: 
n

   - Cluster will not be compiled.

2- Setting up the installation environment.


    - Installation will be made at  /var/ossec .

4- Installing the system

 - Running the Makefile

gmake: *** No rule to make target 'local', needed by 'build'.  Stop.

 Error 0x5.
 Building error. Unable to finish the installation.

```

</details>


<details>

<summary> No ERROR or WARNINGS  :red_circle: </summary>

- Multiple `Couldn't open directory '/var/ossec/queue/agent-groups': No such file or directory.` errors
- Syscheck default configuration include `/boot` by default: `2023/01/23 10:39:21 ossec-syscheckd: WARNING: Error opening directory: '/boot': No such file or directory`

</details>


<details>

<summary> Logcollector :large_blue_circle: </summary>


<blockquote>

<details>

<summary> Basic syslog file monitoring: `/tmp/example.log` :large_blue_circle:</summary>

</details>

<details>

<summary>Syslog file wildcard group: `/tmp/example.log-%Y-%m-%d`  :large_blue_circle:</summary>

</details>

<details>

<summary> Syslog file wildcard generic: `/tmp/**.log`  :large_blue_circle: </summary>

</details>



<details>

<summary> Syslog command monitoring with arguments: `ls -la /tmp`  :large_blue_circle: </summary>

</details>



<details>

<summary>Syslog command monitoring without arguments: `df`  :large_blue_circle: </summary>

</details>

<details>

<summary> Syslog command monitoring with alias: `File system disk space`  :large_blue_circle: </summary>

</details>

<details>

<summary> Syslog: Only future events  :large_blue_circle: </summary>

</details>

<details>

<summary> JSON basic file  :large_blue_circle: </summary>

</details>

<details>

<summary> JSON file using the label option: `<testing>`   :large_blue_circle: </summary>

</details>

<details>

<summary> Multiline format   :large_blue_circle:</summary>

</details>




<details>

<summary> Logcollector: VCheck files: `5`  :large_blue_circle:</summary>

</details>


<details>

<summary> Logcollector: VCheck files: `100000`  :large_blue_circle:</summary>

</details>



<details>

<summary> Logcollector: Loop timeout: `1`  :large_blue_circle:</summary>

</details>


<details>

<summary> Logcollector: Remote commands: `0`  :large_blue_circle:</summary>

</details>


<details>

<summary> Logcollector: Remote commands: `1`  :large_blue_circle:</summary>

</details>


</blockquote>




</details>


<details>

<summary> Syscheck :large_blue_circle: </summary>

</details>

**Comment by Rebits** [comment]
### Update 24/01/2023
- Functional testing of Syscheck 
- Install python3 and prepare for performance and footprint testing

**Comment by Rebits** [comment]
### Update 25/01/2023
- Finish syscheck testing for certain cases
- Perform Csyslog testing
- Work in performance and footprint setup

Error during psutil module installation
<details>

```
  /opt/freeware/bin/gcc -shared -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/opt/freeware/include/python3.7m/ -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=594 -DPSUTIL_AIX=1 -I/opt/freeware/include/python3.7m -c psutil/_psutil_aix.c -o build/temp.aix-7.1-cpython-37/psutil/_psutil_aix.o
  /opt/freeware/bin/gcc -shared -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/opt/freeware/include/python3.7m/ -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=594 -DPSUTIL_AIX=1 -I/opt/freeware/include/python3.7m -c psutil/_psutil_common.c -o build/temp.aix-7.1-cpython-37/psutil/_psutil_common.o
  /opt/freeware/bin/gcc -shared -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/opt/freeware/include/python3.7m/ -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=594 -DPSUTIL_AIX=1 -I/opt/freeware/include/python3.7m -c psutil/_psutil_posix.c -o build/temp.aix-7.1-cpython-37/psutil/_psutil_posix.o
  /opt/freeware/bin/gcc -shared -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurse
```

</details>

**Comment by Rebits** [comment]
### Update 26/01/2023
- Csyslog module work again. The reported error is no longer replicable https://github.com/wazuh/wazuh-qa/issues/3678#issuecomment-1400668610.
- Opened and research issues

**Comment by Rebits** [comment]
This issue will be closed due to the decision to upgrade the AIX manager to version 4.4.0.
Once the relevant packages have been created, new issues will be created and new testing will be performed.
