### ISSUE TITLE
Performance testing of AIX `wazuh-manager` local mode

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#3679]
| Wazuh automation Issue |
| --- |
| https://github.com/wazuh/wazuh-automation/issues/1027 | 

Based on all the information described in this issue [wazuh-qa#3676](https://github.com/wazuh/wazuh-qa/issues/3676), we want to perform performance tests that allow us to know how Wazuh behaves under certain load scenarios for the proposed modules and the possible limits they may have.

For this purpose, we propose to test and analyze the following test cases:

- **Log data collection**:
    -  Syslog simultaneous data monitoring
       - Add 5 entries to 50 files simultaneously per second
       - Add 20 entries to 50 files simultaneously per second
       - Add 100 entries to 50 files simultaneously per second

       - Add 5 entries to 100 files simultaneously per second
       - Add 20 entries to 100 files simultaneously per second
       - Add 100 entries to 100 files simultaneously per second

       - Add 5 entries using a fixed event size of 5KB to 50 files simultaneously per second
       - Add 20 entries using a fixed event size of 2KB to 50 files simultaneously per second
       - Add 100 entries using a fixed event size of 2KB to 50 files simultaneously per second

  -  **JSON simultaneous data monitoring**
       - Add 5 entries to 50 files simultaneously per second
       - Add 20 entries to 50 files simultaneously per second
       - Add 100 entries to 50 files simultaneously per second

       - Add 5 entries to 100 files simultaneously per second
       - Add 20 entries to 100 files simultaneously per second
       - Add 100 entries to 100 files simultaneously per second

       - Add 5 entries using a fixed event size of 5KB to 50 files simultaneously per second
       - Add 20 entries using a fixed event size of 2KB to 50 files simultaneously per second
       - Add 100 entries using a fixed event size of 2KB to 50 files simultaneously per second

- **File integrity monitoring**
    - Monitor 10 paths and create 100 files per second
    - Monitor 20 paths and create 200 files per second

    - Monitor 10 paths and update 100 files per second
    - Monitor 20 paths and update 200 files per second

    - Monitor 10 paths and delete 100 files per second
    - Monitor 20 paths and delete 200 files per second

    - Monitor 50 paths and make multiple operations in 100 files per second

**Comment by Rebits** [comment]
### PoC - Performance testing

In this PoC we are going to select one of the proposed cases (`Add 500 entries to 50 files simultaneously per second (syslog))` in https://github.com/wazuh/wazuh-qa/issues/3679.
The main objective of this test is to determine the differences, if any, in the number of logcollector EPS supported by the different proposed environments.

<details>

<summary> Environments </summary>

<br>


AIX environment is not ready for real testing. To test the created tools we have proposed to test two Wazuh `3.1.0` environments, Ubuntu Manager and Ubuntu Local, with different resources.


| Hostname | OS | Version | CPU | Memory | Installation type | Version
|---- |----|----|----|----|---- |----|
| Host1 |Ubuntu| 22 | 1 | 1024 | Manager | `3.1.0`
| Host2 |Ubuntu| 22 | 1 | 1024 | Local | `3.1.0`


<details>

<summary> Local Ossec-Init </summary>

```
root@ubuntu-footprint-local:/wazuh-3.1.0# cat /etc/ossec-init.conf 
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.1.0"
REVISION="3491"
DATE="Fri 23 Dec 2022 04:20:24 PM UTC"
TYPE="local"
```


</details>


<details>

<summary> Manager Ossec-Init </summary>

```
NAME="Wazuh"
VERSION="v3.1.0"
REVISION="3491"
DATE="Fri 23 Dec 2022 03:48:58 PM UTC"
TYPE="server"
```



</details>


The main objective of this PoC will be determinate for Host2 (Ubuntu local): 
- How many logcollector EPS are supported?
- How many alerts are lost by the Syslog server? 
- Are there any differences between the local and manager servers?


</details>


<details>

<summary> Methodology </summary>






</details>


<details>

<summary> Add 500 entries to 50 files simultaneously per second  </summary>

<blockquote>


<details>

<br>

<summary> Preconditions </summary>

In order to not alter the testing result it is necessary to create the required files.
This can be done using the same footprint script as follows:

```
python3 footprint.py -t 1 -i 1 --syslog-server-port=517 --path /tmp/testing-syslog/ --epi-file-creation=50 
```

</details>


<details>

<summary> <code> ossec.conf </code> </summary>

```
  <syslog_output>
    <level>4</level>
    <server>127.0.0.1</server>
    <port>517</port>
  </syslog_output>

...


  <localfile>
    <log_format>json</log_format>
    <location>/tmp/testing-json/*</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/tmp/testing-syslog/*</location>
  </localfile>


...

  <syscheck>
    <disabled>yes</disabled>
    <frequency>10</frequency>
    <directories realtime="yes" >/tmp/testing_realtime</directories>
...

```

> Syscheck and Logcollector will be disabled depending on each testing case proceed. 


</details>


<details>

<summary> <code> local_decoder.xml</code> </summary>

```
<decoder name="example">
  <program_name>^example</program_name>
</decoder>

<decoder name="example">
  <parent>example</parent>
  <regex>User '(\w+)' logged from '(\d+.\d+.\d+.\d+)'</regex>
  <order>user, srcip</order>
</decoder>

```


</details>


<details>

<summary> <code> local_rules.xml </code>  </summary>

```
<rule id="100010" level="10">
  <program_name>example</program_name>
  <description>User logged</description>
</rule>


<rule id="120010" level="10">
        <decoded_as>json</decoded_as>
        <field name="testing">\.*</field>
  <description>User logged</description>
</rule>
```


</details>


<details>

<summary> Footprint script </summary>

```
python3 footprint.py -t 300 -i 1 --syslog-server-port=517 --path /tmp/testing-syslog/ --epi-file-update=500  --event-type=syslog --generate-graphics=True 
```

Where:
- **--syslog-server-port**: Syslog server port. 
- **--path**: Path where all file operations will be performed
- **-i**: Selected interval (in seconds)
- **--event-type**: Syslog or JSON
- **--generate-graphics**: Enable graphics visualization
- **--epi-file-update**: Number of events of file edition (event generation) per interval

This command will generate:
-  `footprint.csv` : CSV with information about all the Wazuh processes metrics
- `event.csv`: CSV with information about the alerts generated and received by the syslog server
- Charts with `event.csv` and `footprint.csv` information


</details>



<details>

<summary> Results </summary>

- **Footprint**
- **Events**


</details>



</details>


</blockquote>


</details>


<details>

<summary> Individual analysis (To Do) </summary>

</details>


<details>

<summary> Comparision (To Do) </summary>

</details>

**Comment by Rebits** [comment]
### Update 23/12/2022

- Deploy v3.1.0 manager and local 
- Perform multiple iterations of `Add 500 entries to 50 files simultaneously per second`. Pending include the data and analysis into https://github.com/wazuh/wazuh-qa/issues/3679#issuecomment-1364134583

**Comment by Rebits** [comment]
### Update 09/01/2023
- Increase precision in events and metrics calculation 6ad1fc3523d668dd0293c34644ec74d543365f44, 09792d1ed1b639b6f3752fc4c6285491d81acc1c
- Fix errors in the footprint calculation 3254ba3dd6e1ea4be9feb949d50b1cdb93d6a487
- Pending  PoC performance analysis

**Comment by Rebits** [comment]
### Update 11/01/2023
- PoC concluded https://github.com/wazuh/wazuh-qa/issues/3679#issuecomment-1364134583
  - Multiple test cases performed
  - Footprint and performance data gathered
  - Basic analysis of the data
  - Fix minor errors in the environment
  - Create a script for automate environment configuration

**Comment by Rebits** [comment]
### Update 01/02/2023

- Work on a script for performance and footprint automation.
- Pending feedback from @MarcelKemp

**Comment by Rebits** [comment]
### Update 02/02/2023

- Work on the automation script
- Performance measure of AIX agent. Pending report creation

**Comment by Rebits** [comment]
### Update 03/02/2023
- Include new and more meaningful graphics generation in the performance script
- Fixed minor errors in the footprint script

**Comment by Rebits** [comment]
### Update 08/02/2023
- Meeting with @MarcelKemp about AIX agent performance. A new performance analysis was executed manually instead of using developed tools. Results were similar to the specified in https://github.com/wazuh/wazuh/issues/16099.
AIX agent maximum EPS is lower than 200. Persistent warning
```
2023/02/08 11:13:37 wazuh-logcollector: WARNING: Socket busy, discarding the message.
```
Also, it has been checking the performance of a Ubuntu agent. This one, achieve 500 EPS even with lower resources and noticed warning did not appear.
Pending to perform a full analysis and upload the results.

**Comment by Rebits** [comment]
This issue will be closed due to the decision to upgrade the AIX manager to version 4.4.0.
Once the relevant packages have been created, new issues will be created and new testing will be performed.
