### ISSUE TITLE
wazuh-db integration tests fails on Ubuntu

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3716]
## Description

Version: 4.4

During #3695 validation, it was found that there's a specific wazuh_db integration test that fails on Ubuntu, but not in Centos.

```
test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Restore backup file saving previous state - save_pre_restore_state == true] FAILED [  3%]
```
[manager_tests_Test_integration_B35168_20221229174350.txt](https://github.com/wazuh/wazuh-qa/files/10320936/manager_tests_Test_integration_B35168_20221229174350.txt)
[manager_html_report_Test_integration_B35168_20221229174350.zip](https://github.com/wazuh/wazuh-qa/files/10320937/manager_html_report_Test_integration_B35168_20221229174350.zip)

### Current behavior
Test fails on Ubuntu, both Local and Jenkins. Test went well on Centos
### Expected behavior
Tests passes on Ubuntu and Centos as well

**Comment by fedepacher** [comment]
# Update 2023/01/20

It has detected in the `test_db_backup.py` file that when it is recovered the `pre-restore` state backup the result is stored in a list and, in Ubuntu, the list not always remains the same elements order.

Recovered values in the list:
```
['global.db-backup-2023-01-20-18:14:25-pre_restore.gz', 'global.db-backup-2023-01-20-18:14:25.gz']
``` 

The test looks for the element content that has the `pre_restore.gz` substring in the last element of the list. As in ubuntu, sometime, the elements are stored in different order it has prupoused the following:

```
backups = ['global.db-backup-2023-01-20-18:14:25-pre_restore.gz', 'global.db-backup-2023-01-20-18:14:25.gz']
combined = '\t'.join(backups)
assert "-pre_restore.gz" in combined .......
```

So that, the combined string contains all the elements of the list.
