### ISSUE TITLE
Test HLP as Helper Functions as Helper Functions within check/map section

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3735]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |         https://github.com/wazuh/wazuh-qa/issues/3621       |          https://github.com/wazuh/wazuh/pull/15421          |

## Description

The dev team added some parsers that allow you to use the HLPs through them. 

## Proposed test cases

- [x] Use some HLPs as Helper Functions (Verify that the following High Level Parsers work as expected within `check`/`map` section in the `normalize` stage)
  - [x] `quoted`
  - [x] `dsv`
  - [x] `csv`
  - [x] `json`
  - [x] `xml`
  - [x] `kv`
  - [x] `uri`
  - [x] `fqdn`
  - [x] `file`

> `literal` and `ignore` do not have a function helper

**Comment by roronoasins** [comment]
## 2023/01/09

After the performed testing for each HLP in https://github.com/wazuh/wazuh-qa/issues/3703, we need to verify that each one can be used as a parser within `map` section, for example. The documentation is being added, so we will test them using the respective parser located [here](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit#bookmark=id.qtd2vciqgfki). We will test every check that was checked during the previous testing but using the parser in the `normalize`  section. 

- The `dsv` parser was tested.

**Comment by roronoasins** [comment]
## 2023/01/11

Continue with retesting using `map`. Could not reproduce the cases that use an slash (`/`) as delimiter (could not escape it, neither writing it in yaml or json)

**Comment by roronoasins** [comment]
# Conclusion

During the testing process we could test the following cases https://github.com/wazuh/wazuh-qa/issues/3735#issue-1525909641

# Improvements

Error logs within the wazuh-engine `test` feature are confusing because if you mess it up with syntax or parameters, the errors within the tool trace are too generic or not descriptive for each issue because they repeat in multiple situtations, e.g. `Expected a DSV/CSV string`.

# Bugs

- https://github.com/wazuh/wazuh/issues/15879
- https://github.com/wazuh/wazuh/issues/15878
- https://github.com/wazuh/wazuh/issues/15880
- https://github.com/wazuh/wazuh/issues/15881
