### ISSUE TITLE
Read buffer overflow in wazuh-authd when parsing requests

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3742]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4.0|https://github.com/wazuh/wazuh/issues/15861|https://github.com/wazuh/wazuh/pull/15876|

## Description

This issue will fix a buffer overflow hazard in wazuh-authd.

## Proposed checks

- [x] Run auto-enrollment in the agent.
- [x] Run agent-auth in the agent.
- [x] Run a custom SSL client and pass the critical request (will be provided later).

## Steps to reproduce

- Compile the manager with AddressSanitizer.
- Set a 4095-byte password in authd.pass.
- Run any SSL client (or a modified agent-auth) and pass the critical string.

## Expected results

The agent shall enroll normally.

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15876/commits/66b444866992635c30c8f6fbd5a96448efc9ac91 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    20.04     | EC2 |    ami-003530de8839921c4 |
|  centOS |    8     | EC2 |    ami-029496e60f56b4b13 |
|  Windows Server |    2022     | EC2 |    ami-047e29beecff33db0 |


### Tested packages

| `wazuh-manager Deb` |  `wazuh-agent Deb` | `wazuh-agent rpm` | `wazuh-agent win`
|-----------------|-----------------| -----------------| -----------------|
|  [Deb Manager](packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit66b4448_amd64.deb)  | [Deb Agent](packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit66b4448_amd64.deb)   | [RPM Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit66b4448.x86_64.rpm) | [Windows Agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/windows/wazuh-agent-4.4.0-0.commit66b4448.msi) |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@vikman90 )

**Comment by Rebits** [comment]
### Testing results :large_blue_circle: 


<details>

<summary> Bug repplication :large_blue_circle:</summary>

</details>

<details>

<summary> Preconditions </summary>

We are going to deploy an environment of 1 manager (Ubuntu) and 3 agents (centOS, Ubuntu, and Windows Server), [enabling a password for authentication](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html?highlight=use_password#use-password)
```
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <purge>yes</purge>
    <use_password>yes</use_password>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
```

In this case, we are going to use a 4096B password. For example
```
agent111111111...
```


</details>


<details>

<summary> Run auto-enrollment in the agent :green_circle: </summary>

<blockquote>

<details>

<summary> Ubuntu :green_circle: </summary>

The Ubuntu agent was registered correctly

**Agent Control**:
```
   ID: 008, Name: ip-172-31-14-18, IP: any, Active
```

**Ossec Logs**
```
2023/01/13 12:41:46 wazuh-authd: INFO: New connection from 172.31.14.18
2023/01/13 12:41:46 wazuh-authd: INFO: Received request for a new agent (ip-172-31-14-18) from: 172.31.14.18
2023/01/13 12:41:46 wazuh-authd: INFO: Agent key generated for 'ip-172-31-14-18' (requested by any)
2023/01/13 12:41:47 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/01/13 12:41:47 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```



</details>

<details>

<summary> centOS :green_circle: </summary>

The centOS agent was registered correctly

**Agent Control**:
```
   ID: 006, Name: ip-172-31-15-193.ec2.internal, IP: any, Active
```

**Ossec Logs**
```
2023/01/13 12:36:55 wazuh-authd: INFO: New connection from 172.31.15.193
2023/01/13 12:36:55 wazuh-authd: INFO: Received request for a new agent (ip-172-31-15-193.ec2.internal) from: 172.31.15.193
2023/01/13 12:36:55 wazuh-authd: INFO: Agent key generated for 'ip-172-31-15-193.ec2.internal' (requested by any)
2023/01/13 12:36:57 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/01/13 12:36:57 wazuh-remoted: INFO: (1410): Reading authentication keys file. 
```


</details>

<details>

<summary> Windows :green_circle:</summary>

The Windows agent was registered correctly

**Agent Control**:
```
   ID: 010, Name: EC2AMAZ-N9OLJ1L, IP: any, Active
```


**Ossec Logs**
```
2023/01/13 12:52:06 wazuh-agent: INFO: Using password specified on file: authd.pass
2023/01/13 12:52:06 wazuh-agent: INFO: Using agent name as: EC2AMAZ-N9OLJ1L
2023/01/13 12:52:06 wazuh-agent: INFO: Waiting for server reply
2023/01/13 12:52:06 wazuh-agent: INFO: Valid key received
2023/01/13 12:52:06 wazuh-agent: INFO: Waiting 20 seconds before server connection
```

</details>

</blockquote>


</details>


<details>

<summary> Run agent-auth in the agent :green_circle: </summary>

<blockquote>

<details>

<summary> Ubuntu :green_circle:</summary>

The Ubuntu agent was registered correctly using agent-auth:

**Agent Auth output**
```
2023/01/13 12:42:48 agent-auth: INFO: Started (pid: 5785).
2023/01/13 12:42:48 agent-auth: INFO: Requesting a key from server: 172.31.15.160
2023/01/13 12:42:48 agent-auth: INFO: Using password specified on file: etc/authd.pass
2023/01/13 12:42:48 agent-auth: INFO: Using agent name as: ip-172-31-14-18
2023/01/13 12:42:48 agent-auth: INFO: Waiting for server reply
2023/01/13 12:42:48 agent-auth: INFO: Valid key received
```

**Ossec Logs**
```
2023/01/13 12:42:37 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/01/13 12:42:37 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2023/01/13 12:42:48 wazuh-authd: INFO: New connection from 172.31.14.18
2023/01/13 12:42:48 wazuh-authd: INFO: Received request for a new agent (ip-172-31-14-18) from: 172.31.14.18
2023/01/13 12:42:48 wazuh-authd: INFO: Agent key generated for 'ip-172-31-14-18' (requested by any)
2023/01/13 12:42:57 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/01/13 12:42:57 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```

</details>

<details>

<summary> centOS :green_circle:</summary>

The centOS agent was registered correctly using agent-auth:

**Agent Auth output**
```
[root@ip-172-31-15-193 qa]# /var/ossec/bin/agent-auth -m 172.31.15.160
2023/01/13 12:39:36 agent-auth: INFO: Started (pid: 3426).
2023/01/13 12:39:36 agent-auth: INFO: Requesting a key from server: 172.31.15.160
2023/01/13 12:39:36 agent-auth: INFO: Using password specified on file: etc/authd.pass
2023/01/13 12:39:36 agent-auth: INFO: Using agent name as: ip-172-31-15-193.ec2.internal
2023/01/13 12:39:36 agent-auth: INFO: Waiting for server reply
2023/01/13 12:39:36 agent-auth: INFO: Valid key received
[root@ip-172-31-15-193 qa]# 
```

**Ossec Logs**
```
2023/01/13 12:39:36 wazuh-authd: INFO: New connection from 172.31.15.193
2023/01/13 12:39:36 wazuh-authd: INFO: Received request for a new agent (ip-172-31-15-193.ec2.internal) from: 172.31.15.193
2023/01/13 12:39:36 wazuh-authd: INFO: Agent key generated for 'ip-172-31-15-193.ec2.internal' (requested by any)
2023/01/13 12:39:37 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/01/13 12:39:37 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```

</details>

<details>

<summary> Windows :green_circle: </summary>


The Windows agent was registered correctly using agent-auth:

**Agent Auth output**
```
PS C:\Program Files (x86)\ossec-agent> .\agent-auth.exe -m 172.31.15.160
2023/01/13 12:56:29 agent-auth: INFO: Started (pid: 5444).
2023/01/13 12:56:29 agent-auth: INFO: Requesting a key from server: 172.31.15.160
2023/01/13 12:56:29 agent-auth: INFO: Using password specified on file: authd.pass
2023/01/13 12:56:29 agent-auth: INFO: Using agent name as: EC2AMAZ-N9OLJ1L
2023/01/13 12:56:29 agent-auth: INFO: Waiting for server reply
2023/01/13 12:56:29 agent-auth: INFO: Valid key received
```

**Ossec Logs**
```
2023/01/13 12:56:29 wazuh-authd: INFO: New connection from 172.31.7.115
2023/01/13 12:56:29 wazuh-authd: INFO: Received request for a new agent (EC2AMAZ-N9OLJ1L) from: 172.31.7.115
2023/01/13 12:56:29 wazuh-authd: INFO: Agent key generated for 'EC2AMAZ-N9OLJ1L' (requested by any)
2023/01/13 12:56:37 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/01/13 12:56:37 wazuh-remoted: INFO: (1410): Reading authentication keys file.

```



</details>

</blockquote>


</details>


<details>

<summary> Run any SSL client (or a modified agent-auth) and pass the critical string.  :green_circle: </summary>

In order to perform the modified agent-auth request, we have changed the agent_simulator tool.
Changes can be checked in the branch `3742-as-critical-request`. Now agents perform authd process using specified requests in the [development PR](https://github.com/wazuh/wazuh/pull/15876):
```
event = f"OSSEC PASS: agent111111... OSSEC A:'agent4' G:'default,default,...".encode()
```

We simulate the agent using the `simulate_agent` script as follows:
```
python ./simulate_agents.py  -a 172.31.15.160 -n 1
```

Obtaining the expected error message:

```
2023/01/13 13:18:04 sca: INFO: Security Configuration Assessment scan finished. Duration: 8 seconds.
2023/01/13 13:18:04 wazuh-authd: INFO: New connection from 172.31.15.160
2023/01/13 13:18:04 wazuh-authd: INFO: Received request for a new agent (agent4) from: 172.31.15.160
2023/01/13 13:18:04 wazuh-authd: ERROR: Unterminated group field
```

 




</details>

**Comment by Rebits** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved 

The development has been approved. No unexpected behaviors detected
