### ISSUE TITLE
Red Hat Enterprise Linux 9 SCA policy rework - checks 3 to 3.4.2.7

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3819]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.4.x               |         #3391               |        https://github.com/wazuh/wazuh/pull/16016           |

|Check Id and Name| Status| Ready for QA|
|---|---|---|
||||
|3 Network Configuration|||
|3.1 Disable unused network protocols and devices|||
|3.1.1 Ensure IPv6 status is identified (Manual)|⚫||
|3.1.2 Ensure wireless interfaces are disabled (Automated)|⚫||
|3.1.3 Ensure TIPC is disabled (Automated)|⚫||
||||
|3.2 Network Parameters (Host Only)|||
|3.2.1 Ensure IP forwarding is disabled (Automated)|⚫||
|3.2.2 Ensure packet redirect sending is disabled (Automated)|⚫||
||||
|3.3 Network Parameters (Host and Router)|||
|3.3.1 Ensure source routed packets are not accepted (Automated)|⚫||
|3.3.2 Ensure ICMP redirects are not accepted (Automated)|⚫||
|3.3.3 Ensure secure ICMP redirects are not accepted (Automated)|⚫||
|3.3.4 Ensure suspicious packets are logged (Automated)|⚫||
|3.3.5 Ensure broadcast ICMP requests are ignored (Automated)|⚫||
|3.3.6 Ensure bogus ICMP responses are ignored (Automated)|⚫||
|3.3.7 Ensure Reverse Path Filtering is enabled (Automated)|⚫||
|3.3.8 Ensure TCP SYN Cookies is enabled (Automated)|⚫||
|3.3.9 Ensure IPv6 router advertisements are not accepted (Automated)|⚫||
||||
|3.4 Configure Host Based Firewall|||
|3.4.1 Configure a firewall utility|||
|3.4.1.1 Ensure nftables is installed (Automated)|🟢|🟢|
|3.4.1.2 Ensure a single firewall configuration utility is in use (Automated)|⚫||
||||
|3.4.2 Configure firewall rules|||
|3.4.2.1 Ensure firewalld default zone is set (Automated)|⚫||
|3.4.2.2 Ensure at least one nftables table exists (Automated)|🟢|🟢|
|3.4.2.3 Ensure nftables base chains exist (Automated)|🟢|🟢|
|3.4.2.4 Ensure host based firewall loopback traffic is configured (Automated)|⚫||
|3.4.2.5 Ensure firewalld drops unnecessary services and ports (Manual)|⚫||
|3.4.2.6 Ensure nftables established connections are configured (Manual)|⚫||
|3.4.2.7 Ensure nftables default deny firewall policy (Automated)|🟢|🟢|

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16016/commits/d68f83668ef50d872e3deba294e4b98f6352cc55 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  RHEL |    9     | Vagrant |    roboxes/rhel9 |

### Status
- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@72nomada)

**Comment by 72nomada** [comment]
Threat intel - @jk-olaoluwa

**Comment by Rebits** [comment]
## Testing results 

<details>

<summary> 3.1.1 :black_circle:</summary>

Not implemented. Expected due to it is a manual check


</details>

<details>

<summary> 3.1.2 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.1.3 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.2.1 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.2.2 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.1 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.2 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.3 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.4 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.5 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.6 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.7 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.8 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.3.9 :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>


<details>

<summary> 3.4.1.1 :yellow_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :black_circle:
- **Rules**: :yellow_circle:

Check rules do not only ensure that nftables is installed, it also ensure that it is the only firewall configuration utility in use. This does not match with the SCA policy. 

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
[root@rhel9 vagrant]# rpm -q firewalld
firewalld-1.1.1-3.el9.noarch
[root@rhel9 vagrant]# rpm -q iptables
package iptables is not installed
[root@rhel9 vagrant]# rpm -q nftables
nftables-1.0.4-2.el9.x86_64
[root@rhel9 vagrant]# 
```

</details>


<details>

<summary> Alert </summary>

```
{"type":"check","id":940269994,"policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","policy_id":"cis_rhel9_linux","check":{"id":28075,"title":"Ensure nftables is installed.","description":"nftables provides a new in-kernel packet classification framework that is based on a network-specific Virtual Machine (VM) and a new nft userspace command line tool. nftables reuses the existing Netfilter subsystems such as the existing hook infrastructure, the connection tracking system, NAT, userspace queuing and logging subsystem.","rationale":"nftables is a subsystem of the Linux kernel that can protect against threats originating from within a corporate network to include malicious mobile code and poorly configured software on a host.","remediation":"Run the following command to install nftables # dnf install nftables.","compliance":{"cis":"3.4.1.1","cis_csc_v8":"4.4","cis_csc_v7":"9.4","nist_sp_800-53":"CA-9","iso_27001-2013":"A.13.1.1","cmmc_v2.0":"AC.L1-3.1.20,CM.L2-3.4.7,SC.L1-3.13.1,SC.L2-3.13.6","pci_dss_3.2.1":"1.1.4,1.3.1","pci_dss_4.0":"1.2.1,1.4.1","soc_2":"CC6.6","mitre_techniques":"T1562,T1562.004","mitre_tactics":"TA0011","mitre_mitigations":"M1031,M1037"},"rules":["c:rpm -q firewalld -> r:^package firewalld is not installed","c:rpm -q iptables -> r:^package iptables is not installed","c:rpm -q nftables -> r:^nftables-"],"condition":"all","command":"rpm -q firewalld","result":"failed"}}
```

</details>

</blockquote>

</details>





</details>


<details>

<summary> 3.4.1.2 :black_circle: </summary>

Not implemented. Expected due to SCA limitations

</details>


<details>

<summary> 3.4.2.1 :black_circle: </summary>

Not implemented. Expected due to SCA limitations

</details>


<details>

<summary> 3.4.2.2 :yellow_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :yellow_circle:

Expected:
```
Run the following command to create a table in nftables # nft create table inet <table name> Example if FirewallD is not in use on the system: # nft create table inet filter. Note: FirewallD uses the table inet firewalld NFTables table that is created when FirewallD is installed
```
Current:
```
Run the following command to create a table in nftables # nft create table inet <table name> Example: # nft create table inet filter. Note: FirewallD uses the table inet firewalld NFTables table that is created when FirewallD is installed
```

> Could be motivated by the same 3.4.1.1 check


- **Impact**: :green_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :black_circle:
- **Rules**: :yellow_circle:

In case of nftables is not installed in the system due to other utility is installed like firewalld this check will be marked as failed instead of not applicable. It this expected?

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
[root@rhel9 vagrant]# nft list tables
table inet firewalld
[root@rhel9 vagrant]# rpm -q nftables
nftables-1.0.4-2.el9.x86_64
```

</details>


<details>

<summary> Alert </summary>

```
{"type":"check","id":940269994,"policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","policy_id":"cis_rhel9_linux","check":{"id":28076,"title":"Ensure at least one nftables table exists.","description":"Tables hold chains. Each table only has one address family and only applies to packets of this family. Tables can have one of five families.","rationale":"Without a table, nftables will not filter network traffic.","remediation":"Run the following command to create a table in nftables # nft create table inet <table name> Example: # nft create table inet filter. Note: FirewallD uses the table inet firewalld NFTables table that is created when FirewallD is installed.","compliance":{"cis":"3.4.2.2","cis_csc_v8":"4.4","cis_csc_v7":"9.4","nist_sp_800-53":"CA-9","cmmc_v2.0":"AC.L1-3.1.20,CM.L2-3.4.7,SC.L1-3.13.1,SC.L2-3.13.6","pci_dss_3.2.1":"1.1.4,1.3.1","pci_dss_4.0":"1.2.1,1.4.1","soc_2":"CC6.6","iso_27001-2013":"A.13.1.1"},"rules":["c:nft list tables -> r:^table","c:rpm -q nftables -> r:^nftables-"],"condition":"all","command":"nft list tables,rpm -q nftables","result":"passed"}}
```

</details>

</blockquote>

</details>

</details>


<details>

<summary> 3.4.2.3 :red_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :green_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :black_circle:
- **Rules**: :red_circle:

- In case of nftables is not installed in the system due to other utility is installed like firewalld this check will be marked as failed instead of not applicable. It this expected?

- By consistency, use this rule instead
```
- "c:rpm -q nftables -> r:^nftables-"
```

- Rules do not take into account the scenario of using nat type instead of filter, marking as passed even if no type filter is configured
```
[root@rhel9 vagrant]# nft list ruleset | grep "hook output"
		type nat hook output priority -90; policy accept;
		type filter hook output priority filter + 10; policy accept
```

- CIS does not indicate specifically which priority should be used. However it is used in the remediation command priority 0.


<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
[root@rhel9 vagrant]# nft list ruleset
[root@rhel9 vagrant]# nft list ruleset | grep "hook input"
		type filter hook input priority filter + 10; policy accept;
[root@rhel9 vagrant]# nft list ruleset | grep "hook forward"
		type filter hook forward priority filter + 10; policy accept;
[root@rhel9 vagrant]# nft list ruleset | grep "hook output"
		type nat hook output priority -90; policy accept;
		type filter hook output priority filter + 10; policy accept;
[root@rhel9 vagrant]#
```

</details>


<details>

<summary> Alert </summary>

```
{"type":"check","id":940269994,"policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","policy_id":"cis_rhel9_linux","check":{"id":28077,"title":"Ensure nftables base chains exist.","description":"Chains are containers for rules. They exist in two kinds, base chains and regular chains. A base chain is an entry point for packets from the networking stack, a regular chain may be used as jump target and is used for better rule organization.","rationale":"If a base chain doesn't exist with a hook for input, forward, and delete, packets that would flow through those chains will not be touched by nftables.","remediation":"Run the following command to create the base chains: # nft create chain inet <table name> <base chain name> { type filter hook <(input|forward|output)> priority 0 \\; }. Example: # nft create chain inet filter input { type filter hook input priority 0 \\; } # nft create chain inet filter forward { type filter hook forward priority 0 \\; } # nft create chain inet filter output { type filter hook output priority 0 \\; }.","compliance":{"cis":"3.4.2.3","cis_csc_v8":"4.4","cis_csc_v7":"9.4","nist_sp_800-53":"CA-9","cmmc_v2.0":"AC.L1-3.1.20,CM.L2-3.4.7,SC.L1-3.13.1,SC.L2-3.13.6","pci_dss_3.2.1":"1.1.4,1.3.1","pci_dss_4.0":"1.2.1,1.4.1","soc_2":"CC6.6","iso_27001-2013":"A.13.1.1"},"rules":["c:rpm -q nftables -> r:nftables-","c:nft list ruleset -> r:hook input","c:nft list ruleset -> r:hook forward","c:nft list ruleset -> r:hook output"],"condition":"all","command":"rpm -q nftables,nft list ruleset","result":"passed"}}
```

</details>

</blockquote>

</details>

</details>



<details>

<summary> 3.4.2.4 :black_circle: </summary>

Not implemented. Expected due to SCA limitations

</details>

<details>

<summary> 3.4.2.5 :black_circle: </summary>

Not implemented. Expected due to it is a manual check

</details>

<details>

<summary> 3.4.2.6 :black_circle: </summary>

Not implemented. Expected due to it is a manual check

</details>


<details>

<summary> 3.4.2.4 :black_circle: </summary>

Not implemented. Expected due to it is a manual check

</details>


<details>

<summary> 3.4.2.7 :red_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :yellow_circle:

Expected 
```
If NFTables utility is in use on your system: 'Run the following command for the base chains with the input, forward, and output hooks to implement a default DROP policy: # nft chain <table family> <table name> <chain name> { policy drop \; } Example: # nft chain inet filter input { policy drop \; } # nft chain inet filter forward { policy drop \; } # nft chain inet filter output { policy drop \; }.
```
Current
```
Run the following command for the base chains with the input, forward, and output hooks to implement a default DROP policy: # nft chain <table family> <table name> <chain name> { policy drop \; } Example: # nft chain inet filter input { policy drop \; } # nft chain inet filter forward { policy drop \; } # nft chain inet filter output { policy drop \; }.
```

- **Impact**: :green_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

- In case of nftables is not installed in the system due to other utility is used like firewalld this check will be marked as failed instead of not applicable. It this expected? 
> "c:systemctl is-enabled nftables.service -> r:enabled"

- Base chains should contains a policy of drop, althought it is checked the opposite
> "not c:nft list ruleset -> r:policy drop"

Something like the following will do the job
```
- "c:nft list ruleset -> r:hook input\s*policy drop"
- "c:nft list ruleset -> r:hook forward\s*policy drop"
```


<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
[root@rhel9 vagrant]# nft list ruleset
[root@rhel9 vagrant]# nft list ruleset | grep "hook input"
		type filter hook input priority filter + 10; policy accept;
[root@rhel9 vagrant]# nft list ruleset | grep "hook forward"
		type filter hook forward priority filter + 10; policy accept;
[root@rhel9 vagrant]# nft list ruleset | grep "hook output"
		type nat hook output priority -90; policy accept;
		type filter hook output priority filter + 10; policy accept;
[root@rhel9 vagrant]#
```

</details>


<details>

<summary> Alert </summary>

```
{"type":"check","id":1643536875,"policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","policy_id":"cis_rhel9_linux","check":{"id":28078,"title":"Ensure nftables default deny firewall policy.","description":"Base chain policy is the default verdict that will be applied to packets reaching the end of the chain.","rationale":"There are two policies: accept (Default) and drop. If the policy is set to accept, the firewall will accept any packet that is not configured to be denied and the packet will continue traversing the network stack. It is easier to explicitly permit acceptable usage than to deny unacceptable usage. Note: Changing firewall settings while connected over the network can result in being locked out of the system.","remediation":"Run the following command for the base chains with the input, forward, and output hooks to implement a default DROP policy: # nft chain <table family> <table name> <chain name> { policy drop \\; } Example: # nft chain inet filter input { policy drop \\; } # nft chain inet filter forward { policy drop \\; } # nft chain inet filter output { policy drop \\; }.","compliance":{"cis":"3.4.2.7","cis_csc_v8":"4.4","cis_csc_v7":"9.4","nist_sp_800-53":"CA-9","cmmc_v2.0":"AC.L1-3.1.20,CM.L2-3.4.7,SC.L1-3.13.1,SC.L2-3.13.6","pci_dss_3.2.1":"1.1.4,1.3.1","pci_dss_4.0":"1.2.1,1.4.1","soc_2":"CC6.6","iso_27001-2013":"A.13.1.1"},"rules":["c:systemctl is-enabled nftables.service -> r:enabled","c:nft list ruleset -> r:hook input","c:nft list ruleset -> r:hook forward","not c:nft list ruleset -> r:policy drop"],"condition":"all","command":"systemctl is-enabled nftables.service,nft list ruleset","result":"passed"}}
```


</details>

</blockquote>

</details>

</details>

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3819#issuecomment-1453492788

3.4.1.1 🟡 -  This is expected

3.4.2.2 🟡
  - Remediation - Solved
  - Rules - This is expected

3.4.2.3 🔴 
  - Failure is expected if this is not working
  - This is solved for uniformity (r:^nftables-)
  - We are looking for table, not for filter
  - CIS does not indicate specifically which priority should be used - We are just looking for the table, not for any other parameter

3.4.2.7 🔴
  - Remediation - Solved
  - Rules: 
     - It this expected? - Yes, this is expected
     - Base chains should contains a policy of drop, although it is checked the opposite - Solved

https://github.com/wazuh/wazuh/commit/c181131e092b4196e37cf6cf7bf3cdb610427f74

**Comment by Rebits** [comment]
## Testing results - Second review


<details>

<summary> 3.4.1.1 :green_circle: </summary>

- **Rules**: Accepted in favor of policy clarity and consistency

</details>


<details>

<summary> 3.4.2.2 :green_circle: </summary>


- **Rules**: Accepted in favor of policy clarity and consistency
- **Remediation**: :green_circle:


</details>



<details>

<summary> 3.4.2.3 :green_circle: </summary>

- **Rules**: :green_circle:: Now the rule work as expected taking into account the nat hook type.

Alert:
```
{"type":"check","id":940269994,"policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","policy_id":"cis_rhel9_linux","check":{"id":28077,"title":"Ensure nftables base chains exist.","description":"Chains are containers for rules. They exist in two kinds, base chains and regular chains. A base chain is an entry point for packets from the networking stack, a regular chain may be used as jump target and is used for better rule organization.","rationale":"If a base chain doesn't exist with a hook for input, forward, and delete, packets that would flow through those chains will not be touched by nftables.","remediation":"Run the following command to create the base chains: # nft create chain inet <table name> <base chain name> { type filter hook <(input|forward|output)> priority 0 \\; }. Example: # nft create chain inet filter input { type filter hook input priority 0 \\; } # nft create chain inet filter forward { type filter hook forward priority 0 \\; } # nft create chain inet filter output { type filter hook output priority 0 \\; }.","compliance":{"cis":"3.4.2.3","cis_csc_v8":"4.4","cis_csc_v7":"9.4","nist_sp_800-53":"CA-9","cmmc_v2.0":"AC.L1-3.1.20,CM.L2-3.4.7,SC.L1-3.13.1,SC.L2-3.13.6","pci_dss_3.2.1":"1.1.4,1.3.1","pci_dss_4.0":"1.2.1,1.4.1","soc_2":"CC6.6","iso_27001-2013":"A.13.1.1"},"rules":["c:rpm -q nftables -> r:nftables-","c:nft list ruleset -> r:hook input","c:nft list ruleset -> r:hook forward","c:nft list ruleset -> r:hook output"],"condition":"all","command":"rpm -q nftables,nft list ruleset","result":"passed"}}
```

**Command output**
```
[root@rhel9 vagrant]# nft list ruleset | grep "filter hook"
		type filter hook prerouting priority mangle + 10; policy accept;
		type filter hook prerouting priority filter + 10; policy accept;
		type filter hook input priority filter + 10; policy accept;
		type filter hook forward priority filter + 10; policy accept;
		type filter hook output priority filter + 10; policy accept;
```


</details>




<details>

<summary> 3.4.2.7 :green_circle: </summary>

- **Remediation**: :green_circle: 
Accepted in favor of consistency of the policy.

- **Rules**: :green_circle:

Now,  the check fails as expected:
```
{"type":"check","id":940269994,"policy":"CIS Benchmark for Red Hat Enterprise Linux 9.","policy_id":"cis_rhel9_linux","check":{"id":28083,"title":"Ensure audit logs are not automatically deleted.","description":"The max_log_file_action setting determines how to handle the audit log file reaching the max file size. A value of keep_logs will rotate the logs but never delete old logs.","rationale":"In high security contexts, the benefits of maintaining a long audit history exceed the cost of storing the audit history.","remediation":"Set the following parameter in /etc/audit/auditd.conf: max_log_file_action = keep_logs.","compliance":{"cis":"4.1.2.2","cis_csc_v8":"8.3","cis_csc_v7":"6.4","nist_sp_800-53":"AU-8","iso_27001-2013":"A.12.4.1","pci_dss_3.2.1":"10.7","soc_2":"A1.1","mitre_techniques":"T1562,T1562.006","mitre_tactics":"TA0005"},"rules":["f:/etc/audit/auditd.conf -> r:^\\s*max_log_file_action\\s*=\\s*keep_logs"],"condition":"all","file":"/etc/audit/auditd.conf","result":"failed"}}
```

**Command output**:
```
[root@rhel9 vagrant]# nft list ruleset | grep "hook forward"
		type filter hook forward priority filter + 10; policy accept;
[root@rhel9 vagrant]# nft list ruleset | grep "hook input"
		type filter hook input priority filter + 10; policy accept;
[root@rhel9 vagrant]# 
```



</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

The suggested changes have been applied and everything appears to be correct.

**Comment by Rebits** [comment]
## Testing result - Fourth review


| PR Commit |
| --- |
| https://github.com/wazuh/wazuh/commit/24405eb600b03d6556fea30d7d4a9dd45f74df1a | 


After the development of a PDF policy parser and a compliance mapping tool, it has been detected some new unexpected values:

***

<details>

<summary> 3.4.2.3 :red_circle: </summary>

**Remediation**:  Missing example.

Expected:
```
If NFTables utility is in use on your system: Run the following command to create the base chains: # nft create chain inet <table name> <base chain name> { type filter hook <(input|forward|output)> priority 0 \; } Example: # nft create chain inet filter input { type filter hook input priority 0 \; } # nft create chain inet filter forward { type filter hook forward priority 0 \; } # nft create chain inet filter output { type filter hook output priority 0 \; }.
```

</details>



<details>

<summary> 3.4.2.7 :red_circle:</summary>

**Remediation**: Missing last example

```
Example: # nft chain inet filter input { policy drop \; } # nft chain inet filter forward { policy drop \; } # nft chain inet filter output { policy drop \; }
```

</details>

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3819#issuecomment-1462452915

3.4.2.3 🔴 - Solved
3.4.2.7 🔴 - Solved

**Comment by Rebits** [comment]
## Testing result - Fourth review


| PR Commit |
| --- |
| https://github.com/wazuh/wazuh/commit/7f4e24311e64fcae337eb33914c74d644b21df2f | 

***

<details>

<summary> 3.4.2.3 :green_circle: </summary>

**Remediation**: :green_circle: 

</details>


<details>

<summary> 3.4.2.7 :green_circle: </summary>

**Remediation**: :green_circle: 

</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

The suggested changes have been applied and everything appears to be correct.
