### ISSUE TITLE
macOS Ventura SCA policy - check 3 to 5.2.8

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3853]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |       #3850      |      https://github.com/wazuh/wazuh/pull/16027|

|Check Id and Name| Status| Extra|
|---|---|---|
|3 Logging and Auditing|||
|3.1 Ensure Security Auditing Is Enabled (Automated)|||
|3.2 Ensure Security Auditing Flags For User-Attributable Events Are Configured Per Local Organizational Requirements (Automated)|||
|3.3 Ensure install.log Is Retained for 365 or More Days and No Maximum Size (Automated)|||
|3.4 Ensure Security Auditing Retention Is Enabled (Automated)|||
|3.5 Ensure Access to Audit Records Is Controlled (Automated)|||
|3.6 Ensure Firewall Logging Is Enabled and Configured (Automated)|||
|3.7 Audit Software Inventory (Manual)|||
||||
|4 Network Configurations|||
|4.1 Ensure Bonjour Advertising Services Is Disabled (Automated)|||
|4.2 Ensure HTTP Server Is Disabled (Automated)|||
|4.3 Ensure NFS Server Is Disabled (Automated)|||
||||
|5 System Access, Authentication and Authorization|||
|5.1 File System Permissions and Access Controls|||
|5.1.1 Ensure Home Folders Are Secure (Automated)|||
|5.1.2 Ensure System Integrity Protection Status (SIP) Is Enabled (Automated)|||
|5.1.3 Ensure Apple Mobile File Integrity (AMFI) Is Enabled (Automated)|||
|5.1.4 Ensure Sealed System Volume (SSV) Is Enabled (Automated)|||
|5.1.5 Ensure Appropriate Permissions Are Enabled for System Wide Applications (Automated)|||
|5.1.6 Ensure No World Writable Files Exist in the System Folder (Automated)|||
|5.1.7 Ensure No World Writable Files Exist in the Library Folder (Automated)|||
||||
|5.2 Password Management|||
|5.2.1 Ensure Password Account Lockout Threshold Is Configured (Automated)|||
|5.2.2 Ensure Password Minimum Length Is Configured (Automated)|||
|5.2.3 Ensure Complex Password Must Contain Alphabetic Characters Is Configured (Manual)|||
|5.2.4 Ensure Complex Password Must Contain Numeric Character Is Configured (Manual)|||
|5.2.5 Ensure Complex Password Must Contain Special Character Is Configured (Manual)|||
|5.2.6 Ensure Complex Password Must Contain Uppercase and Lowercase Characters Is Configured (Manual)|||
|5.2.7 Ensure Password Age Is Configured (Automated)|||
|5.2.8 Ensure Password History Is Configured (Automated)|||

**Comment by Rebits** [comment]
### Testing environment

| OS     | OS version | Deployment | Image/AMI | Notes |
| ------ | ---------- | ---------- | --------- | ----- |
| macOS  | Ventura    | Local      |           |       |
| ubuntu | 20         | Vagrant    | -         |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` |
| --------------- | ------------- |
|  [4.4.1](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.4.1-1_amd64.deb)               |  [4.4.1](https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.1-1.pkg)             |

> **Note** 
> macOS Ventura sca policy will be included manually in the agent. The development package will be used for the final validation


### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@juliamagan )
- [ ] Development team leader approved (@72nomada )

**Comment by Rebits** [comment]
## Testing results :large_blue_circle:

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16027/commits/d0692b70b4f8e68b2b07c19de04653716c817e15 | 

***

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh-qa/issues/3853#issuecomment-1508289568

3.3 🔴
3.4 🔵 

https://github.com/wazuh/wazuh/pull/16027/commits/630c98471440b9428afab1a7eef10036bda872eb

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh-qa/issues/3853#issuecomment-1508289568

4.2 🔴 - Resolved
4.3 🔴 - Resolved
5.1.1 🔴 - Resolved
5.1.3 🔴 - Resolved
5.2.3 🔴 - Resolved
5.2.4 🔴 - Resolved
5.2.5 🔴 - Cannot be implemented
5.2.6 🔴 - Resolved
5.2.7 🔴 - Resolved

https://github.com/wazuh/wazuh/commit/fe32c21d2a8194143b502be0eebb6e33c5b0daee

**Comment by Rebits** [comment]
## Testing results :green_circle:

| Tester | PR commit               |
|--------|-------------------------| 
| @Rebits| https://github.com/wazuh/wazuh/pull/16027/commits/0933eabc74fe89a053b188f1c5cd3eefd2c63ec7 | 


***



<details>

<summary> 3.3 :green_circle: </summary>

- **Rules**: :green_circle:

```
sh-3.2# cat /etc/asl/com.apple.install
# install messages get saved only in /var/log/install.log
? [= Facility install] claim only
* file /var/log/install.log format='$((Time)(JZ)) $Host $(Sender)[$(PID)]: $Message' rotate=seq compress file_max=50M all_max=150M size_only
```

```

2023/04/18 15:40:29 sca[26495] wm_sca.c:1909 at wm_sca_pattern_matches(): DEBUG: Testing minterm (/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent)(grep 31062) -> 0
2023/04/18 15:40:29 sca[26495] wm_sca.c:1912 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent)(grep 31062) -> 0
2023/04/18 15:40:30 sca[26495] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31062 'Ensure install.log Is Retained for 365 or More Days and No Maximum Size.'
2023/04/18 15:40:30 sca[26495] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31062 'Ensure install.log Is Retained for 365 or More Days and No Maximum Size.' -> 0
```

</details>




<details>

<summary> 3.4 :green_circle: </summary>


**Rules**: :green_circle:

```
sh-3.2# cat /etc/security/audit_control
#
# $P4: //depot/projects/trustedbsd/openbsm/etc/audit_control#8 $
#
dir:/var/audit
flags:lo,aa
minfree:5
naflags:lo,aa
policy:cnt,argv
filesz:2M
expire-after: 1d OR 5G
superuser-set-sflags-mask:has_authenticated,has_console_access
superuser-clear-sflags-mask:has_authenticated,has_console_access
member-set-sflags-mask:
member-clear-sflags-mask:has_authenticated
```

***

```
sh-3.2# pkill modulesd; /Library/Ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['  | grep 31063
2023/04/18 15:51:47 sca[27512] wm_sca.c:1909 at wm_sca_pattern_matches(): DEBUG: Testing minterm (/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent)(grep 31063) -> 0
2023/04/18 15:51:47 sca[27512] wm_sca.c:1912 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent)(grep 31063) -> 0
2023/04/18 15:51:48 sca[27512] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31063 'Ensure Security Auditing Retention Is Enabled.'
```


</details>






<details>

<summary> 4.2 :green_circle: </summary>

**Rules**: :green_circle:

```
sh-3.2# launchctl list
...
156	0	com.apple.corebrightnessd
-	0	com.apple.tailspind
```


```
2023/04/18 15:53:52 sca[28490] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31068 'Ensure HTTP Server Is Disabled.'
2023/04/18 15:53:52 sca[28490] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31068 'Ensure HTTP Server Is Disabled.' -> 1
```


</details>



<details>

<summary> 4.3  :green_circle: </summary>

- **Rules**: green_circle:

```
2023/04/18 15:55:56 sca[28539] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31069 'Ensure NFS Server Is Disabled.'
2023/04/18 15:55:56 sca[28539] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31069 'Ensure NFS Server Is Disabled.' -> 0
```



</details>




<details>

<summary> 5.1.1 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
sh-3.2# sh -c "ls -l /Users | grep -v total" 
-rw-r--r--   1 root     wheel    0  2 dic 12:37 .localized
drwxrwxrwt   6 root     wheel  192 21 mar 19:28 Shared
...
sh-3.2# 
```

</details>


<details>

<summary> Alert </summary>

```
sh-3.2# pkill modulesd; /Library/Ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['  | grep 31070
2023/04/18 16:01:57 sca[28600] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31070 'Ensure Home Folders Are Secure.'
2023/04/18 16:01:57 sca[28600] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31070 'Ensure Home Folders Are Secure.' -> 0
```

</details>

</blockquote>

</details>

</details>




<details>

<summary> 5.1.3 :green_circle: </summary>


- **Rules** :green_circle:

```
sh-3.2# nvram -p | grep -c "amfi"
0
sh-3.2# 
```


```
2023/04/18 16:03:43 sca[28646] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31072 'Ensure Apple Mobile File Integrity (AMFI) Is Enabled.'
2023/04/18 16:03:43 sca[28646] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31072 'Ensure Apple Mobile File Integrity (AMFI) Is Enabled.' -> 1
```


</details>


<details>

<summary> 5.2.3 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
sh-3.2# pwpolicy -getaccountpolicies | grep "minimum"
				<string>Introduceți o parolă de minimum patru caractere sau lăsați gol câmpul pentru parolă.</string>
```


</details>


<details>

<summary> Alert </summary>

```
2023/04/18 16:14:26 sca[28733] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31079 'Ensure Complex Password Must Contain Alphabetic Characters Is Configured.'
2023/04/18 16:14:26 sca[28733] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31079 'Ensure Complex Password Must Contain Alphabetic Characters Is Configured.' -> 0

```


After remediation
```
2023/04/18 16:15:32 sca[28779] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31079 'Ensure Complex Password Must Contain Alphabetic Characters Is Configured.'
2023/04/18 16:15:32 sca[28779] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31079 'Ensure Complex Password Must Contain Alphabetic Characters Is Configured.' -> 1

```

</details>

</blockquote>

</details>

</details>


<details>

<summary> 5.3.4 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
sh-3.2# sh  -c "pwpolicy -getaccountpolicies | grep -A1 minimumNumericCharacters " 
sh-3.2# 
```

</details>


<details>

<summary> Alert </summary>


```
2023/04/18 16:26:43 sca[29800] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31080 'Ensure Complex Password Must Contain Numeric Character Is Configured.'
2023/04/18 16:26:43 sca[29800] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31080 'Ensure Complex Password Must Contain Numeric Character Is Configured.' -> 0
2023/04/18 16:26:43 sca[29800] wm_sca.c:2820 at wm_sca_hash_integrity(): DEBUG: ID: 31080; Result: 'failed'
```

After remediation

```
sh-3.2# /usr/bin/sudo /usr/bin/pwpolicy -n /Local/Default -setglobalpolicy "requiresNumeric=2"
sh-3.2# pkill modulesd; /Library/Ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['  | grep 31080
2023/04/18 16:27:58 sca[31030] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31080 'Ensure Complex Password Must Contain Numeric Character Is Configured.'
2023/04/18 16:27:58 sca[31030] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31080 'Ensure Complex Password Must Contain Numeric Character Is Configured.' -> 1
```

</details>

</blockquote>

</details>

</details>


<details>

<summary> 5.2.5  :black_circle:</summary>

Not implemented. Expected due to SCA limitations

</details>


<details>

<summary> 5.2.6 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
  - **CIS ID**: :green_circle:
  - **CSC**: :green_circle:
  - **ISO**: :green_circle:
  - **CMMC**: :green_circle:
  - **SOC**: :green_circle:
  - **NIST**: :green_circle:
  - **PCI**: :green_circle:
  - **MITRE**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

<details>

<summary> Rules details </summary>

<blockquote>


<details>

<summary> Command output </summary>

```
sh-3.2# pwpolicy -getaccountpolicies | grep minimum
				<string>Introduceți o parolă de minimum patru caractere sau lăsați gol câmpul pentru parolă.</string>
				<string>No minimum number of letters</string>
				<string>Pas de nombre minimum de lettres</string>
				<string>Pas de nombre minimum de lettres</string>
				<string>Tidak ada jumlah minimum huruf</string>
				<string>Tiada bilangan minimum untuk huruf</string>
				<key>minimumLetters</key>
				<key>minimumNumericCharacters</key>
sh-3.2# 
```

</details>


<details>

<summary> Alert </summary>

```
2023/04/18 16:30:49 sca[32282] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31082 'Ensure Complex Password Must Contain Uppercase and Lowercase Characters Is Configured.'
2023/04/18 16:30:49 sca[32282] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31082 'Ensure Complex Password Must Contain Uppercase and Lowercase Characters Is Configured.' -> 0
```


After remediation
```
sh-3.2# pkill modulesd; /Library/Ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['   | grep 31082
2023/04/18 16:31:31 sca[32326] wm_sca.c:1000 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 31082 'Ensure Complex Password Must Contain Uppercase and Lowercase Characters Is Configured.'
2023/04/18 16:31:31 sca[32326] wm_sca.c:1255 at wm_sca_do_scan(): DEBUG: Result for check id: 31082 'Ensure Complex Password Must Contain Uppercase and Lowercase Characters Is Configured.' -> 1

```


</details>

</blockquote>

</details>

</details>



<details>

<summary> 5.2.7 :green_circle:</summary>

**Compliance**: :green_circle:

</details>

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly
