### ISSUE TITLE
Wazuh-metrics not finding wazuh_clusterd service

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#3940]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
| - | - | - |

## Description
When the `wazuh-clusterd` service was renamed to `wazuh_clusterd` in https://github.com/wazuh/wazuh/issues/12838, some QA tools were affected. One of them is wazuh-metrics, which is still looking for the old name:
```
wazuh-metrics -p wazuh-db wazuh-apid wazuh_clusterd -v 4.4.0 -s 5 -u KB --store /tmp/binaries/
Traceback (most recent call last):
  File "/usr/local/bin/wazuh-metrics", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wazuh_testing/scripts/wazuh_metrics.py", line 131, in main
    for i, pid in enumerate(Monitor.get_process_pids(process)):
  File "/usr/local/lib/python3.8/dist-packages/wazuh_testing/tools/performance/binary.py", line 85, in get_process_pids
    raise ValueError(f'The process {process_name} is not running')
ValueError: The process wazuh_clusterd is not running
```

It should be renamed here for it to work properly:
https://github.com/wazuh/wazuh-qa/blob/d4b613598df5133ee8d9a414a96461e1461d2434/deps/wazuh_testing/wazuh_testing/tools/performance/binary.py#L77-L80

**Comment by jmv74211** [comment]
Reviewing the proposed change, I noticed that in the `wazuh-qa` repository there are many calls to `wazuh-clusterd`. For example https://github.com/wazuh/wazuh-qa/blob/ca13918a9cf69ea93b111ccefcfda215e7865627/deps/wazuh_testing/wazuh_testing/tools/services.py#L117

It is necessary to do a deep research about all necessary changes, taking into account the following:
- The `clusterd` binary is named `wazuh-clusterd` although underneath the script is called from `wazuh_clusterd`.
- If we check the wazuh processes, clusterd will appear as `wazuh_clusterd`.
- If we check, call... the wazuh binary, we need to call it as `wazuh-clusterd`.

**Comment by Rebits** [comment]
Regarding the rename of cluster daemon implications in the QA framework:

### Service module  

**Control Service**

The service module it is not affected by this rename. The `wazuh-cluster` daemon is stopped correctly due to the control_service function uses the name of the PID files in the `/var/run` directory.
However, it detected an error not related to the rename at wazuh-cluster restart time.
```
usage: wazuh_clusterd.py [-h] [--ssl] [-f] [-d] [-V] [-r] [-t] [-c config]
wazuh_clusterd.py: error: unrecognized arguments: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qa/wazuh-qa/deps/wazuh_testing/wazuh_testing/tools/services.py", line 142, in control_service
    subprocess.check_call([f'{daemon_path}/{daemon}', '' if not debug_mode else '-dd'])
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/ossec/bin/wazuh-clusterd', '']' returned non-zero exit status 2.
```

**Check daemon status**
This function uses the output of the `wazuh-control` binary, in which it still used `wazuh-cluster`, so it is not affected.


### IT 

Some tests reference `wazuh-clusterd` (eg. `test_analysisd/test_event_messages/test_event_messages.py` ). All of them define a necessary attribute for `monitored_sockets_params` function. However, this one makes use of the `control_service` and `check_daemon_status`, reviewed in the last section.

### Performance tool
As @Selutario , notice it would be necessary to rename the cluster daemon in the binary module
