### ISSUE TITLE
Run a Coverity scan as part of the weekly build

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#4239]
## Description

Currently, we're running Coverity manually as a subtask of the release testing, and weekly (example: https://github.com/wazuh/wazuh/issues/17597). It would be highly desirable that the weekly tests launch a scan.

### Current behavior

We run a Coverity scan manually.

### Expected behavior

Weekly run to run a Coverity scan automatically (as much as possible).

**Comment by Rebits** [comment]
### 16/06/2023

- Researched current Jenkins libraries and images for automating coverity scan.

**Comment by Rebits** [comment]
### 19/06/2023
- Research about coverity scan CLI capabilities
- Research about coverity scan reports
- Research about current use of the coverity scan script ( ty to @vikman90 for the information)
- Created new coverity script to be used in Jenkins pipeline
- Created Dockerfile for coverity scan

**Comment by Rebits** [comment]
### 20/06/2023

- Research about current bug in coverity scan were no report is sent though email. No solution for this situation for now. Feedback provided from @vikman90 
- Created ECR for coverity scan
- Created basic pipeline for coverity_scan automation.
- Blocked for now due to lack of permissions

**Comment by davidjiglesias** [comment]
Latest investigations show this is not doable as of right now.
