### ISSUE TITLE
Investigate and document tests - Test_unit

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#4262]
|||
|-----|----|
| Parent issue |https://github.com/wazuh/wazuh-qa/issues/4241|
| Pipeline state | ❗ |
| Tests state | 🟡 |
| Jenkins link | https://ci.wazuh.info/job/Test_unit/ |
| Branch used | 4.4 |

## Description 

This issue aims to analyze and document all about the Unit tests. Jenkins parameters, pytest location, steps in the test, and current state of it. Also, manual execution is required.

## State of `Test_unit` pipeline ❗

The `Test_unit` pipeline is executed in the daily development tasks (when a new change is introduced to the sources, in the **PR_wazuh** pipeline, or in the **Nightly** pipeline).

- There is a target that is not being used, called `libcheck`, so it should be removed as a "target" option.

## State of each test run by the pipeline 🟡

- All the unit tests pass successfully.
- Some warnings are shown in the results of Pytest, they should be checked by the Framework Team which has the ownership of those tests. There is an issue opened by the team: https://github.com/wazuh/wazuh/issues/13267

**Comment by mauromalara** [comment]
# Test_unit

| Pipeline | Tests |
|--------|--------|
| ⚫ | ⚫ | 

## Parameters

- TARGET: Type of test to run
- COMPONENT: Target component to be tested
- SOURCE_REFERENCE: Wazuh source branch that will be tested.
- DESTROY_INSTANCES: Define whether to destroy or not the instances used to run the tests
- VERBOSITY
- CHECKRUN_REFERENCE
- JENKINS_REFERENCE: Jenkins source branch that will be used to run the tests
- CREDENTIALS: Credentials to be used during the execution
- CUSTOM_TASK_DEFINITION

## Execution

### Status

WIP.

**Comment by fcaffieri** [comment]
## Review notes

> There is a target that is not being used, called libcheck, so it should be removed as a "target" option.

Good catch. If you set the target to `libcheck` the pipeline throws an exception:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/95df5123-c428-4aca-8c21-a3a849e56115)

So we need to remove it from Jenkins UI.

### Parameters

> CHECKRUN_REFERENCE

We need to set a description.

> JENKINS_REFERENCE: Jenkins source branch that will be used to run the tests

Jenkins != wazuh-jenkins, if referring to a repository branch, the name of the repository must be used.

### Steps

I do not see the list and description of the steps.

### Test

> Some warnings are shown in the results of Pytest, they should be checked by the Framework Team which has the ownership of those tests.

We have an issue for Framework Team in order for them to analyze the warnings? Please link the issue here.


---

### Notes 

We can use this issue to complete the Jenkins documentation. https://github.com/wazuh/wazuh-jenkins/issues/5360

**Comment by mauromalara** [comment]
@fcaffieri thank you for the review.

> **Steps**
> I do not see the list and description of the steps.

What do you mean by this? Do you mean a step-by-step of each unit test? or a step-by-step of the pipeline? Do you think this is useful for the documentation? I think that the code itself should explain this. But, let me know what you mean by "steps".

**Comment by fcaffieri** [comment]
After talking with @mauromalara, we decided that it is not necessary to include the steps because reviewing the structure of the tests corresponds to the Core and Framework teams.

**Comment by davidjiglesias** [comment]
LGTM!
