### ISSUE TITLE
Agentd tests fail on Windows Agents

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4403]
### Description

It has been detected in https://github.com/wazuh/wazuh/issues/18286 that the integration tests `test_agentd\test_agentd_state` and `test_agentd\test_agentd_parametrized_reconnections` fail consistently.

It seems that connection to the manager mocked manager is taking to long as in both tests the expected `Trying to connect to server` event is not detected.

### Evidences

- **Report**: [agent_windows_html_report_Test_integration_B42125_20230807202942.zip](https://github.com/wazuh/wazuh-qa/files/12285601/agent_windows_html_report_Test_integration_B42125_20230807202942.zip)
- **Build**: https://ci.wazuh.info/job/Test_integration/42125/

**Comment by nmkoremblum** [comment]
We will temporarily place this issue on hold in favor of issue [#6284](https://github.com/wazuh/wazuh-documentation/issues/6284) which has a higher priority. Once the [#6284](https://github.com/wazuh/wazuh-documentation/issues/6284)  is resolved, we will resume our focus on this issue.

**Comment by nbertoldo** [comment]
I leave the reports that complement the tests to which @LucioDonda Lucio refers above.

[Report_IT_agentd_1.zip](https://github.com/wazuh/wazuh-qa/files/12352497/Report_IT_agentd_1.zip)
[Report_IT_agentd_2.zip](https://github.com/wazuh/wazuh-qa/files/12352498/Report_IT_agentd_2.zip)
[Report_IT_agentd_3.zip](https://github.com/wazuh/wazuh-qa/files/12352500/Report_IT_agentd_3.zip)

**Comment by vikman90** [comment]
Removing from 4.5.1 and setting the objective to _high impact bugs_.

**Comment by JorgeMarinoDev** [comment]
Either these enrollment tests started failing from version 4.5.1 onwards, or they have begun to be reported from this point and even in later versions such as 4.7.0 onwards,

1. Several attempts were made to reproduce this. No success.
2. Are we sure that it's possible to expect "Connection attempts took too much!" under normal conditions? Besides setting the enrollment retry count or timeouts, I think "Connection attempts took too much!" is related to a poor link to the manager, hard to emulate unless we include a packet loss rate in the test pipeline.
3. We must define a clear criteria to consider this issue closed. Otherwise this issue will be dragged ad infinitum as Known Bug in later tests.
4. We have this [issue](https://github.com/wazuh/wazuh-jenkins/issues/5930) where we must make sure that Jenkin's conditions will produce deterministic results,

@vikman90 Could you please bring some light on this? Thank you.

**Comment by TomasTurina** [comment]
Solved as part of the migration: https://github.com/wazuh/wazuh/issues/19088
