### ISSUE TITLE
Automate Puppet E2E test

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#4430]
## Description
The E2E test execution time can be improved by using automation tools like vagrant.

### Current behavior
There's no automation tool that help reduce the execution time.

### Expected behavior
Partially/complete automation, reducing the execution time.

**Comment by mhamra** [comment]
### UPDATE

I've created a baseline environment provisioning script with Vagrant to deploy VMs. I've tested it with Virtual Box. 

[e2ePuppet.zip](https://github.com/wazuh/wazuh-qa/files/12363329/e2ePuppet.zip)

**Comment by Selutario** [comment]
The goal of E2E is to follow the documentation just as users would to identify the parts that don't work or are confusing. This is also why we test parts of Wazuh that we are not involved in developing.

I'm closing the issue since it doesn't make sense to automate part of the process, it's just intended to be done manually.
