### ISSUE TITLE
Logcollector integration tests are failing

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#4564]
## Description

- Version: 4.7.1 (development)
- PR showing this: https://github.com/wazuh/wazuh/pull/19290
- PR check: https://ci.wazuh.info/job/Test_integration/43327

### Current behavior

The test produces this result: https://github.com/wazuh/wazuh/pull/19290/checks?check_run_id=17209620138

[logcollector.txt](https://github.com/wazuh/wazuh-qa/files/12748331/logcollector.txt)

### Expected behavior

We expect this test to pass in branch 4.7.0.

**Comment by JorgeMarinoDev** [comment]
**Results**

![image](https://github.com/wazuh/wazuh-qa/assets/117848458/68222819-3260-4452-aea7-d8f73342523e)

[Jenkins Job](https://ci.wazuh.info/view/Tests/job/Test_integration/44671/)

[Test Report](https://github.com/wazuh/wazuh-qa/files/13356951/agent_windows_html_report_Test_integration_B44671_20231114201651.zip)

[Windows Logcollector test results txt](https://github.com/wazuh/wazuh-qa/files/13356953/windows_agent_tests_Test_integration_B44671_20231114201651.txt)

**Conclusions**

Test have passed in 4.7.0.
Probably PR checks were failing after merge due to target branch instead.
Making sure pass in 4.7.0. OK
