### ISSUE TITLE
Agentd integration tests are failing

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#4565]
## Description

- Version: 4.7.1 (development)
- PR showing this: https://github.com/wazuh/wazuh/pull/19290
- PR check: https://ci.wazuh.info/job/Test_integration/43329

### Current behavior

The test produces this result: https://github.com/wazuh/wazuh/pull/19290/checks?check_run_id=17209688374

[agentd.txt](https://github.com/wazuh/wazuh-qa/files/12748393/agentd.txt)

### Expected behavior

We expect this test to pass in branch 4.7.0.

**Comment by JorgeMarinoDev** [comment]
Just a brief status update on this.

1. [PR Check 43329](https://ci.wazuh.info/job/Test_integration/43329) It had been deleted from Jenkins. Missing context to analyze.
2. This check was triggered after merging to 4.7.1. We have tried to execute agentd integration tests on Windows Agent but 4.7.1 packages are not present in pre-release or warehouse repos. Disregard.
3. Since the Expected behavior requires this test to pass in 4.7.0, we have triggered a new [Test Job](https://ci.wazuh.info/view/Tests/job/Test_integration/44668). Expecting results to continue research.

**Comment by JorgeMarinoDev** [comment]
**Test Results**

![image](https://github.com/wazuh/wazuh-qa/assets/117848458/a0c88d53-a674-4bb1-9585-aadeebcec969)

[Jenkins Job 44669](https://ci.wazuh.info/view/Tests/job/Test_integration/44669/)

![image](https://github.com/wazuh/wazuh-qa/assets/117848458/7741a110-b4fa-4bb6-89db-b4af0f99e2ae)

[Test Report HTML](https://github.com/wazuh/wazuh-qa/files/13354600/agent_windows_html_report_Test_integration_B44669_20231114185029.zip)
[Windows Agents Report txt](https://github.com/wazuh/wazuh-qa/files/13354647/windows_agent_tests_Test_integration_B44669_20231114185029.txt)

**Comment by cborla** [comment]
LGTM!
