### ISSUE TITLE
Agentd scanning IT: Connection issues to a Windows host and the inability to calculate the checksum of a remote file needed for generating logs

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#4732]
### Description

It has been detected in https://github.com/wazuh/wazuh/issues/20479 where Testing Agentd integration in Windows Agent, the following connection error were found:

```
15:33:28  TASK [Launch windows pytests] **************************************************
15:33:28  task path: /home/ec2-user/workspace/Test_integration@2/quality/tests/integration/test_integration.yaml:37
15:33:28  fatal: [ID2_B45032_Test_integration_windows_agent]: FAILED! => {}
15:33:28  
15:33:28  MSG:
15:33:28  
15:33:28  ssl: 
15:33:28  Using module file /usr/local/lib/python3.7/site-packages/ansible/modules/windows/win_stat.ps1
15:33:28  Pipelining is enabled.
15:33:28  <172.31.6.205> ESTABLISH WINRM CONNECTION FOR USER: Jenkins on PORT 5986 TO 172.31.6.205
15:33:48  
15:33:48  TASK [Generate stdout txt logs for Windows] ************************************
15:33:48  task path: /home/ec2-user/workspace/Test_integration@2/quality/tests/integration/test_integration.yaml:74
15:33:48  fatal: [ID2_B45032_Test_integration_windows_agent]: FAILED! => {
15:33:48      "changed": false,
15:33:48      "file": "C:\\tmp\\Test_integration_B45032_20231128151317\\pytest_plain_report.txt"
15:33:48  }
15:33:48  
15:33:48  MSG:
15:33:48  
15:33:48  unable to calculate the checksum of the remote file
15:33:48  
15:33:48  PLAY RECAP *********************************************************************
15:33:48  ID2_B45032_Test_integration_windows_agent : ok=0    changed=0    unreachable=0    failed=2    skipped=3    rescued=0    ignored=0 
```

### Evidences

- **Build**: https://ci.wazuh.info/job/Test_integration/45032/

**Comment by fcaffieri** [comment]
## Update

The two errors reported in the issue were investigated. The second error `15:33:48 unable to calculate the checksum of the remote file` occurs as a consequence of the first. This error occurs when you try to make a copy of a file with ansible which does not exist or is empty since it tries to calculate the checksum and cannot. At this point, the feasibility of incorporating a validation of the existence of the file to avoid the error and handle it can be analyzed.
The first error, which does not show much detail, was due to a connectivity problem with the Windows agent. This is a known issue where this type of connection problem is recurring. This [issue](https://github.com/wazuh/wazuh-jenkins/issues/6038) was generated to correct connectivity problems against Windows, but it is not a stopper to 4.7.1.
As validation of this, the test was run again and ended without errors: https://ci.wazuh.info/job/Test_integration/45138/console

**Comment by juliamagan** [comment]
LGTM
