### ISSUE TITLE
DTT1 - Iteration 3 - Test module - Module documentation

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4850]
> Epic #4848

## Description
This issue aims to generate usage and technical documentation for the module

### Tasks
- [x] Usage documentation
- [x] Technical documentation (including class/flow diagrams)

**Comment by pro-akim** [comment]
The present document will be divided into 2 sections:
 
1. User Manual
2. Technical Documentation of the Framework

---

### 1. User Manual:
To perform Deployability type tests, it is necessary to:

- Install Python libraries

For this purpose, it is recommended to use virtual environments. Follow the technical [documentation](https://docs.python.org/es/3/library/venv.html):

Activate the environment:

```
source {venv directory}/bin/activate
```

Clone the wazuh-qa repository:

```
git clone https://github.com/wazuh/wazuh-qa.git
```

Navigate to the project directory and switch to the project branch:

```
cd wazuh-qa
git checkout enhancement/4495-DTT1
```

Install requirements:

```
pip3 install -r /deployability/deps/requirements.txt
pip3 install -r /deployability/deps/remote-requirements.txt
```

- Test Fixture to Execute
> Note: You can find examples in deployability/modules/workflow_engine/examples/


Configure:

```
variables/agent-os
variables/manager-os
infra-provider
working-dir
tasks
```

Pay attention to the tasks:

```
depends-on (test progression: 1. allocation, 2. provision, 3. test)
args
```

In args, configure the launcher's path correctly.

- Execution of Command (local)

Execute the command by referencing the parameters required by the launcher.
Example:

```
python3 {launcher} {test} {schema}
```

```
python3 launchers/workflow_engine.py modules/workflow_engine/examples/dtt1-agents-poc.yaml modules/workflow_engine/schema.json
```

The command execution can also be mediated through Jenkins.

### 2. Technical Documentation of the Framework:

- Modules

The framework has 4 modules (`allocation`, `provision`, `testing`, `observability`) that must act consecutively, and a 5th module that orchestrates the previous modules (`Workflow`).

|Module|Description
|--|--|
|Workflow (Orchestrator)|Receives a YAML containing all the instructions to execute for the test development. It contains instructions for allocation, provision, and testing.
|Allocation| Receives instructions for the desired architecture and creates the structures, generating IPs, ports either in AWS or locally with Vagrant.
|Provision| Installs applications on the structures created in allocation.
|Testing| Executes tests on the previously defined structures.
|Observability| Allows the ordered and indexed visualization of data obtained in the 3 previous modules.

- Directory Structure

```
wazuh-qa/
└── deployability
    ├── deps
    ├── Jenkinsfiles
    ├── launchers
    │   ├── allocation.py
    │   ├── provision.py
    │   ├── test.py
    │   └── workflow_engine.py
    ├── modules
    │   ├── allocation
    │   ├── generic
    │   ├── provision
    │   ├── testing
    │   └── workflow_engine
    ├── playbooks
    └── plugins
```
Deployability contains the following directories:

|Directory|Description|
|---|---|
|deps|Contains information about the dependencies used for installing the necessary libraries for running the framework.|
|Jenkinsfiles|Contains instructions for the pipelines for test execution.|
|launchers|Contains the executor files for each module.|
|modules|Contains files for each module.|
|playbooks|Contains templates and templates used in modules.|
|plugins|Contains modules for the observability plugin.|

**Comment by QU3B1M** [comment]
Required discussion with @fcaffieri about how generic or specific this documentation must be.

**Comment by pro-akim** [comment]
## Update

The documentation will be moved to General documentation.
The test documentation will be written after a POC presentation

**Comment by fcaffieri** [comment]
We need to adapt the documentation with these recommendations:

- We could have a short introduction about allocation in the User documentation section. In the tech documentation section under it, we can see a short intro about the allocation module but nothing similar for the user doc above.
- Styles using passive voice are vague. We could change to active voice instead. For example, "_You must install Python libraries. We recommend using virtual environments_" rather than "... must be installed..." and "... is recommended to use...".
- Maybe creating some subsections with subtitles to separate topics like one for setting up the repository and environment, another one for using the workflow library, another for manually running it, and so on.
- Paths could use links to easily check files content in Github. For example: _**Module functions** [/wazuh-qa/deployability/modules/allocation/allocation.py](https://github.com/wazuh/wazuh-qa/blob/enhancement/4495-DTT1/deployability/modules/allocation/allocation.py): Module-specific functions responsible for triggering the allocation._
- If required, we could review phrasing as well as expanding some topics.

**Comment by pro-akim** [comment]
## Update

Sample updated in https://github.com/wazuh/wazuh-qa/issues/4850#issuecomment-1914645866

**Comment by pro-akim** [comment]
## Update
Some fixes were done.
Readme of wf was incorrectly modified.

**Comment by rauldpm** [comment]
LGTM
