### ISSUE TITLE
data-visualizer script graph labels overlapping

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4899]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| -  | -   |  4.8.0  |

## Description

During research for  https://github.com/wazuh/wazuh/issues/20781 it was detected that the script outputs graphs with overlapping labels. This was replicated on Ubuntu 22.04 and Windows 11 instances.

![Benchmark-worker_10_CPU](https://github.com/wazuh/wazuh-qa/assets/14501079/0df136f1-3fde-4fd4-a7ca-e7b30f64a4ee)

| Module | Windows  | Ubuntu |
| --| --| --| 
| python |  3.12.1| 3.10.12
| matplotlib | 3.8.2  | 3.8.2 |

Research is needed on cause and apply fixes as needed.

**Comment by MARCOSD4** [comment]
## Update

I have read and reviewed the issue and all the other issues it depends on, related to the workload, to better understand the problem. Also, I have reviewed the data-visualizer script.

**Comment by MARCOSD4** [comment]
## Update

I have reviewed how plots are created and performed various tests in my local environment using previously created artifacts but have not been able to replicate the problem.

I have launched this build to test with new artifacts: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/397/

**Comment by MARCOSD4** [comment]
## Update

I have launched several builds to test the generated artifacts and performed several tests but have not been able to replicate the problem because the time range of the tests is too small. I have launched another build to get data with a larger time range and it should be tested when finished: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/403/.

**Comment by rafabailon** [comment]
### LGTM

**Comment by davidjiglesias** [comment]
LGTM
