### ISSUE TITLE
Failed Solaris FIM IT on 4.8.0 Beta 2

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#5033]
| Target version | Related issue | 
|---|---|
| 4.8.0 - Beta 2  | https://github.com/wazuh/wazuh/issues/22125  | 

## Description

During release testing [4.8.0 Beta 2 IT](https://github.com/wazuh/wazuh/issues/22125) suite execution, multiple FIM tests failed on Solaris endpoint.  

This tests have not been migrated to github actions as other agent's have.

The displayed error in all tests occurred during test setup:

```
test_fim/test_files/conftest.py:44: in wait_for_fim_start
    wait_for_fim_active(get_configuration, request)
test_fim/test_files/conftest.py:77: in wait_for_fim_active
    detect_initial_scan(file_monitor)
/opt/python3/lib/python3.7/site-packages/wazuh_testing/modules/fim/event_monitor.py:470: in detect_initial_scan
    error_message=ERR_MSG_SCHEDULED_SCAN_ENDED)
/opt/python3/lib/python3.7/site-packages/wazuh_testing/tools/monitoring.py:199: in start
    error_message=error_message).result()
/opt/python3/lib/python3.7/site-packages/wazuh_testing/tools/monitoring.py:465: in start
    raise TimeoutError(error_message)
E   TimeoutError: Did not receive expected "File integrity monitoring scan ended" event
 -----------------------------Captured stderr setup------------------------------ 
2024/02/26 18:42:13 rootcheck: INFO: Rootcheck disabled.
2024-02-26 18:43:13,800 - wazuh_testing - ERROR - Did not receive expected "File integrity monitoring scan ended" event
2024-02-26 18:43:13,801 - wazuh_testing - ERROR - Results accumulated: 0
2024-02-26 18:43:13,801 - wazuh_testing - ERROR - Results expected: 1

 -------------------------------Captured log setup------------------------------- 
ERROR    wazuh_testing:monitoring.py:461 Did not receive expected "File integrity monitoring scan ended" event
ERROR    wazuh_testing:monitoring.py:462 Results accumulated: 0
```

- Build reports: [Evidence](https://github.com/wazuh/wazuh/files/14408996/agent_solaris_html_report_Test_integration_B46443_20240226171119.zip) 

More research is needed.

**Comment by jotacarma90** [comment]
# Pre-analysis
In the first quick analysis, it can be seen that there has been some problem in the environment, there are multiple errors in the tests, possibly due to the fact that the agent could not be restarted:
TimeoutError: Did not receive expected "File integrity monitoring scan ended" event

In the only test failed of which we have the ossec.log, it can be observed:

```
2024/02/26 18:45:56 wazuh-syscheckd: INFO: (6678): No directory provided for syscheck to monitor.
2024/02/26 18:45:56 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
2024/02/26 18:45:56 rootcheck: INFO: Rootcheck disabled.
2024/02/26 18:45:56 wazuh-syscheckd: INFO: Started (pid: 9460).
2024/02/26 18:45:56 wazuh-syscheckd: INFO: (6000): Starting daemon...
2024/02/26 18:45:56 wazuh-syscheckd: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2024/02/26 18:45:56 wazuh-syscheckd: INFO: (6008): File integrity monitoring scan started.
2024/02/26 18:45:56 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2024/02/26 18:45:56 wazuh-syscheckd: INFO: FIM sync module started.
```

That gives us to understand that the debug mode of the agent is not activated, reinforcing the theory of the problem when restarting the agent.
It is necessary to enter the solaris machine to check what could have happened.

**Comment by jotacarma90** [comment]
# Conclusion

After a deep analysis, I have entered the Solaris machine created by this build (without destroying instances):
https://ci.wazuh.info/job/Test_integration/46454/

Inside I have been able to verify that the problem is that the pipeline was not well configured to activate the debug mode of the agent:
![image](https://github.com/wazuh/wazuh-qa/assets/60003131/74710d20-ce1a-461f-b2da-2b1b803b7108)


Re-launched pipeline waiting for everything to work OK:
https://ci.wazuh.info/job/Test_integration/46455/
