### ISSUE TITLE
System agentless_cluster tests fail in 4.8.0-beta4

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5100]
### Description

During [Release 4.8.0 - Beta 4 - System tests](https://github.com/wazuh/wazuh/issues/22481) it has been detected unexpected errors
in the agentless_cluster environment tests `test_integrity_sync`

Probably the error is due to a change in the log message. We can find the following log message
```
2024/03/13 11:27:02 WARNING: [Worker wazuh-worker1] [Integrity sync] {'etc/rules/test_file_big_8': ['Maximum zip size exceeded. Not all files will be compressed during this sync.']}
```

Further research is required

### Evidences

- **Test case**: `test_zip_size_limit`
- **Error**
```
E                   TimeoutError: Did not found the expected callback in wazuh-master: .*File too large to be synced: /var/ossec/etc/rules/test_file_too_big
```
- Report: [agentless_cluster.zip](https://github.com/wazuh/wazuh-qa/files/14601375/agentless_cluster.zip)

**Comment by juliamagan** [comment]
Moved to `On hold` due to https://github.com/wazuh/wazuh-qa/issues/5113

**Comment by juliamagan** [comment]
It has been seen that the behavior of the logs has changed, with the logs now being concatenated instead of appearing individually:

```
2024/03/20 15:41:44 WARNING: [Worker wazuh-worker1] [Integrity sync] {'etc/rules/test_file_too_big': ['File too large to be synced: /var/ossec/etc/rules/test_file_too_big'], 'etc/rules/test_file_big_7': ['Maximum zip size exceeded. Not all files will be compressed during this sync.']}
2024/03/20 15:41:47 WARNING: [Worker wazuh-worker2] [Integrity sync] {'etc/rules/test_file_big_4': ['Maximum zip size exceeded. Not all files will be compressed during this sync.']}
```

We should adapt this test to the change of logs. Also, I think there is some problem with the size of the files and we should check it.

**Comment by juliamagan** [comment]
After speaking with @Selutario  about how integrity sync works, and what the test was intended to test, it has been decided to modify the size and number of files so that they can be run in almost any environment.

Initially, 140 files of 1MB had been added so that they exceeded the 100MB limit. However, in a t3.large environment, it took 22 minutes to finish the test and also failed, since the last logs, although they appeared, appeared after the timeout (2 minutes). Switching to a c5.large instance reduced the speed to 15 minutes, but it still failed. The files have been reduced to 60MB and the limit to 50MB to avoid very long and expensive tests. In this way, the test lasts about 8~9 minutes and passes correctly.


|Instance|Files|Duration|Result|
|:--:|:--:|:--:|:--:|

**Comment by juliamagan** [comment]
After running several tests, it has failed again in EC2 environments. In addition, in local it fails because being faster, the timeout does not occur.

We are trying to refactor the test so that it takes as little time as possible, but we should consider increasing the capacity of the instances.

**Comment by santipadilla** [comment]
LGTM

**Comment by rauldpm** [comment]
LGTM
