### ISSUE TITLE
Unify monitoring metrics values for child processes with those of the main process

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5479]
## Description

The current monitoring class records metrics separately for the main process and its child processes, leading to potential inconsistencies and difficulties in data aggregation, comparison and analysis.
For example, in [Release 4.8.0 - RC 4 - Vulnerability Detection performance test](https://github.com/wazuh/wazuh/issues/23982) wazuh-indexer binary metrics split child metrics from main process:
 
![CPU](https://github.com/wazuh/wazuh-qa/assets/11089305/52871ede-9fe7-4b00-a269-10bc3409174a)

 To enhance the accuracy and usability of monitoring data, unify the metrics collected for child processes with those of the main process.

## Tasks

- [ ] Design a unified monitoring strategy that consolidates child process metrics.

## Validation

- [ ]  Processes with multiple child processes appear in metrics as one..

**Comment by rafabailon** [comment]
## Procedure

To generate the graphs, there must first be a CSV file with the information to be painted. The first thing to do is to launch the monitor. The code can be found in [wazuh_metrics.py#116](https://github.com/wazuh/wazuh-qa/blob/3cd69e3b77849d6252cc44d1c022b8ce89b4c9dd/deps/wazuh_testing/wazuh_testing/scripts/wazuh_metrics.py#L116). The monitor generates a CSV file per process and per sub-process. This can be checked in the artifacts generated by the pipeline. 

The monitor class found in [binary.py#23](https://github.com/wazuh/wazuh-qa/blob/3cd69e3b77849d6252cc44d1c022b8ce89b4c9dd/deps/wazuh_testing/wazuh_testing/tools/performance/binary.py#L23) is in charge of collecting the data and generating a CSV file with them. At the end we obtain a CSV for each monitored process and sub-process.

These CSVs are the ones used in [data_visualizations.py#L27](https://github.com/wazuh/wazuh-qa/blob/3cd69e3b77849d6252cc44d1c022b8ce89b4c9dd/deps/wazuh_testing/wazuh_testing/scripts/data_visualizations.py#L27) to generate the plots. This is where data from different CSVs are put together and painted into a single plot.

## Possible Solutions

A possible solution is to add in the Monitor logic the necessary code to generate an extra CSV file with the combined information of the processes and their subprocesses. You may also have to modify the logic that paints the plots to take all this into account.

Another solution would be that the logic itself to paint the plots includes the possibility of combining the data of the processes and subprocesses. I believe that it would not be the best idea since the class that paints the plots should not modify the data.
