### ISSUE TITLE
Benchmarking tools and techniques investigation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5502]
# Description

The objective of this issue is to investigate and identify the most effective tools, techniques, and methodologies for benchmarking testing. These tests will serve as a baseline for comparison, enabling the tracking of performance improvements or regressions. By doing so, benchmarking will help maintain and enhance the efficiency of the product. The proposed tools and techniques should meet the proposed functional and non-functional requirements. This research will enable us to determine the necessary functionalities to develop a performance test for the product, ensuring that it is comprehensive and effective.

# Funcional Requirements

## Capabilities

   - **Scripting module**: 
     - Records user interactions for testing.
     - Allows modification of recorded scripts to add data and configure measurement details.
   - **Test management module**: 
     - Creates and executes test scenarios that simulate various user activities.
     - Uses recorded scripts and load generators to simulate different loads.
   - **Load Injector**: 
     - Generate different loads in the environment.
   - **Analysis Module**
       - Analyze the test data automatically, determining if they are within baseline or not.
       - Provides computational results.
       - Provides reports and visualizations to help understand test results.

## KPTM analysis and data collection

Proposed tools should be capable of monitoring the following KPTM (Key Performance Test Metrics):

- CPU, memory, file descriptors, disk operations, hardware usage of all Wazuh components: Agent, Manager, Indexer, Dashboard
- Events per second for different modules, varying event size
- API request response time
- Dashboard web load time
- Error rate
- Loss alert percentage
- Indexing time for alerts/vulnerabilities, etc.

# Implementation restrictions

- The CI process must use the QA owned Jenkins infrastructure.
- New tests must be developed using the JobFlow Python dependency.
- Consider OpenSearch benchmarking tools for Wazuh indexer.
- The CI process should be parallelizable, extensible and cost-efficient
- Benchmarking techniques and tools should be industry standard.

# Plan

1. Agree on expected KPTM values
   - Identify the KPTM to be measured
   - Determine target values for these KPTM to ensure the system meets performance standards
2. Research and Analysis: 
   - Research current tools
   - Research tools to collect, analyze, and generate testing loads
   - Research tools for reporting and analysis. 
   - Identify the most suitable tools for collecting and analyzing KPTM values.
   - Analyze the tools and their capabilities to determine the best fit for testing needs.
  
## Related issues

**Parent issue**
- https://github.com/wazuh/wazuh/issues/23383

**Comment by rafabailon** [comment]
## Tools

- [Artillery](https://www.artillery.io/)
- [Opensearch Benchmark](https://opensearch.org/docs/latest/benchmark/)
- [Playwright](https://playwright.dev/)
- [Locust](https://locust.io/)
- [Fluentd](https://www.fluentd.org/)

**Comment by MARCOSD4** [comment]
## Tools

- [Prometheus](https://prometheus.io/) and [Grafana](https://grafana.com/)
- [Zabbix](https://www.zabbix.com/)
- [Nagios](https://www.nagios.org/)
- [Netdata](https://www.netdata.cloud/)
- [Telegraf, InfluxDB](https://www.influxdata.com/time-series-platform/telegraf/) and [Grafana](https://grafana.com/)

**Comment by rafabailon** [comment]
## Metrics Analysis Tools

| Tool | Advantages | Disadvantages |
| --- | --- | --- |
| Prometheus | Easy Installation and Deployment. Metrics Collection. Data Visualization. Scalability. | Configuration and Setup. Scalability. Customer Service. |
| Grafana | Customizable Dashboards. User-Friendly Visualization. | Customization Effort. Limited Visualization Styles. External Data Storage. |
| Netdata | Real-Time Monitoring. Lightweight. Automatic Dashboard Creation. | Limited Historical Data. Complex Configuration. |
| Nagios | Alerting and Incident Management. Compatible Platforms. Documentation and Support. | Installation Complexity. UI/UX Design. Scalability. |
| Zabbix | Metrics Collection. Scalability. Incident Management. | Installation and Setup. UI/UX Design. Data Visualization. | 

## Advantages and Disadvantages (Explained)

<details>
   <summary>Prometheus</summary>
   <br/>

- Advantages:
   - Easy Installation and Deployment: Prometheus is straightforward to install and deploy.
   - Metrics Collection: It excels at collecting time series data from servers.
   - Data Visualization: Although it lacks built-in visualization, it pairs well with Grafana for creating customizable dashboards.
   - Scalability: Prometheus scales well.

- Disadvantages:
   - Configuration and Setup: Can be development-intensive.
   - Scalability: Becomes challenging at large scale.
   - Customer Service: Known for slow response times.

</details>

<details>
   <summary>Grafana</summary>
   <br/>

- Advantages:
   - Customizable Dashboards: Grafana allows you to create and customize dashboards for visualizing metrics.
   - User-Friendly Visualization: Provides a variety of visualization options.

- Disadvantages:
   - Customization Effort: Customizing Grafana dashboards can be time-consuming.
   - Limited Visualization Styles: Some limitations in visual representation.
   - External Data Storage: Requires external data storage.

</details>

<details>
   <summary>Netdata</summary>
   <br/>

- Advantages:
   - Real-Time Monitoring: Provides real-time insights into system performance.
   - Lightweight: Minimal resource overhead.
   - Automatic Dashboard Creation: Automatically generates dashboards for various services.

- Disadvantages:
   - Limited Historical Data: Focuses on real-time data, lacks extensive historical data storage.
   - Complex Configuration: Setting up custom monitoring can be intricate.

</details>

<details>
   <summary>Nagios</summary>
   <br/>

- Advantages:
   - Alerting and Incident Management: Strong alerting capabilities.
   - Compatible Platforms: Works on various Unix variants.
   - Documentation and Support: Well-documented and supported.

- Disadvantages:
   - Installation Complexity: Requires additional setup (Apache server, Nagios Plugins).
   - UI/UX Design: Could be improved.
   - Scalability: May face challenges at scale.

</details>

<details>
   <summary>Zabbix</summary>
   <br/>

- Advantages:
   - Metrics Collection: Robust data collection.
   - Scalability: Scales well.
   - Incident Management: Effective alerting and incident handling.

- Disadvantages:
   - Installation and Setup: Installation guide lacks details on database and web server setup.
   - UI/UX Design: Could be enhanced.
   - Data Visualization: Requires integration with other tools like Grafana.

</details>

**Comment by rafabailon** [comment]
## Update

Research must be expanded to the tools that are already being used. Specifically, we must review how hardware resources are monitored (tests and footprints). Also, alerts and specific Wazuh measurements are generated that are not possible to cover with an external tool.

**Comment by Rebits** [comment]
### Tools for saturation of wazuh modules (internal) :large_blue_circle:

**Comment by Rebits** [comment]
## Tools for running processes and system utilization monitoring (external and internal tools) 🔵

**Comment by rafabailon** [comment]
## Locuts vs Artillery

Both **Artillery** and **Locust** are popular tools for load and performance testing.

| Information | Artillery | Locust |
| --- | --- | --- |
| Created By | Shoreditch Ops LTD | Ferran Basora |
| License | Apache 2.0 | MPL2 |
| Written In | NodeJS | Python |
| Scriptable | Yes | Yes |
| Distributed Load Generation | No | Yes |
| Website | [Artillery](https://artillery.io/) | [Locust](https://locust.io/) |
| Performance | Artillery was considered slower than other tools | Locust has improved significantly and was considered faster than before |
| Approach | Artillery focuses on executing load scenarios defined in YAML files. You can specify paths, timeouts, payloads, and more. | Locust focuses on simulating real users interacting with a web application. You can define custom behaviors for these virtual users. |
| Resources | Locust, being written in Python, may require fewer resources compared to Artillery (written in NodeJS). However, this may vary depending on the load scenario and configuration. | Artillery, being lighter and faster to set up, could be more resource efficient. |
| Data Returned | Locust provides detailed information about virtual user performance, such as response times, errors, and statistics. | Artillery returns metrics such as latency, success rate, average response time, and more, depending on the scenario configuration. |

In short, **Locust** has improved in performance, while **Artillery** has decreased in speed. Both tools have their advantages and disadvantages, so the choice depends on your specific needs and preferences. If you are looking for a faster and more distributed tool, **Locust** might be the better choice.

Locust is more widely used than Artillery at the moment. The most notable advantage is that whenever you can write Python code to do something, you can test it with Locust. This makes it much easier to deploy. Also, the integration with Jenkins is very simple and fast since it can even be used as a [library](https://docs.locust.io/en/stable/use-as-lib.html). This would allow you to run tests automatically, generate results and even analyze them.

In the case of Artillery, it is not yet as widely used as Locust. It uses JavaScript for tests. This not only complicates the creation of tests but, if you want to integrate it with Jenkins, it is more complex (and requires [Docker](https://hub.docker.com/u/artilleryio) to run the tests). In my tests, it has also turned out to be slower when running tests and does not offer the possibility of distributed load generation.

**Comment by rafabailon** [comment]
## Tools for Analysis

A first idea is to manually analyze the data with a Python script. To do this, it is useful to use the libraries available in Python.

| Library | Description | Use |
| --- | --- | --- |
| Pandas | Provides data structures (such as DataFrames) for data analysis and manipulation. | Cleaning, transformation and analysis of tabular data. |
| NumPy | Ideal for mathematical calculations in multidimensional arrays. | Linear algebra, statistics, array manipulation. |
| Matplotlib | Used to create graphs and visualizations. | Creation of 2D and 3D graphics, data visualization. |
| Seaborn | Useful library for statistical visualization. | Improves the appearance of Matplotlib plots, especially for data analysis. |

It is also possible to use some alternative tools. `R` is the most widespread and popular although it is still a specific programming language for calculations and analysis.

| Tool | Description |
| --- | --- |
| R | Programming language and statistical environment widely used for data analysis. |
| Apache Kafka | Real-time data streaming platform to process data streams. |
| Apache Spark | Clustered data processing engine for distributed analytics. |
| Tableau | Popular tool for data visualization and creating interactive dashboards. |

**Comment by rafabailon** [comment]
## Grafana Open Source vs Grafana Enterprise

| Characteristics | Grafana Open Source | Grafana Enterprise |
| --- | --- | --- |
| License | Open source | Commercial |
| Premium Plugins | Not included | Included |
| Integration with Tools | Limited | Expanded |
| Authentication and Security | Basic | Advanced |
| Support and Maintenance | Community | Premium Support |

Grafana is a widely used open source visualization and monitoring tool. The [Grafana Enterprise](https://grafana.com/docs/grafana/latest/introduction/grafana-enterprise/) version is the commercial edition of Grafana and offers additional features not found in the open source version. Here are the key differences:

**Premium Plugins**
   - Grafana Enterprise includes integrations with commercial monitoring tools such as Datadog, Splunk, New Relic, AppDynamics, Oracle and Dynatrace. These plugins are created, maintained and supported by the Grafana Labs team.
   - If you are a customer of any of these companies and value having that data available in Grafana, Grafana Enterprise gives you access to all of these plugins. This enables centralized observability with Grafana as a single access point.

**Authentication and Security**
   - For businesses, managing access control for existing users and reducing friction when managing new users is a major challenge.
   - Grafana Enterprise offers seamless LDAP sync, data source permissions, and team sync features. This makes it easy to expand access to all relevant stakeholders and protect sensitive data without needing to completely separate Grafana instances.

According to the official documentation, this is the [list of exclusive features of the Enterprise version](https://grafana.com/docs/grafana/latest/introduction/grafana-enterprise/#enterprise-features):

   - Role-based access control to control access with role-based permissions.
   - Data source permissions to restrict query access to specific teams and users.
   - Data source query and resource caching to temporarily store query results in Grafana to reduce data source load and rate limiting.
   - Reporting to generate a PDF report from any dashboard and set up a schedule to have it emailed to whomever you choose.
   - Export dashboard as PDF
   - Custom branding to customize Grafana from the brand and logo to the footer links.
   - Usage insights to understand how your Grafana instance is used.
   - Recorded queries to see trends over time for your data sources.
   - Vault integration to manage your configuration or provisioning secrets with Vault.
   - Auditing tracks important changes to your Grafana instance to help you manage and mitigate suspicious activity and meet compliance requirements.
   - Request security makes it possible to restrict outgoing requests from the Grafana server.
   - Settings updates at runtime allows you to update Grafana settings at runtime without requiring a restart.

In general, depending on the features you need, this is a summary of which version of Grafana to use:

**Grafana Open Source**
   - Use Grafana Open Source if you are looking for a free open source solution.
   - It is ideal for personal projects, small businesses or development environments.
   - Offers a wide variety of data sources and visualizations.
   - Does not include premium plugins or advanced security features.

**Grafana Enterprise**
   - Opt for Grafana Enterprise if you need advanced features and premium support.
   - Use it in business environments with more demanding requirements.
   - Includes premium plugins for integration with commercial tools.
   - Offers advanced authentication, LDAP sync, and data source permissions.

List of [Premium Plugins](https://grafana.com/docs/grafana/latest/introduction/grafana-enterprise/#enterprise-data-sources):

<details>
   <summary>Expand List</summary>
   <br/>

| Plugin | Use |
| --- | --- |
| [AppDynamics](https://grafana.com/grafana/plugins/dlopes7-appdynamics-datasource/) | The AppDynamics data source plugin is the easiest way to pull AppDynamics data directly into Grafana dashboards. |
| [Azure Cosmos DB](https://grafana.com/grafana/plugins/grafana-azurecosmosdb-datasource/) | The Azure Cosmos DB data source plugin allows you to query and visualize Cosmos DB data in Grafana. |
| [Azure Devops](https://grafana.com/grafana/plugins/grafana-azuredevops-datasource/) | The Azure DevOps data source plugin allows you to query and visualize Azure DevOps data from within Grafana. |
| [Catchpoint](https://grafana.com/grafana/plugins/grafana-catchpoint-datasource/) | The Catchpoint data source plugin allows you to query Tests, SLO, RUM data. |
| [Databricks](https://grafana.com/grafana/plugins/grafana-databricks-datasource/) | The Databricks datasource allows a direct connection to Databricks to query and visualize Databricks data in Grafana. |
| [Datadog](https://grafana.com/grafana/plugins/grafana-datadog-datasource/) | The Datadog data source plugin is the easiest way to pull Datadog data directly into Grafana dashboards. |
| [DynamoDB](https://grafana.com/grafana/plugins/grafana-dynamodb-datasource/) | The DynamoDB datasource allows a direct connection to DynamoDB to query and visualize data in Grafana. |
| [Dynatrace](https://grafana.com/grafana/plugins/grafana-dynatrace-datasource/) | The Dynatrace data source plugin is the easiest way to pull Dynatrace data directly into Grafana dashboards. |
| [GitLab](https://grafana.com/grafana/plugins/grafana-gitlab-datasource/) | The GitLab data source plugin is the easiest way to pull GitLab data directly into Grafana dashboards. |
| [Grafana Enterprise Logs](https://grafana.com/grafana/plugins/grafana-enterprise-logs-app/) | Grafana Enterprise Logs (GEL) is a commercial offering based on the open-source project Loki. The commercial offering allows you to deploy a highly-scalable, simple, and reliable logs cluster in your own data center. This app plugin gives you an easy way to manage your logs cluster. |
| [Grafana Enterprise Metrics](https://grafana.com/grafana/plugins/grafana-metrics-enterprise-app/) | Grafana Enterprise Metrics (GEM) is a commercial offering based on the open-source project Mimir. The commercial offering allows you to deploy a higly-scalable, simple, and reliable metrics cluster in your own data center. This app plugin gives you an easy way to manage your metrics cluster. |
| [Grafana Enterprise Traces](https://grafana.com/grafana/plugins/grafana-enterprise-traces-app/) | Grafana Enterprise Traces (GET) is a commercial offering based on the open-source project Tempo. The commercial offering allows you to deploy a highly-scalable, simple, and reliable traces cluster in your own data center. The app plugin gives you an easy way to manage your traces cluster. |
| [Honeycomb](https://grafana.com/grafana/plugins/grafana-honeycomb-datasource/) | The Honeycomb data source plugin is the easiest way to pull Honeycomb data directly into Grafana dashboards. |
| [Jira](https://grafana.com/grafana/plugins/grafana-jira-datasource/) | The Jira data source plugin is the easiest way to pull Jira data directly into Grafana dashboards. |
| [Looker](https://grafana.com/grafana/plugins/grafana-looker-datasource/) | The Looker data source plugin allows you to visualize data from Looker in Grafana. |
| [MongoDB](https://grafana.com/grafana/plugins/grafana-mongodb-datasource/) | With the Grafana data source plugin for MongoDB, you can interact in real time with your existing MongoDB data and unify data sets across your company into one diagnostic workspace. |
| [New Relic](https://grafana.com/grafana/plugins/grafana-newrelic-datasource/) | The New Relic data source plugin is the easiest way to pull New Relic data directly into Grafana dashboards. |
| [Oracle Database](https://grafana.com/grafana/plugins/grafana-oracle-datasource/) | The Oracle data source plugin is the easiest way to pull Oracle data directly into Grafana dashboards. |
| [PagerDuty](https://grafana.com/grafana/plugins/grafana-pagerduty-datasource/) | The PagerDuty data source plugin allows you to query incidents data or visualize incidents within Grafana using annotations. |
| [Salesforce](https://grafana.com/grafana/plugins/grafana-salesforce-datasource/) | The Salesforce data source plugin is the easiest way to pull Salesforce data directly into Grafana dashboards. |
| [SAP HANA®](https://grafana.com/grafana/plugins/grafana-saphana-datasource/) | The SAP HANA® data source plugin is the easiest way to pull SAP HANA® data directly into Grafana dashboards. |
| [ServiceNow](https://grafana.com/grafana/plugins/grafana-servicenow-datasource/) | The ServiceNow data source plugin is the easiest way to pull ServiceNow data directly into Grafana dashboards. |
| [Snowflake](https://grafana.com/grafana/plugins/grafana-snowflake-datasource/) | The Snowflake data source plugin is the easiest way to pull Snowflake data directly into Grafana dashboards. |
| [Splunk](https://grafana.com/grafana/plugins/grafana-splunk-datasource/) | The Splunk data source plugin is the easiest way to pull Splunk data directly into Grafana dashboards. |
| [Splunk Infrastructure Monitoring](https://grafana.com/grafana/plugins/grafana-splunk-monitoring-datasource/) | The Splunk Infrastructure Monitoring (formerly known as SignalFx) data source plugin is the easiest way to pull Splunk Infrastructure Monitoring data directly into Grafana dashboards. |
| [Sqlyze Datasource](https://grafana.com/grafana/plugins/grafana-odbc-datasource/) | A Grafana data source plugin that connects to hundreds of datasources using one language: SQL. Connect to your favorite SQL databases, NoSQL databases, and many other non-SQL sources...and query them with SQL. |
| [Sumo Logic](https://grafana.com/grafana/plugins/grafana-sumologic-datasource/) | The Sumo Logic data source plugin is the easiest way to pull Sumo Logic data directly into Grafana dashboards. |
| [Wavefront](https://grafana.com/grafana/plugins/grafana-wavefront-datasource/) | The Wavefront data source plugin is the easiest way to pull Wavefront data directly into Grafana dashboards. |

</details>

Regarding prices, Grafana does not clearly show the [price of its Enterprise version](https://grafana.com/pricing/). Likewise, it does not easily offer a demo. You need to contact Grafana to get a demo and pricing for Grafana Enterprise. Likewise, the information is not very clear since they focus on the sale of their cloud services.

To consider using Grafana Enterprise we would have to see if we need any of the extra functions. If they are not necessary, the Open Source version should cover all needs.

**Comment by rafabailon** [comment]
## Conclusions 🔵

**Comment by Rebits** [comment]
### Dashboard Performance tests

It has been confirmed in a meeting with @davidjiglesias @havidarou and @julia the use of Artillery and Playwright for basic performance testing. LGTM

### API Tests

It has been confirmed in a meeting with @davidjiglesias @havidarou and @julia the use of Locust for basic performance testing. LGTM

### Data Analysis

It has been confirmed in a meeting with @davidjiglesias @havidarou and @julia the use of Python libraries for statistical analysis of performance results. Further research will be carried on at the design phase. LGTM

### Modules saturation

It has been confirmed in a meeting with @davidjiglesias @havidarou and @julia the use of custom tools for module saturation in the Agent performance test. LGTM

### Process monitoring

It has been confirmed in a meeting with @davidjiglesias @havidarou and @julia the use of current libraries based on psutils for process monitoring. LGTM

### Visualization (@MARCOSD4 )

Grafana and Prometheus visualization method could maybe not be the best suit due to the following reasons:
 
- **Temporal Data Focus**: Grafana and Prometheus are primarily designed for visualizing time-series data, where the emphasis is on trends and changes over time. Our performance data is not temporal and does not change over time, using these tools may not be efficient or necessary.

- **Complexity Overhead**: Setting up and maintaining Grafana and Prometheus can be complex. These tools are built for managing and visualizing dynamic, time-sensitive metrics, which means configuring them for non-temporal data can involve unnecessary complexity and overhead.

- **Resource Intensiveness**: Prometheus especially is optimized for time-series data storage and querying. Using it for non-temporal data might result in inefficient use of resources (storage, memory, processing power) compared to simpler tools that are better suited for static data.

- **Feature Overkill**: Grafana offers a rich set of features tailored for time-series visualization, including dynamic dashboards, alerting based on thresholds, and detailed metric exploration. Our case doesn’t require these features, using Grafana might be overkill and unnecessarily complicate your visualization setup.

- **Simplicity Preference**: For offline and non-temporal data visualization, simpler tools that focus solely on static data visualization might be more appropriate. Such tools typically have a lighter footprint, are easier to set up, and are more intuitive for users who do not need advanced time-series analysis capabilities.


For these reasons, I suggest researching Plotly/Dash applications to visualize performance metrics https://plotly.com/python/. I also provided a basic PoC of how metrics could appear in a future performance dashboard:
[PoCFootprint.zip](https://github.com/user-attachments/files/16176115/PoCFootprint.zip)

It is requested to investigate these libraries and incorporate them into the analysis to finalize the research

**Comment by MARCOSD4** [comment]
An in-depth analysis of Plotly and Dash has been added to [this commentary](https://github.com/wazuh/wazuh-qa/issues/5502#issuecomment-2180980202), and the final conclusion has been edited according to the research done.

**Comment by jseg380** [comment]
LGTM

**Comment by Rebits** [comment]
LGTM
