### ISSUE TITLE
Change `Ensure that the manager version is` warning version agnostic in VD E2E tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5609]
# Description

It has been detected in [Release 4.9.0 - Alpha 3 - Vulnerability Detection E2E tests](https://github.com/wazuh/wazuh/issues/24809#issuecomment-2247927918) that 
`Ensure that the manager version is` expected warning it only expects hardcoded v4.8.0.
It's necessary to change this into an agnostic version of regex.

**Comment by hossam1522** [comment]
The `Ensure that the manager version is` expected warning has been changed to work with any version:
- https://github.com/wazuh/wazuh-qa/blob/bug/5609-ensure-manager-version-agnostic/tests/end_to_end/test_vulnerability_detector/test_vulnerability_detector.py

It remains to check that the changes have been correctly applied and that everything works perfectly.

**Comment by hossam1522** [comment]
On hold until the test is finished:
- Build: https://ci.wazuh.info/job/Test_e2e_system/336/

**Comment by hossam1522** [comment]
The build finished without a report because of:

```
21:27:08  hudson.remoting.ProxyException: org.wazuh.JenkinsException: Invalid testingPytest did not launch correctly [end_to_end/test_vulnerability_detector] tests modules. Report was not created
```

This failure was mentioned in https://github.com/wazuh/wazuh-jenkins/issues/6246#issuecomment-1961021711 without reaching any clear conclusion.

The pipeline will be re-executed. In case the error is persistent, a new issue will be opened concerning this problem:
- Build: https://ci.wazuh.info/job/Test_e2e_system/337/

On hold until the test is finished.

**Comment by hossam1522** [comment]
The pipeline was successfully executed and you can see from the following evidence that the problem was fixed correctly:
- Build: https://ci.wazuh.info/job/Test_e2e_system/337/
- Evidence: [Test_e2e_system_337_test_vulnerability_detector.zip](https://ci.wazuh.info/job/Test_e2e_system/337/artifact/337/Test_e2e_system_337_test_vulnerability_detector.zip)

# Summary
## Before
Before the code was fixed, the results obtained in https://github.com/wazuh/wazuh/issues/24809#issuecomment-2247927918 were:
![image](https://github.com/user-attachments/assets/ab6d96be-0a9d-4bf1-868e-e9783f087cf4)
![image](https://github.com/user-attachments/assets/89f1f2d3-77bd-4f7e-ab3d-3c6eec6503b9)

## After
Now, after the code was fixed:
![image](https://github.com/user-attachments/assets/4986d19f-6d6c-422e-b532-9c2e2e4e5a70)
![image](https://github.com/user-attachments/assets/3fe0c13b-b41b-4d90-8c29-7029c479fb08)


Errors obtained in the report other than the fixed one were reported in https://github.com/wazuh/wazuh/issues/24809#issuecomment-2247927918.

A pull request has been created: 
- https://github.com/wazuh/wazuh-qa/pull/5630
