### ISSUE TITLE
Log all pytest output in the Jobflow testing module

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5613]
# Description

Testing https://github.com/wazuh/wazuh/issues/24935, it has been observed that the pytest output only appears if an error occurs, we need to change this so we can log the passed tests too

https://github.com/wazuh/wazuh-qa/blob/v4.9.0-alpha3/deployability/modules/testing/testing.py#L86-L102

We need to change the _run_tests method of the testing.py file to the following

```

    @classmethod
    def _run_tests(cls, test_list: list[str], ansible: Ansible, extra_vars: ExtraVars) -> None:
        """
        Execute the playbooks that runs the tests.

        Args:
            test_list (list[str]): The list of tests to run.
            ansible (Ansible): The Ansible object to run the tests.
            extra_vars (ExtraVars): The extra vars for the tests.
        """
        for test in test_list:
            rendering_var = {**extra_vars, 'test': test}
            template = str(cls._test_template)
            result = ansible.run_playbook(template, rendering_var)
            for event in result.events:
                logger.info(f"{event['stdout']}")
            if result.stats["failures"]:
                for event in result.events:
                    if "fatal" in event['stdout']:
                        raise Exception(f"Test {test} failed with error")
```

This has been tested with the mentioned testing issue and in the log, the pytest output can be observed

This is going to be treated as a bug as it is not desired to hide testing output

**Comment by joaquinsgi** [comment]
The changes for the _run_tests method in order to view the logs of the passed tests are applied to a new branch: [enhacement/5613-change_run_tests-method](https://github.com/wazuh/wazuh-qa/tree/enhacement/5613-change_run_tests-method).

A new pull request was made to merge the branch with the specified changes with branch 4.9.0: https://github.com/wazuh/wazuh-qa/pull/5618

**Comment by fcaffieri** [comment]
Good job, let's perform some execution from the branch where the changes were made, to ensure that it does not fail due to some indentation, and incorporate the executed test into the associated PR.
On the other hand, since it is a bug, the name of the branch should be `bug/5613-change-run_tests-method` instead of `enhacement/5613-change-run_tests-method` since it is not a new feature or enhancement.

**Comment by rauldpm** [comment]
Testing has been done on the linked issue with the change proposed

**Comment by joaquinsgi** [comment]
Updated the branch from `enhacement/5613-change-run_tests-method` to `bug/5613-change-run_tests-method`

**Comment by fcaffieri** [comment]
LGTM

**Comment by rauldpm** [comment]
LGTM
