### ISSUE TITLE
Inconsistent results in Indexer Vulnerability Detection performance tests

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5667]
## Description

Analyzing [Release 4.9.0 - Beta 1 - Vulnerability Detection performance test](https://github.com/wazuh/wazuh/issues/25081) It is found that the Indexer 2 CPU plot appears incorrect or inconsistent.
In the rest of the plots you can see that the indexer was not working or went silent. There are no errors detected in the logs that refer to this

Detail:

[artifacts.tgz.zip](https://github.com/user-attachments/files/16563268/artifacts.tgz.zip)

![image](https://github.com/user-attachments/assets/5d23bc01-16a8-43b4-b93a-69fc7efc303f)

4.8.1:

![image](https://github.com/user-attachments/assets/73dfbb70-4cb7-4e34-b306-ccdd32d1a579)

4.9.0

![image](https://github.com/user-attachments/assets/e5943c57-7bff-4071-9911-3975b4e85a8e)

> More research required

**Comment by MARCOSD4** [comment]
After investigating the possible cause of this issue, it has been found that this is not a consistent problem. These Vulnerability Detection performance tests have been run numerous times since 4.8.0 and this problem has been appearing without any apparent pattern between the different tests (medium, high, and very high). For example, this issue was reported for the medium activity case in [4.9.0-beta1](https://github.com/wazuh/wazuh/issues/25081#issuecomment-2276666127) but has not appeared in the recent [4.9.0-beta2](https://github.com/wazuh/wazuh/issues/25140#issuecomment-2284047929) tests. In addition, I have re-run the medium activity test with the same parameters and the same thing has not occurred either:

Build: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/625/
Artifacts: [artifacts.zip](https://github.com/user-attachments/files/16597863/artifacts.zip)

This leads us to conclude that this is not a consistent problem and that its cause is more complicated to determine.

This problem has already been reported in this [issue](https://github.com/wazuh/wazuh-qa/issues/5479) in order to unify the processes that appeared to be split when monitoring them. This division makes the results inconsistent and difficult to compare and analyze. Therefore, to improve the accuracy of the analysis and its usability, it was decided to add a parameter to unify the generated threads into a single one. This parameter should be used in these tests, as it was introduced precisely for use here, and it will also allow the comparison to be more accurate.
To check this, I re-launched the tests for the very high activity case, which was the only one where this problem appeared in 4.9.0-beta2, checking the option to unify the processes. The results should be analyzed tomorrow: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/627/

**Comment by MARCOSD4** [comment]
Moved to On hold until the [build](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/627/) is complete.

**Comment by rauldpm** [comment]
@MARCOSD4 could it be that there is a master node and two workers? that would explain why one node has less resource usage (master) and why two of them have a high usage (workers), but we need to know if this behavior is expected with that workload

**Comment by MARCOSD4** [comment]
## Conclusion 

Indeed, as @rauldpm points out, one indexer's low use of resources is because it acts as a coordinator node and delegates the operations to the rest of the indexers. This occurs if you keep the default configuration when installing Wazuh, as in the case of these tests. Then, OpenSearch automatically chooses a coordinator node and the rest of the indexers perform the data ingest operations. It can also happen that all the nodes distribute the operations among them and there is no coordinator as such, in that case, all the indexers would have acceptable resource usage values, as has also been seen in other tests.

Therefore, the behavior reported in this issue is expected and should be considered in the future for these tests. In addition, it would be advisable to launch the tests using the `UNIFY_BINARY_PROCESSES_FOR_PLOTTING` pipeline option to avoid confusion with the `child` processes and make the analysis more accurate, as mentioned above.

**Comment by santipadilla** [comment]
LGTM

**Comment by rauldpm** [comment]
Good job @santipadilla! We will take it into account in the next release of testing

1. We must identify which node is the master in both versions and compare those nodes, for the workers we will just compare them randomly as we can't identify them individually
2. W will set the unify daemon in the pipeline
