### ISSUE TITLE
Increase Scan Timeout in VD E2E tests

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-qa#5669]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
|   |  https://github.com/wazuh/wazuh-qa/issues/5664  |   |

## Description

After executing and reviewing the **VD E2E tests**, @Rebits detected that the VD database is so slow that it causes some tests to fail when detecting vulnerabilities. The vulnerabilities are inconsistent, so we should also increase the scan timeout for this issue: https://github.com/wazuh/wazuh-qa/issues/5664. As seen in previous stages, errors appear in the product that weren't present in version 4.8.1. The errors are also strange because, even though they fail due to timeout, they tend to always fail in the same spots.

## Proposed checks

- [ ] Check that the database works successfully.
- [ ] Check that the scans doesn't fail in vulnerabilities.

## Expected results

Ensuring that the E2E tests do not fail in VD as observed in previous tests.

**Comment by Rebits** [comment]
Debug results will be performed as part of the 4.9.0 RC 1. In addition this same behaviour is being researched in the following issues:
- https://github.com/wazuh/wazuh-qa/issues/5657
- https://github.com/wazuh/wazuh-qa/issues/5665

I suggest in the future analyzing the failures of these tests in the same issue, due to all being related to the nature of the VD scanner. Closing as not planned
