### ISSUE TITLE
Vulnerability Detector: Integration tests for general settings

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#660]
| Tier | Type |
|-|-|
| 0 | Configuration |

### Description

Test the general settings of the Vulnerability Detector module.

```xml
    <enabled>yes</enabled>
    <interval>5m</interval>
    <ignore_time>6h</ignore_time>
    <run_on_start>yes</run_on_start>
```

### Tests

- **[enabled](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/vuln-detector.html#enabled)**

When it is set to `no` the module should be disabled. A debug message should appear:

```
2020/04/21 08:10:39 wazuh-modulesd:vulnerability-detector[71109] wm_vuln_detector.c:5238 at wm_vuldet_init(): DEBUG: Module disabled. Exiting...
```

- **[interval](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/vuln-detector.html#interval)**

Once a scan is completed, the module should wait the `interval` time until running the next one.

- **[ignore_time](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/vuln-detector.html#ignore_time)**

The test has to check that once the scan has reported vulnerabilities for an agent, it only reports new vulnerabilities during the `ignore_time`. Skipping the ones already reported.

- **[run_on_start](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/vuln-detector.html#run_on_start)**

When it is set to `yes`, the scan should run at start-up (after the download of the feeds). Otherwise, it should sleep the `interval` time.

**Comment by BraulioV** [comment]
Hi all,

I'm closing this issue since all the tests described in it are already done and merged in 3.13.

- **enabled**: issue #668 and PR #684 :heavy_check_mark:
- **interval**: issue #667 and PR #686 :heavy_check_mark:
- **ignore_time**: issue #665 and PR #721 :heavy_check_mark:
- **run_on_start**: issue #666 and PR #677 :heavy_check_mark:
Feel free to reopen this issue if you have any requests.

Best regards.
