### ISSUE TITLE
Vulnerability Detector: Integration tests for analyzing scan results

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#663]
| Tier | Type |
|-|-|
| 0 | Operation |

### Description

This issue covers the integration tests to ensure the operation of the detector engine.

The mechanics are intended to be the same for all tests: a sample inventory should be provided, which is evaluated against a preloaded vulnerabilities DB. The scan results are matched with the expected vulnerabilities reported.

Following the scheme defined above, each permutation of agent OS and feed should be treated as a different test.

### Proposed tests

- Ubuntu inventory against Canonical feed #693 
- Debian inventory against Debian feed  #706 
- RHEL/CentOS inventory against RedHat feed #710 

- Ubuntu inventory against NVD #722
- Debian inventory against NVD #734
- RHEL/CentOS inventory against NVD #725 

- Ubuntu inventory against Canonical feed and NVD #737 
- Debian inventory against Debian feed and NVD #737 
- RHEL/CentOS inventory against RedHat feed and NVD #737 

- Windows package inventory against NVD #738 
- Windows system hotfixes against NVD #738

**Comment by grg121** [comment]
I'm with https://github.com/wazuh/wazuh-qa/issues/693

**Comment by xr09** [comment]
Working on #706   Debian inventory / Debian feeds

**Comment by BraulioV** [comment]
Hi all, 

I'm closing this issue since all the proposed tests are done. Here you can see the issues and the PR implementing the tests:

- **Ubuntu inventory against Canonical feed.** 
    - Issue: #693. 
    - PR: #729
- **Debian inventory against Debian feed.** 
    - Issue: #706 . 
    - PR: #740
- **RHEL/CentOS inventory against RedHat feed.** 
    - Issue: #710. 
    - PR: #724
- **Ubuntu inventory against NVD.** 
    - Issue: #722. 
    - PR: #736
- **Debian inventory against NVD.** 
    - Issue: #734. 
    - PR: #736
- **RHEL/CentOS inventory against NVD.** 
    - Issue: #725. 
    - PR: #736
- **Ubuntu inventory against Canonical feed and NVD.** 
    - Issue: #737. 
    - PR: #741
- **Debian inventory against Debian feed and NVD.** 
    - Issue: #737. 
    - PR: #741
- **RHEL/CentOS inventory against RedHat feed and NVD.** 
    - Issue: #737. 
    - PR: #741
- **Windows package inventory against NVD.** 
    - Issue: #738. 
    - PR: #790
- **Windows system hotfixes against NVD.** 
    - Issue: #738. 
    - PR: #790

Regards.
