### ISSUE TITLE
Vuln detector: Add test to check correct behavior with different fix version on same CVEs

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#767]
Hi team,

I opened this issue to add some tests for these use cases that may appear in vulnerability detector:
- CVE that appears on NVD and not in the OVAL.
- CVE that appears in the OVAL but not in NVD.
- CVE that appears in both feeds but there's no patch in OVAL.
- CVE that appears RHEL feed and not in NVD.
- CVE that appears NVD and not in RHEL feed.

**Comment by grg121** [comment]
Hello Team, 

We're working on this test.

What we want to check is that everything works as expected when:

- CVE for a package appears on NVD and not in the OVAL -> A vulnerability alert must be generated based on the NVD criteria
- CVE appear in the OVAL but not in NVD -> A vulnerability alert must be created based on the OVAL criteria
- CVE appear in both feeds but there is no patch in the OVAL -> A vulnerability alert must be created based on the NVD criteria


The last two points have been deprecated due to the last changes in NVD feed relationship with redhat.

**Comment by grg121** [comment]
The two first points are already covered on `test_scan_providers_and_nvd_feeds`.

We will add a case for the last one in that test.

**Comment by grg121** [comment]
## Test cases

| actual version | nvd  | provider | name                                    |
|----------------|------|----------|-----------------------------------------|
| 1\.0           | 0\.5 | 1\.5     | nvd\_vulnerable\_package                |
| 1\.0           | 1\.5 | 0\.5     | provider\_vulnerable\_package           |
| 1\.0           | 0\.5 | 0        | no\_patch\_nvd\_vulnerable\_package     |
| 1\.0           | 1\.5 | 0        | no\_path\_nvd\_non\_vulnerable\_package |
| 1\.0           | 0\.5 | 0\.5     | vulnerable\_package                     |
| 1\.0           | 1\.5 | 1\.5     | non\_vulnerable\_package                |

**Comment by grg121** [comment]
Test branch on Jenkins [ubuntu] https://jenkins-production.wazuh.info/view/Tests/job/test_integration_vulnerability_detector/178/console 
Test branch on Jenkins [centos] https://jenkins-production.wazuh.info/view/Tests/job/test_integration_vulnerability_detector/179/console
