### ISSUE TITLE
Vulnerability Detector: Manual analysis of RHEL reports

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#786]
### Description

The goal of this issue is the analysis of the Vulnerability Detector reports for RHEL agents after the adding of the OVALs as feed instead of the CVE list provided by the Redhat API.

With the help of the [agents_simulator](https://github.com/wazuh/wazuh-tools/tree/master/utils/agents_simulator) we will compare the generated alerts of 3.13 and the new changes for the following OS:

- RHEL5
- RHEL6
- RHEL7
- RHEL8

**Comment by 0xN3utr0n** [comment]
Among the things that should be checked, a few of the most important ones are:

- The kind of vulnerabilities detected: whether they are `affected`, `will-not-fix`, `reffered` etc.
- `RHBA/RHEA` false-positives. We are aware that CVEs which belong to `RHBA` or `RHEA` are prone to generating false-positives, and we want to know just how much of them there are.
- If there are any false-negatives caused by the use of binary name, instead of the source name, for matching.

**Comment by chemamartinez** [comment]
> * The kind of vulnerabilities detected: whether they are `affected`, `will-not-fix`, `reffered` etc.

For now, until we process the vulnerability data from https://access.redhat.com/hydra/rest/securitydata/cve/CVE-XXXX-YYYY.json to get the status of the affected package, the unpatched packages reported by the OVAL can be referred to `Will not fix`, `fix deferred`, `out of support` or `affected` and we are reporting as vulnerable all of them. In the future, when that information is processed, we can evaluate if discarding any of them.

> * `RHBA/RHEA` false-positives. We are aware that CVEs which belong to `RHBA` or `RHEA` are prone to generating false-positives, and we want to know just how much of them there are.

Not found any false positive in the analysis. Although RHBA or RHEA is not strictly related to security patches, they solve CVEs so they are going to be treated as the RHSA.

> * If there are any false-negatives caused by the use of binary name, instead of the source name, for matching.

Not found any false-negative when using the binary of the packages. It has made RHEL detection more accurate.

Closing this issue since all the results have been analyzed for CentOS and RHEL targets.
