### ISSUE TITLE
Test: Rootcheck

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-qa#79]
# Testing: Rootcheck

| Version | Revision | Branch |
| --- | --- | --- |
| 3.9.0 | 3916 | 3.9 |

## Rootkit

- [x] Check `ignore` option.

### CentOS 7

- [x] Check running processes
- [ ] Check hidden ports
- [x] Check unusual files and permissions
- [x] Check hidden files using system calls
- [x] Scan the /dev directory
- [x] Scan network interfaces
- [x] Rootkit checks (rootkit_files.txt, rootkit_trojans.txt, win_malware_rcl.txt

### Ubuntu 16

- [x] Check running processes
- [ ] Check hidden ports
- [x] Check unusual files and permissions
- [x] Check hidden files using system calls
- [x] Scan the /dev directory
- [x] Scan network interfaces
- [x] Rootkit checks (rootkit_files.txt, rootkit_trojans.txt, win_malware_rcl.txt

### Windows 10

- [ ] Check Windows audit
- [ ] Check Windows malware
- [ ] Check Windows application

### CentOS 5
- [x] Check Unix audit, system_audit_rcl.txt, system_audit_ssh.txt, cis_rhel5_linux_rcl.txt

### CentOS 6
- [x] Check Unix audit, system_audit_rcl.txt, system_audit_ssh.txt, cis_rhel6_linux_rcl.txt
- [x] Check Unix audit , cis_rhel_linux_rcl.txt

### CentOS 7
- [x] Check Unix audit, system_audit_rcl.txt, system_audit_ssh.txt, cis_rhel7_linux_rcl.txt
- [x] Check Unix audit , cis_rhel_linux_rcl.txt

### Ubuntu 16
- [x] Check Unix audit, system_audit_rcl.txt, system_audit_ssh.txt, cis_debian_linux_rcl.txt

### Suse 11

- [x] Check Unix audit, system_audit_rcl.txt, system_audit_ssh.txt, cis_sles11_linux_rcl.txt

### Suse 12

- [x] Check Unix audit, system_audit_rcl.txt, system_audit_ssh.txt, cis_sles12_linux_rcl.txt

**Comment by Zenidd** [comment]
### Check `ignore` option
- Rootcheck **keeps throwing alerts** from paths on ignore tags.

This ignore tag `<ignore type="sregex">^/dev</ignore>` is not able to stop rootcheck alerts:

```
** Alert 1556631995.68758937: - ossec,rootcheck,gdpr_IV_35.7.d,
2019 Apr 30 15:46:35 vagrant->rootcheck
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Files hidden inside directory '/dev'. Link count does not match number of files (20,24).
title: Files hidden inside directory '/dev'.
```

**Comment by Zenidd** [comment]
# TESTING ROOTCHECK

## 1. Check running processes:

- To **hide a process** in order to trigger rootcheck, we are using Diamorphine rootkit (thanks to Sergio Cervilla) --> https://github.com/wazuh/Diamorphine/
- The install process in simple and its included on Diamorphine github.

*Maybe the makefile is not able to find the right kernel path to compile diamorphine against it. It can be fixed using this sentence:*
- RPM:
`sudo yum install "kernel-devel-uname-r == $(uname -r)"`
- DEB:
`apt-get install linux-headers-$(uname -r)`

Then, **we can hide process using signaling** `kill -31 <PID>`. To unhide process just enter the same sentence again. It has to **generate an alert** if rootcheck is working properly.

## 2. Check hidden ports

## 3 & 4. Check unusual files and permissions & check hidden files using system calls

- Check this feature by **creating a hidden file** on one of this directories: 

```
"bin", "sbin", "usr/bin",
"usr/sbin", "dev", "lib",
"etc", "root", "var/log",
"var/mail", "var/lib", "var/www",
"usr/lib", "usr/include",
"tmp", "boot", "usr/local",
"var/tmp", "sys"
```

Example: 
`cd /bin ; touch .t0rn ; mkdir rootkitFiles ; cd rootkitFiles ; touch .shit`

 - To test the module that performs system calls we install **Reptile rootkit** https://github.com/f0rb1dd3n/Reptile ; The installation itself triggers alerts.
 
## **5. Scan the /dev directory**
 - **Creating files** to trigger rootcheck:

`cd /dev ; touch .hidden ; mkdir hiddenFiles ; touch .hidden2`


## 6. Scan network interfaces

 - **Enabling promiscous mode** on some interface is enough to trigger rootcheck

`ip link set [interface] promisc on`

## 7. Unix audit.

 - Disabling the other rootcheck options is useful to detect audit alerts easy.

```
	<check_unixaudit>yes</check_unixaudit>
	<check_files>no</check_files>
	<check_trojans>no</check_trojans>
	<check_dev>no</check_dev>
	<check_sys>no</check_sys>
	<check_pids>no</check_pids>
	<check_ports>no</check_ports>
	<check_if>no</check_if>
```

 - **Including the desired audit files**(suse11 on this example):
```
    <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/cis_sles11_linux_rcl.txt</system_audit>
```
- **ossec-control restart** after to start throwing alerts to manager.
